SELECT ?count ?fabrication_method ?fabrication_method_label ?example
WHERE {
  { 
    SELECT (COUNT(DISTINCT(?file)) AS ?count) ?fabrication_method (SAMPLE(?file) AS ?example) WHERE {
      ?file wdt:P2079 ?fabrication_method. 
    }
    GROUP BY ?fabrication_method
  }
    SERVICE <https://query.wikidata.org/sparql> {
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". 
                              ?fabrication_method rdfs:label ?fabrication_method_label.
                             } 
  }
}
ORDER BY DESC(?count)
