# Most populous first-level country subdivisions without legislatures 
# from [[d:Property_talk:P194#Most_populous_first-level_subdivisions_without_legislature]]
# Based on "Largest first-level country subdivisions" at https://
