PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX v: <http://www.wikidata.org/prop/statement/>

SELECT ?p ?pLabel ?oLabel ?cobLabel WHERE {
   ?p wdt:P27 wd:Q408 .
   OPTIONAL {
     ?p wdt:P495 ?o MINUS {?p wdt:P495 wd:Q408} .
   }
  
  ?p wdt:P19 ?pob .
  ?pob wdt:P17 ?cob MINUS {?pob wdt:P17 wd:Q408} .
   
   SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
   }
 }
