SELECT ?statement ?subjectLabel ?subject ?propertyLabel ?property ?objectLabel ?object ?refURL WHERE {
  hint:Query hint:optimizer "None" .
  ?ref pr:P854 ?refURL 
  FILTER (CONTAINS(str(?refURL),'http://www.ppk-kp3k.kkp.go.id/direktori-pulau/index.php/public_c/pulau_info/')) . 
  ?statement prov:wasDerivedFrom ?ref .
  ?subject ?p ?statement .
  ?property wikibase:claim ?p .
  ?property wikibase:statementProperty ?ps .
  ?statement ?ps ?object .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
  }
}
