#defaultView:Table
SELECT DISTINCT ?entity ?entityLabel WHERE {
  ?entity wdt:P31 wd:Q759421.
  ?entity wdt:P131 ?location .      # which have a location
  ?location wdt:P131* wd:Q1198 .    # which is in NRW
  FILTER(!EXISTS { ?entity wdt:P3974 ?x. })
  SERVICE wikibase:label { bd:serviceParam wikibase:language "de" }
}
ORDER BY ?entityLabel
