SELECT ?item ?itemLabel ?aunamendi WHERE {
  ?item wdt:P3218 ?aunamendi .
  ?item wdt:P735 wd:Q19273889 .
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  
  }
