SELECT DISTINCT ?item ?ru ?en WHERE {
  ?item (wdt:P31/wdt:P279*) wd:Q192287.
  ?item rdfs:label ?ru.
    OPTIONAL {
    ?item rdfs:label ?en.
    FILTER((LANG(?en)) = "en")
  }
  FILTER((LANG(?ru)) = "ru")
}
