SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P407 wd:Q7026 . 
  MINUS { ?entity wdt:P50 []; wdt:P407 wd:Q7026  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
