#Expedities Nederlands-Indië en Indonesië
SELECT ?item ?itemLabel ?begindatum ?einddatum ?deelnemer ?deelnemerLabel ?geografische_locatie
WHERE {
  { ?item wdt:P31 wd:Q2401485. }
  UNION
  { ?item wdt:P31 wd:Q366301. }
  { ?item wdt:P17 wd:Q188161. }#Nederlands-Indie, kolonie binnen NL
  UNION
  { ?item wdt:P17 wd:Q252. }#Indonesie
  UNION
  { ?item wdt:P17 wd:Q941881. }#Nederlands Nieuw Guinea
 SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  OPTIONAL { ?item wdt:P710 ?deelnemer. }
  OPTIONAL { ?item wdt:P580 ?begindatum. }
  OPTIONAL { ?item wdt:P582 ?einddatum. }
  OPTIONAL { ?item wdt:P625 ?geografische_locatie. }
OPTIONAL { ?item wdt:P373 ?Commonscategorie. }
}
