SELECT ?item ?itemLabel ?coordinate ?elevation ?isolation ?prominence
WHERE 
{
  ?item wdt:P31 wd:Q54050.
  ?item wdt:P4552 wd:Q4210.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  OPTIONAL { ?item wdt:P625 ?coordinate . }
  OPTIONAL { ?item wdt:P2044 ?elevation . }
  OPTIONAL { ?item wdt:P2659 ?isolation . }
  OPTIONAL { ?item wdt:P2660 ?prominence . }
}
