SELECT ?item ?itemLabel ?itemDescription 
{
    ?item wdt:P31 wd:Q26877490 .
    ?item wikibase:sitelinks 1 .
    [] schema:about ?item ; schema:isPartOf <https://hu.wikipedia.org/> .
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en,hu". }
}         
