# count apni id taxa without authors


SELECT (COUNT(DISTINCT ?item) AS ?count) WHERE {
  #hint:Prior hint:gearing "forward" .
  ?item wdt:P5984 ?apni_id.
  ?item p:P225 ?stat . 
  ?stat ps:P225 ?taxon_name.
  minus {?stat pq:P405 ?author.}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } 

} 
