# Articles in wikidata, with an AFD_pub_id with Tim R. New as author
SELECT ?item  ?itemLabel ?link WHERE {
  ?item wdt:P6982 ?AFD_pub_id.
  ?item wdt:P50 wd:Q21338300.
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
    BIND (URI(CONCAT("https://biodiversity.org.au/afd/publication/",str(?AFD_pub_id))) as ?link)  
    }
ORDER BY ?item ?itemLabel ?AFD_pub_id
