#Langues mortes

#added before 2016-10

#defaultView:Table
SELECT DISTINCT ?language ?languageLabel ?locutors ?date
WHERE 
{
	?language wdt:P31/wdt:P279* wd:Q34770 .  # find instances of subclasses of language
	?language wdt:P1098 ?locutors .
	# ?locutors pq:P585 ?date .
  	FILTER (?locutors = 0) .
	SERVICE wikibase:label {
		bd:serviceParam wikibase:language "fr" .
	}

}
ORDER BY DESC(?locutors)
LIMIT 300
