PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX v: <http://www.wikidata.org/prop/statement/>
PREFIX q: <http://www.wikidata.org/prop/qualifier/>
PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?item ?itemLabel WHERE {
  ?item p:P569 ?stmt .
  ?stmt prov:wasDerivedFrom ?ref.
  
  ?ref pr:P143 wd:Q206855 .
      
  filter exists {
    ?item p:P569 ?stmt2 filter(?stmt != ?stmt2) .
  }
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
  }
}
