SELECT ?item ?itemLabel 
WHERE 
{
  ?item wdt:P31 wd:Q3305213 .
  ?item wdt:P170 wd:Q209615 .
  Filter not exists{ ?item p:P528/pq:P972 wd:Q70004331 .}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
