SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P361 wd:Q16024163 . 
  MINUS { ?entity wdt:P131 []; wdt:P361 wd:Q16024163  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
