SELECT ?item ?itemLabel ?subject ?subjectLabel ?article WHERE {

  ?item wdt:P1433 wd:Q15987216 .
  ?item wdt:P31 wd:Q19389637.
  ?item wdt:P921 ?subject .
  ?article 	schema:about ?subject ;
			schema:isPartOf <https://en.wikisource.org/> .

  OPTIONAL { ?article2 schema:about ?subject ; schema:isPartOf <https://en.wikipedia.org/> }
  FILTER ( !bound(?article2) )
  
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en" .
    }

} 
