SELECT ?item
       {
          {?item ?property wd:Q162684.} UNION { ?item ?property2 [wdt:P361 wd:Q162684].} 
          ?item wdt:P31 wd:Q5; wikibase:statements ?st
       }
       ORDER BY ASC(?st) ?item 
       LIMIT 3000
