SELECT DISTINCT ?item ?label ?output4 WHERE {
  ?item skos:altLabel ?label .
  ?item wdt:P31 wd:Q5.
  ?item wdt:P6379 wd:Q99349995.
    FILTER NOT EXISTS {?item wdt:P53 []}
  BIND(replace(?label,"([A-Z])[a-z\u0080-\uFFFF]+ (?:([A-Z])[a-z\u0080-\uFFFF]+ )?(?:([A-Z])[a-z\u0080-\uFFFF]+ )?(?:([A-Z])[a-z\u0080-\uFFFF]+ )?(.*)([A-Z][a-z\u0080-\uFFFF]+)$","$1.$2.$3.$4. $5$6") AS ?output) .
  BIND(replace(?output,"[\\.]+",".") AS ?output2) .
  BIND(replace(?output2,"([A-Z])\\.? ?([A-Z])\\.?(?: ?([A-Z])\\.?)? ","$1.$2.$3. ") AS ?output3) .
  BIND(replace(?output3,"[\\.]+",".") AS ?output4) .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "nl, en". }
  FILTER((LANG(?label)) = "nl")
  FILTER(REGEX(?label, "^[A-z]{3,}"))
  FILTER(!REGEX(?label, "\\("))#geen altnamen met haakjes
  FILTER NOT EXISTS {
  ?item skos:altLabel ?alt .
    FILTER(REGEX(?alt, ?output4))#bestaat al
    }
}
