SELECT DISTINCT ?item
  WITH {
  SELECT ?item WHERE {
  ?item wdt:P31 wd:Q5.
  ?item wdt:P6379 wd:Q17153751.
  FILTER NOT EXISTS {?item wdt:P569 []}.  
  FILTER NOT EXISTS {?item wdt:P7763 []}.  
  FILTER NOT EXISTS {?item wdt:P570 []}.  
  } 
  } AS %results
  WHERE {
    INCLUDE %results.
  ?sitelink schema:about ?item .
  ?sitelink schema:inLanguage ?lang .   
  ?sitelink schema:isPartOf [ wikibase:wikiGroup "wikipedia" ] .
}
