SELECT DISTINCT ?itemLabel ?item  ?origineleNaam  ?naam ?auteursrechtenstatusLabel ?RKD ?geboortedatum ?overlijdensdatum ?gelijk 
{
	?item wdt:P6379 wd:Q99349995 .
  ?item wdt:P650 ?rkd.
    ?item wdt:P31 wd:Q5.
    ?item rdfs:label ?label.
  FILTER NOT EXISTS {
   ?item p:P569 [ ps:P569 ?geboortedatum;
                    prov:wasDerivedFrom 
                    [ pr:P813 ?geraadpleegd; 
                    ]
                  ].
    }
      ?item wdt:P569 ?geboortedatum.
    SERVICE wikibase:label { bd:serviceParam wikibase:language "nl" } .
}
ORDER BY ?itemLabel 
LIMIT 300
