SELECT DISTINCT ?item  ?itemLabel ?altLabel ?rechtsvormLabel {
  ?item wdt:P1454 ?rechtsvorm.
  ?rechtsvorm wdt:P31 wd:Q56871091.#Dutch legal form
  OPTIONAL { ?item skos:altLabel ?altLabel . FILTER (lang(?altLabel) = "nl") }
  FILTER NOT EXISTS { ?item wdt:P3220 [].}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "nl". } 
}
