SELECT DISTINCT ?item ?itemLabel ?articleEN ?articleNL WHERE {
  ?item wdt:P31 wd:Q5.
  ?item wdt:P6379 wd:Q1782422.
OPTIONAL {
    ?articleNL schema:about ?item.
    ?articleNL schema:isPartOf <https://nl.wikipedia.org/>.
  }
OPTIONAL {
    ?articleEN schema:about ?item.
    ?articleEN schema:isPartOf <https://en.wikipedia.org/>.
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,nl". }
}
