SELECT DISTINCT ?item ?itemLabel ?date_of_birth ?article WHERE {
    ?item wdt:P21 wd:Q6581072.
    ?item wdt:P6379 wd:Q2191118.
    OPTIONAL {
    ?article schema:about ?item .
    ?article schema:isPartOf <https://nl.wikipedia.org/>.
      }
  OPTIONAL { ?item wdt:P569 ?date_of_birth. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "nl, en". }
}
