PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?item ?itemLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "nl, en". }
  ?item wdt:P31 wd:Q5.
  ?item wdt:P570 ?death.
  ?object wdt:P170 ?item.
  ?object wdt:P195 ?collection.
  FILTER(?death >= "1949-01-01T00:00:00Z"^^xsd:dateTime)
  FILTER(?death < "1950-01-01T00:00:00Z"^^xsd:dateTime)
}
