SELECT ?item ?itemLabel 
WHERE 
{
  ?item wdt:P31 wd:Q5. 
  ?item wdt:P106 wd:Q59938940.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],nl". } # <span lang="en" dir="ltr" class="mw-content-ltr">Helps get the label in your language, if not, then en language</span>
}
