SELECT DISTINCT ?item ?itemLabel ?age WHERE {
  ?item wdt:P31 wd:Q5.
  ?item wdt:P6379 wd:Q17153751.
  ?item wdt:P569 ?born .
  ?item wdt:P570 ?death .
  bind( year(?death) - year(?born)  as ?age )
  FILTER (?age > 120).  
}
