SELECT DISTINCT ?item ?title
WHERE {
  hint:Query hint:optimizer "None".
{  SERVICE wikibase:mwapi {
    bd:serviceParam wikibase:api "Search";
                    wikibase:endpoint "www.wikidata.org";
                    mwapi:srsearch "\"liver transplantation\" and haswbstatement:P31=Q13442814".
    ?page_title wikibase:apiOutput mwapi:title.
  }}
  UNION
{  SERVICE wikibase:mwapi {
    bd:serviceParam wikibase:api "Search";
                    wikibase:endpoint "www.wikidata.org";
                    mwapi:srsearch "\"liver transplantation\" -and haswbstatement:P31=Q13442814".
    ?page_title wikibase:apiOutput mwapi:title.
  }}
UNION  
{  SERVICE wikibase:mwapi {
    bd:serviceParam wikibase:api "Search";
                    wikibase:endpoint "www.wikidata.org";
                    mwapi:srsearch "\"liver transplantations\" and haswbstatement:P31=Q13442814".
    ?page_title wikibase:apiOutput mwapi:title.
  }}
  UNION
{  SERVICE wikibase:mwapi {
    bd:serviceParam wikibase:api "Search";
                    wikibase:endpoint "www.wikidata.org";
                    mwapi:srsearch "\"liver transplantations\" -and haswbstatement:P31=Q13442814".
    ?page_title wikibase:apiOutput mwapi:title.
  }}
  BIND(IRI(CONCAT(STR(wd:), ?page_title)) AS ?item)
  FILTER NOT EXISTS { ?item wdt:P921 wd:Q1368191. }
  
  ?item wdt:P31 wd:Q13442814;
        wdt:P1476 ?title.
  FILTER CONTAINS(LCASE(?title), "liver").
  FILTER CONTAINS(LCASE(?title), "transplantation").
}
#LIMIT 100
