# Wikidata items for concepts that have a MeSH Descriptor ID (P486) and a Disease Ontology ID (P699)
# and optionally a Wikidata label in English and multiple Indian languages
# sorted by number of Wikimedia sitelinks for the concept

SELECT 
  DISTINCT ?item 
  (CONCAT("{{Scholia-inline|", REPLACE(STR(?item), ".*Q", "Q"), "}}") AS ?q)
  ?English ?Hindi ?Bangla ?Marathi ?Telugu ?EastPunjabi ?Kannada ?Odia ?Urdu ?Malayalam
  ?sitelinks 

WHERE {
  ?item wdt:P486 [] .  
  ?item wdt:P699 [] .  
  ?item wikibase:sitelinks ?sitelinks .

  OPTIONAL { ?item rdfs:label ??English filter (lang(?English) = "en") . }

   { ?item rdfs:label ?Hindi filter (lang(?Hindi) = "hi") . }
  UNION { ?item rdfs:label ?Bangla filter (lang(?Bangla) = "bn") . }

  UNION { ?item rdfs:label ?Marathi filter (lang(?Marathi) = "mr") . }
  UNION { ?item rdfs:label ?Telugu filter (lang(?Telugu) = "te") . }
  UNION { ?item rdfs:label ?EastPunjabi filter (lang(?EastPunjabi) = "pa") . }
  UNION { ?item rdfs:label ?Kannada filter (lang(?Kannada) = "kn") . }
  UNION { ?item rdfs:label ?Odia filter (lang(?Odia) = "or") . }
  UNION { ?item rdfs:label ?Urdu filter (lang(?Urdu) = "ur") . }
  UNION { ?item rdfs:label ?Malayalam filter (lang(?Malayalam) = "ml") . }
  FILTER (?sitelinks > 50)
}
ORDER BY DESC(?sitelinks)
