embed.html#SELECT ?prop ?propLabel ?propDescription WHERE {
    ?prop wikibase:propertyType wikibase:CommonsMedia
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
