SELECT ?item 
	(COUNT(DISTINCT ?page) as ?ct) 
	(GROUP_CONCAT(DISTINCT CONCAT("[",str(?page)," ",?title,"]"); separator="; ") as ?articles)
	(GROUP_CONCAT(DISTINCT ?l; separator=" ") as ?langs)
	(GROUP_CONCAT(DISTINCT CONCAT("{","{Label","
