embed.html#SELECT DISTINCT ?w ?t ?a ?n ?d
WHERE {
{?a ?p1 wd:Q168751.} UNION {?a ?p2 [wdt:P361 wd:Q168751].}
?w wdt:P50 ?a ; wdt:P921 wd:Q179924 .
OPTIONAL {?w wdt:P577 ?d.} 
OPTIONAL {?w wdt:P1476 ?t.} 
?a rdfs:label ?n.
FILTER(LANG(?n) = "en").
}
GROUP BY ?w ?t ?a ?n ?d
ORDER BY DESC(?d)
LIMIT 100
