#exhibitions in the National Museum of Ethnology
SELECT ?item ?itemLabel 
WHERE 
{
  { ?item wdt:P31 wd:Q29023906 . } #temporary exhibition/tentoonstelling
  UNION 
  { ?item wdt:P31 wd:Q464980 . } #exhibition/opstelling in vaste collection
  ?item wdt:P276 wd:Q17339437 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "nl,en". }
}
