SELECT DISTINCT ?item ?itemLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "nl, en". }

  ?item wdt:P31 wd:Q5 .
  ?item wdt:P27 wd:Q29999 .
  ?item wdt:P106 wd:Q36180 .
  ?item wdt:P570 ?died.
  FILTER (?died >= "1952-01-01T00:00:00Z"^^xsd:dateTime && ?died < "1953-01-01T00:00:00Z"^^xsd:dateTime)
}
