SELECT DISTINCT ?item ?itemLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  OPTIONAL { ?item wdt:P301/wdt:P1269 ?facet_of. }
#   FILTER NOT EXISTS { ?item wdt:P31 wd:Q59541917 . }
}
