SELECT ?item ?itemLabel ?start ?end (CONCAT(STR(DAY(?start)),".",STR(MONTH(?start)),".",STR(YEAR(?start))) as ?displayDateStart)(CONCAT(STR(DAY(?end)),".",STR(MONTH(?end)),".",STR(YEAR(?end))) as ?displayDateEnd) WHERE { ?item wdt:P31 wd:Q29023906. ?item wdt:P276 wd:Q703640. ?item wdt:P580 ?start. ?item wdt:P582 ?end. SERVICE wikibase:label { bd:serviceParam wikibase:language 'de' }    } ORDER BY ?start
