SELECT DISTINCT ?item ?dobyear ?dodyear ?sl WHERE {
  ?item wdt:P69/wdt:P361? wd:Q273579; wdt:P31 wd:Q5; wikibase:sitelinks ?sl .
  OPTIONAL {
    ?item wdt:P569 ?dob .
    BIND(YEAR(?dob) AS ?dobyear) .
  }
  OPTIONAL {
    ?item wdt:P570 ?dod .
    BIND(YEAR(?dod) AS ?dodyear) .
  }
  FILTER(BOUND(?dobyear) && ?dobyear <= 1950) .
}
