#articles Prof. Voit
SELECT ?work ?workLabel ?count 
WITH {
  SELECT (count(?citing_work) as ?count) ?work WHERE {
    ?work wdt:P50 wd:Q21256003 .
    OPTIONAL { ?citing_work wdt:P2860 ?work . }
  }
  GROUP BY ?work
} AS %result
WHERE {
  INCLUDE %result
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }        
} ORDER BY DESC(?count)
LIMIT 55
