# click "Execute" to run the query, then (on the right side) below "Display" select the link "Map" or "Image Grid"
SELECT 
	?item 
	?itemLabel 
	(GROUP_CONCAT(?instanceLabel; separator=", ") as ?instance_of)
	(SAMPLE(?coord) as ?coordinates)
	(SAMPLE(?img) as ?image)
WHERE
{
	VALUES ?item { wd:Q22671354 wd:Q2636368 wd:Q9285794 wd:Q9173390 wd:Q23058053 wd:Q22939736 wd:Q22945245 wd:Q22939575 wd:Q8080468 wd:Q22674448  }
	OPTIONAL {?item wdt:P625 ?coord } .  
	OPTIONAL {?item wdt:P31 ?instance } .   
  	OPTIONAL {?item wdt:P18 ?img } .   
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en,en" 
                           . ?item rdfs:label ?itemLabel
                           . ?instance rdfs:label ?instanceLabel }
}
GROUP BY ?item ?itemLabel 
