# click "Execute" to run the query, then (on the right side) below "Display" select the link "Map" or "Image Grid"
SELECT 
	?item 
	?itemLabel 
	(GROUP_CONCAT(?instanceLabel; separator=", ") as ?instance_of)
	(SAMPLE(?coord) as ?coordinates)
	(SAMPLE(?img) as ?image)
WHERE
{
	VALUES ?item { wd:Q2727560 wd:Q510799 wd:Q22920647 wd:Q23022589 wd:Q23034829 wd:Q22945654 wd:Q22945895 wd:Q21153247 wd:Q22945980 wd:Q22920999  }
	OPTIONAL {?item wdt:P625 ?coord } .  
	OPTIONAL {?item wdt:P31 ?instance } .   
  	OPTIONAL {?item wdt:P18 ?img } .   
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en,en" 
                           . ?item rdfs:label ?itemLabel
                           . ?instance rdfs:label ?instanceLabel }
}
GROUP BY ?item ?itemLabel 
