#defaultView:Map
SELECT ?item ?itemLabel ?propertyLabel ?property ?coord WHERE {
  ?item (wdt:P31/wdt:P279*) wd:Q41176.
  ?item ?property wd:Q13371.
  OPTIONAL { ?item wdt:P625 ?coord. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
