SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity (wdt:P31/(wdt:P279*)) wd:Q33506;  wdt:P17 ?countries FILTER (?countries IN (wd:Q28, wd:Q34, wd:Q36, wd:Q38, wd:Q39, wd:Q40, wd:Q77, wd:Q142, wd:Q145, wd:Q183, wd:Q212, wd:Q233, wd:Q252, wd:Q298, wd:Q399, wd:Q403, wd:Q414, wd:Q657, wd:Q668, wd:Q962, wd:Q963, wd:Q974, wd:Q1006, wd:Q1036, wd:Q1033, wd:Q1037, wd:Q29999)). ?entity wdt:P17 ?grouping .} GROUP BY ?grouping HAVING (?count >= 5) ORDER BY DESC(?count) LIMIT 1000
