SELECT DISTINCT ?country ?item ?part ?mp 
WHERE {
  ?country wdt:P31 wd:Q6256 .
  OPTIONAL { 
    VALUES ?type { wd:Q10553309 wd:Q37002670 }
    ?item wdt:P31/wdt:P279* ?type ; wdt:P1001 ?country . 
    FILTER NOT EXISTS { ?item wdt:P576 [] } . # no end date
    OPTIONAL { ?item wdt:P527 ?part . ?part wdt:P279* wd:Q4175034 } 
    OPTIONAL { ?mp wdt:P279* wd:Q4175034 ; wdt:P361 ?item } 
    FILTER NOT EXISTS { ?part wdt:P279* wd:Q1758037 }
    FILTER NOT EXISTS { ?mp wdt:P279* wd:Q1758037 }
  }
}
