SELECT DISTINCT ?item ?itemlabelfr ?fr ?itemlabelar ?ar ?field ?fieldlabel { ?item wdt:P2521 ?ar . FILTER(lang(?ar)="ar") OPTIONAL {	?item wdt:P2521 ?fr . 	FILTER(lang(?fr)="fr") } OPTIONAL { 	?item wdt:P425 ?field   SERVICE wikibase:label { bd:serviceParam wikibase:language "ar" . ?field rdfs:label ?fieldlabel } } SERVICE wikibase:label { bd:serviceParam wikibase:language "ar" . ?item rdfs:label ?itemlabelar } SERVICE wikibase:label { bd:serviceParam wikibase:language "fr" . ?item rdfs:label ?itemlabelfr } }
