#Locations of horse stud farm all over Japan
#defaultView:Map
SELECT ?stud ?studLabel ?studDescription ?studLabel_ja ?countryLabel ?website ?coord ?article
WHERE {
	?stud wdt:P31/wdt:P279* wd:Q108696 ;
		wdt:P17 wd:Q17
	OPTIONAL {
		?stud rdfs:label ?studLabel_ja filter (lang(?studLabel_ja) = "ja")
	}
    OPTIONAL {
		?article schema:about ?stud .
        ?article schema:isPartOf <https://ja.wikipedia.org/>.
	}
    OPTIONAL {
		?stud wdt:P856 ?website
	}
    OPTIONAL {
		?stud wdt:P625 ?coord
	}
	SERVICE wikibase:label {
		bd:serviceParam wikibase:language "en,ja" .
	}
}
