SELECT ?student ?studentLabel where {
  ?student p:P69 ?school .
  ?school ps:P69 wd:Q523926 .
  ?school rdf:type wdno:P512 .
    SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
  }
}
