SELECT ?item 
WHERE { 
  ?item wdt:P1343 wd:Q602358; wdt:P1343 wd:Q17378135; wdt:P31 wd:Q5 .
  #?item p:P1343 [ps:P1343 wd:Q602358; pq:P805 ?article] ; wdt:P2924 ?id ; wdt:P31 wd:Q5 .
  #?link schema:about ?article ; schema:isPartOf <https://ru.wikisource.org/> . 
FILTER NOT EXISTS { ?wru schema:about ?item ; schema:isPartOf <https://ru.wikipedia.org/> . }
}
