SELECT ?item 
WHERE { 
  ?item wdt:P1343 wd:Q602358 ; wdt:P1343 wd:Q1960551 ; wdt:P31 wd:Q5 .
FILTER NOT EXISTS { ?wru schema:about ?item ; schema:isPartOf <https://ru.wikipedia.org/> . }
#OPTIONAL {?item wikibase:sitelinks ?linkcount .} 
#LIMIT 1000
}
