index.html#SELECT DISTINCT
  ?work
  (COUNT(?work) AS ?count)
  (SAMPLE(?id)  AS ?sampleId)
  (SAMPLE(?url) AS ?sampleStatement)
WHERE {
  ?x wdt:P3365 ?id .
  FILTER REGEX(?id, "%[0-9][0-9]|\\(") .
  BIND(REPLACE(STR(?id),".*(\\(|%28)|(\\)|%29).*","") AS ?work) .
  BIND(URI(CONCAT(STR(?x),"#P3365")) AS ?url)
}
GROUP BY ?work
ORDER BY DESC(?count)
