SELECT (CONCAT("-", replace(str(?x),str(wd:),"")) as ?s) (CONCAT("A", lang(?alias)) as ?p) (CONCAT('"', ?alias, '"') as ?o)
WHERE {
  ?x wdt:P31 wd:Q16521 ;
     rdfs:label    ?alias ;
     skos:altLabel ?alias .
}
LIMIT 10000
