SELECT DISTINCT (uri(concat("https://www.wikidata.org/wiki/", substr(str(?item),32))) as ?item_link) ?label ?desc
WHERE {
  VALUES ?prop { wdt:P3365 wdt:P6404 wdt:P7993 wdt:P4223 wdt:P5844 wdt:P9621 wdt:P7620 }
  ?item ?prop ?id.
  ?item schema:description ?desc FILTER (lang(?desc) = "it" && regex(?desc, "^[A-Z][a-z].*")).
  OPTIONAL {?item rdfs:label ?label FILTER (lang(?label) = "it").}
  FILTER NOT EXISTS { ?item wdt:P31 wd:Q11344 }
  FILTER NOT EXISTS { ?item wdt:P31 wd:Q3624078 }
  FILTER NOT EXISTS { VALUES ?item { wd:Q12544 wd:Q48961 wd:Q198998 wd:Q9592 wd:Q2249415 wd:Q766677 } }
  FILTER NOT EXISTS {
    VALUES ?country { wd:Q3024240 wd:Q96196009 wd:Q179164 wd:Q619610 wd:Q3624078 wd:Q6256 wd:Q107390 wd:Q106458883 }
    ?item wdt:P31/wdt:P279? ?country .
    FILTER (regex(?desc, "^Stato ")) .
  }
}
ORDER BY ?desc
