SELECT DISTINCT ?item ?st (CONCAT("[",str(?url)," ws]") as ?ws) ?entry
{
      ?entry wdt:P1433 wd:Q665807 ; wdt:P921 ?item .
      ?item wikibase:statements ?st .  
      ?url schema:about ?entry ; schema:isPartOf <https://de.wikisource.org/> .
      ?entry wdt:P31 wd:Q19389637 .
}
ORDER BY ASC(?st) ?item
LIMIT 100
