SELECT (wd:Q2481549 as ?item) ("father or mother (P22/P25)" as ?legend) (GROUP_CONCAT(?p;separator = ",") as ?labels) (GROUP_CONCAT(?ct;separator = ",") as ?values)
{
	{	SELECT  ?p (COUNT(DISTINCT ?mainsubject) as ?ct)
		{
			?entry 	wdt:P31 wd:Q19389637
  			; 		wdt:P1433 wd:Q665807 .
          	?entry wdt:P921 ?mainsubject
          	OPTIONAL { ?mainsubject wdt:P22 ?dob }
          	OPTIONAL { ?mainsubject wdt:P25 ?dod }
			BIND(CONCAT(IF(!BOUND(?dob),"---","father-"),IF(!BOUND(?dod),"---","-mother")) as ?p)
		}
		GROUP BY  ?p
		ORDER BY ASC(?p)                  
	}
}
