SELECT distinct ?country ?countryLabel ?language ?languageLabel
WHERE {
    ?country  wdt:P31 wd:Q3624078
    FILTER NOT EXISTS {?country wdt:P31 wd:Q3024240}
    optional {?country wdt:P37 ?language}
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
