SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity wdt:P131+ wd:Q18259. ?entity wdt:P31 ?grouping .} GROUP BY ?grouping HAVING (?count < 5) ORDER BY DESC(?count) LIMIT 1000
