SELECT ?item ?itemLabel ?itemDescription
{
	?item wdt:P31 wd:Q19389637 . 
    MINUS { ?item wdt:P921 [] }
	SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
LIMIT 100
