SELECT DISTINCT ?item ?itemLabel ?seats WHERE {
  ?item wdt:P1342 ?seats ;
        wdt:P31/wdt:P279* wd:Q11204 .
  ?number wdt:P1181 ?seats ;
          wdt:P31/wdt:P279* wd:Q49008 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
} ORDER BY DESC(?seats) 
