SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P31 wd:Q61220733 . 
  MINUS { ?entity wdt:P4908 []; wdt:P31 wd:Q61220733  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
