SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity wdt:P31 wd:Q3305213; wdt:P195 ?collection. ?collection wdt:P17 wd:Q29. ?entity wdt:P195 ?grouping .} GROUP BY ?grouping HAVING (?count < 50) ORDER BY DESC(?count) LIMIT 1000
