SELECT ?item (COUNT(DISTINCT ?map) AS ?item_count) (COUNT(DISTINCT ?stmt) AS ?stmt_count) WHERE {
           
           hint:Query hint:optimizer "None" .
           ?class wdt:P195 wd:Q56753539 .    # KTop
           ?map wdt:P195 ?class .
           ?map wdt:P31/wdt:P279* wd:Q4006 .
           {?map p:P180 ?stmt . ?stmt ps:P180 ?item }
           UNION
           {?map p:P921 ?stmt . ?stmt ps:P921 ?item }
           MINUS {?item wdt:P31 wd:Q17146139}
          
         
        }  GROUP BY ?item
        ORDER BY DESC (?item_count) DESC (?stmt_count)
