SELECT ?item 
WHERE 
{
  ?item wdt:P31/wdt:P279* wd:Q41176.
  MINUS {?item p:P31 wd:Q24354 } . 
  ?item p:P669 ?street .
  ?street ps:P669 wd:Q1841356 .
  OPTIONAL {?street pq:P670 ?streetno } . 
}
ORDER BY xsd:integer(?streetno)
