SELECT ?item WHERE {
{
{
    ?item wdt:P31 wd:Q202444 .
} UNION {
    ?item wdt:P31 wd:Q11879590 .
} UNION {
    ?item wdt:P31 wd:Q12308941 .
} UNION {
    ?item wdt:P31 wd:Q3409032 .
}
  ?item wdt:P31 wd:Q4167410 .
}
  UNION { values ?item { wd:Q884375 } }
}
