#Hermitage paintings
SELECT ?pic ?labelRu ?labelEn ?labelBa ?cat_num ?website WHERE {
  ?pic wdt:P31 wd:Q33506	.
  ?pic wdt:P131 wd:Q911.
 OPTIONAL {?pic wdt:P7414 ?cat_num }.
 OPTIONAL {?pic wdt:P856 ?website }.
 OPTIONAL {
    ?pic rdfs:label ?labelEn.
    FILTER((LANG(?labelEn)) = "en")
  }
  OPTIONAL {
    ?pic rdfs:label ?labelRu.
    FILTER((LANG(?labelRu)) = "ru")
  }
  OPTIONAL {
    ?pic rdfs:label ?labelBa.
    FILTER((LANG(?labelBa)) = "ba")
  }
}
