SELECT ?l ?lemma ?example WHERE {
   ?l a ontolex:LexicalEntry ; dct:language ?language ;
        wikibase:lemma ?lemma ; p:P5831 ?statement.
  ?language wdt:P218 'pl'.
  ?statement ps:P5831 ?example.
  FILTER NOT EXISTS {?statement pq:P6072 ?sense }
} ORDER BY ?lemma
