#Eskulturak Donostian
#defaultView:Map
SELECT DISTINCT ?item ?itemLabel ?coor ?image WHERE {
  ?item wdt:P131 wd:Q10313.
  ?item wdt:P31 wd:Q860861.
  OPTIONAL { ?item wdt:P625 ?coor. }
  OPTIONAL { ?item wdt:P18 ?image. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "eu,es". }
}
ORDER BY ?itemLabel
