#Eskulturak Donostian mapa
#defaultView:Map
SELECT DISTINCT ?item ?itemLabel ?coor ?image WHERE {
  ?item wdt:P131* ?non.
  wd:Q47588 wdt:P527 ?non.
  ?item wdt:P31 wd:Q8502.
  OPTIONAL { ?item wdt:P625 ?coor. }
  OPTIONAL { ?item wdt:P18 ?image. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "eu,es". }
}
ORDER BY ?itemLabel
