SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P1174/psv:P1174 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P1174 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
