SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P1868/psv:P1868 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P1868 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
