SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2769/psv:P2769 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2769 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
