SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2555/psv:P2555 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2555 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
