SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2556/psv:P2556 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2556 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
