SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2130/psv:P2130 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2130 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
