SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2595/psv:P2595 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2595 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
