SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P3629/psv:P3629 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P3629 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
