SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P1697/psv:P1697 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P1697 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
