SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2312/psv:P2312 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2312 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
