SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2213/psv:P2213 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2213 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
