SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P1314/psv:P1314 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P1314 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
