SELECT ?id ?idLabel WHERE {
    ?id p:P2547/psv:P2547 [ wikibase:quantityUnit wd:Q253276 ]
    FILTER(?id != wd:Q4115189 && ?id != wd:Q13406268 && ?id != wd:Q15397819)
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
