SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2097/psv:P2097 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2097 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
