SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2196/psv:P2196 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2196 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
