SELECT ?id ?idLabel ?type ?typeLabel WHERE {
    ?id p:P2386/psv:P2386 [ wikibase:quantityUnit wd:Q208788 ] .
    OPTIONAL { ?id wdt:P31 ?type }
    FILTER(?id != wd:Q4115189 && ?id != wd:Q13406268 && ?id != wd:Q15397819)
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
