SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2325/psv:P2325 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2325 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
