SELECT ?id ?idLabel ?type ?typeLabel WHERE {
    ?id p:P5448/psv:P5448 [ wikibase:quantityUnit wd:Q3312063 ] .
    OPTIONAL { ?id wdt:P31 ?type }
    FILTER(?id != wd:Q4115189 && ?id != wd:Q13406268 && ?id != wd:Q15397819)
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
