SELECT ?id ?idLabel ?type ?typeLabel WHERE {
    ?id p:P5027/psv:P5027 [ wikibase:quantityUnit wd:Q35397282 ] .
    OPTIONAL { ?id wdt:P31 ?type }
    FILTER(?id != wd:Q4115189 && ?id != wd:Q13406268 && ?id != wd:Q15397819)
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
