SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P2139/psv:P2139 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P2139 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
