SELECT ?unit (count(?x) as ?count) WHERE {
     { ?x p:P3071/psv:P3071 [ wikibase:quantityUnit ?unit ] }
     UNION
     { ?x pqv:P3071 [ wikibase:quantityUnit ?unit ] }
} GROUP BY ?unit
ORDER BY DESC(?count)
