SELECT ?category ?categoryLabel (count(?category) as ?count) WHERE {
  ?lexeme dct:language wd:Q29401; 
          wikibase:lexicalCategory ?category;
          wikibase:lemma [].
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],as". }
}
GROUP BY ?category ?categoryLabel
ORDER BY ?count
