SELECT ?l ?lemma ?lang ?form WHERE {
  ?l a ontolex:LexicalEntry ;
       dct:language wd:Q9027 ;
       wikibase:lemma ?lemma .
  ?l ontolex:lexicalForm ?form.
  minus {?form wikibase:grammaticalFeature [].}
}
limit 10
