#defaultView:Map
SELECT ?item ?itemLabel ?itemDescription ?coord
{
	?item wdt:P31 wd:Q39715 . 
    ?item wdt:P17 wd:Q213 . 
    
	?item wdt:P625 ?coord . 
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
