select distinct (?l as ?item) (concat("[[Lexeme:", replace(str(?l), str(wd:), ""), "|", replace(str(?l), str(wd:), ""), "]]") as ?l_) ?lemma ?len {
  ?l dct:language wd:Q7737;
     wikibase:lemma ?lemma.
  filter (regex(lcase(str(?lemma)), "[б-джзй-нп-тф-щ]{5}")).
  bind (replace(lcase(str(?lemma)), ".*(?<=[^б-джзй-нп-тф-щ]
