SELECT ?item ?geo ?sitelink  WHERE {
  { ?item wdt:P31 wd:Q5 . }
  { ?item wdt:P27 wd:Q183 . } UNION { ?item wdt:P27 wd:Q39 . } UNION { ?item wdt:P27 wd:Q40 . } # oder Land der Staatsangehörigkeit: Deutschland oder Schweiz oder Österreich
  ?sitelink schema:about ?item .
  ?sitelink schema:isPartOf <https://de.wikipedia.org/> .
  OPTIONAL {?item wdt:P569 ?gebdat }  
  FILTER (!bound(?gebdat))   # nur jene OHNE gebdat
}
