# taxa where author name is Paul Graham Wilson & William Paul
SELECT ?item ?stat ?taxon_name ?article WHERE {
  ?item p:P225 ?stat . 
  ?stat ps:P225 ?taxon_name.
  ?stat pq:P405 wd:Q910302.  
  ?stat pq:P405 wd:Q19043806.
}
ORDER BY ?taxon_name ?item
