# Women artists with work in an Australian museum
# map view shows their birth place (no longer)
# the query also finds their article


SELECT DISTINCT ?female ?femaleLabel ?dob ?dod ?age ?birthplaceLabel ?id  ?sitelink WHERE {
  #SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?female wdt:P21 wd:Q6581072;         # instance of female
    wdt:P6379 ?institution.            # Has works in the collection of ?institution
  
   {?institution wdt:P131* wd:Q408.}   # institution in Oz (administrative territory)
  union
    {?institution wdt:P17 wd:408 . }   # institution in Oz (country)
  OPTIONAL { ?female wdt:P569 ?dob. }  # date of birth
  OPTIONAL { ?female wdt:P570 ?dod. }  # date of death
  bind(year(?dod)-year(?dob) as ?age ) 
  OPTIONAL {?female wdt:P19 ?birthplace.}   # defines birth place
  OPTIONAL 	{ ?sitelink schema:about ?female. ?sitelink schema:inLanguage "en" }
   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } 
  }
 ORDER BY ?femaleLabel  
 LIMIT 4000    
