# Items about female artists with/without  a Wikipedia page whose works are in SMK museum
SELECT ?artist ?artistLabel ?article  with { select distinct ?artist WHERE 
 {
   ?artist wdt:P106 ?occ.
   VALUES ?occ {wd:Q1028181 wd:Q483501  wd:Q3391743   }    # occupations (painter only)
   ?artist wdt:P31 wd:Q5.             # is human
   ?artist wdt:P27 wd:Q35.
   ?artist wdt:P21 wd:Q6581072.       # is female
   #?artist wdt:P6379 ?collection.     # collection
   #VALUES ?collection {wd:Q671384 }   # SMK museum 
      
 } } as %i where

{
  include %i
     OPTIONAL
    {?article schema:about ?artist. # and do not have an article about them
     ?article schema:isPartOf <https://da.wikipedia.org/> . # on *Danish* Wikipedia
     }
	SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],da" }
}
ORDER BY ?artistLabel ?article
