# AusLichen taxa without taxon author citations
SELECT ?item ?itemLabel ?taxon_name ?ausLichen  WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  ?item wdt:P9093 ?ausLichen.
  ?item wdt:P225 ?taxon_name.
  MINUS {?item wdt:P6507 ?citation.} 
}
ORDER BY ?taxon_name
