# AFD taxa without parents
SELECT ?item  ?itemLabel WHERE {
  ?item wdt:P6039 ?AFD_id.
  minus {?item wdt:P171 ?parent.}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } 
}
ORDER BY ?item ?itemLabel
