# Find taxon names with Queensland Biota ids
SELECT  ?item ?itemLabel  ?ATRFid WHERE {
    ?item wdt:P225 ?taxon_name.
    { ?item wdt:P6904 ?ATRFid} .

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } 
}
order by ?itemLabel
