# Index fungorum, mycobank  taxa & not ausFungi
SELECT ?item ?itemLabel ?taxon_name  WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  {?item wdt:P1391 ?IF.} UNION {?item wdt:P962 ?myco}
  ?item wdt:P225 ?taxon_name.
   MINUS {?item wdt:P9076 ?AusfungiID.}
}
ORDER BY ?taxon_name
#LIMIT 200
