#Australian paintings/drawing by institution and female creator

SELECT ?creatorLabel ?institutionLabel (COUNT(*) AS ?count) WHERE {
  {?painting wdt:P31 wd:Q3305213.}
  UNION
   {?painting wdt:P31 wd:Q11060274.}
  ?painting wdt:P170 ?creator.
  ?creator wdt:P21 wd:Q6581072.
  ?institution wdt:P131 wd:Q3224.
  ?painting wdt:P195 ?institution.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
GROUP BY ?creatorLabel ?institutionLabel
ORDER BY ?count ?creatorLabel
