SELECT ?item
WHERE {
  {
    SELECT ?item ?itemLabel
    WHERE {
      ?item wdt:P735 ?given .
      VALUES ?given {
        wd:Q3195783 # Mari (female)  
      }
      { ?item wdt:P27 ?country . }
      UNION { ?item wdt:P19/wdt:P17 ?country . }
      ?country wdt:P2936 wd:Q1321 . # Spanish
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,es". }
    }
  }
  FILTER(CONTAINS(?itemLabel, "Mari Carmen")
