PREFIX schema: <http://schema.org/>
#defaultView:Table;ImageGrid;
SELECT DISTINCT ?item ?itemLabel ?itemDescription ?article  ?image WHERE {
  ?item wdt:P31 wd:Q5.               # ist ein = Mensch
  #?item wdt:P27 wd:Q183.             # Staatsangehörgigkeit = Deutscher
  ?item wdt:P106 wd:Q19204627.       # Tätigkeit = Judoka

  ?article schema:about ?item.
  ?article schema:isPartOf <https://de.wikipedia.org/>.    # Artikel in der Deutschen

  OPTIONAL { ?item wdt:P18 ?image. }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "de". }
}
order by ?itemLabel
LIMIT 100
