SELECT ?item ?itemLabel ?st {
  ?item ^schema:about/schema:isPartOf <https://cs.wikipedia.org/>; wdt:P17 wd:Q213 .
  MINUS { ?item wdt:P31|wdt:P279 [] } .
  ?item wikibase:statements ?st .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "cs" } .
} ORDER BY ?st ?itemLabel
