SELECT ?item (COUNT(distinct ?sitelink) as ?count) WHERE { ?item wdt:P31 wd:Q5 . ?item wdt:P21 wd:Q6581072 . ?item wdt:P27 wd:Q40 . ?sitelink schema:about ?item . FILTER NOT EXISTS { ?wals schema:about ?item . ?wals schema:inLanguage "als" }  MINUS {?item  wdt:P106 wd:Q10833314} }  GROUP BY ?item ORDER BY DESC(?count)
