SELECT ?item ?itemLabel ?count WHERE {
  {
    SELECT ?item (COUNT(DISTINCT ?length) AS ?count) WHERE {
      ?item wdt:P31* wd:Q11446;
        wdt:P2043 ?length.
    }
    GROUP BY ?item
  }
  FILTER(?count > 1 )
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY DESC (?count) (?itemL)
