SELECT ?property ?propertyLabel WHERE {
  ?property wikibase:propertyType wikibase:Quantity; p:P2302/ps:P2302 wd:Q51723761 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language 'en' }
} ORDER BY ASC(xsd:integer(STRAFTER(STR(?property), 'entity/P')))
