SELECT ?item ?page ?wikilink ?sitelinks WHERE {
  ?item p:P1343 ?described .
  ?described ps:P1343 wd:Q66362718 .
  ?item wikibase:sitelinks ?sitelinks . 
  OPTIONAL { ?described pq:P304 ?page } . 
} ORDER BY xsd:integer(?page) LIMIT 1500
