SELECT ?item ?itemLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
   ?item wdt:P5008 wd:Q104665671.
       MINUS { ?item wdt:P31 wd:Q5. }
  MINUS {?item wdt:P31 wd:Q18204.}  
  MINUS {?item wdt:P31 wd:Q215380.}
  MINUS {?item wdt:P31 wd:Q868557.}
  MINUS {?item wdt:P31 wd:Q77133429.}
  MINUS {?item wdt:P31 wd:Q26895936.}
  MINUS {?item wdt:P31 wd:Q13406463.}
  MINUS {?item wdt:P31 wd:Q811979.}
  MINUS {?item wdt:P31 wd:Q13393265.}
  MINUS {?item wdt:P31 wd:Q26894053.}
  MINUS {?item wdt:P31 wd:Q2922711.}
  MINUS {?item wdt:P31 wd:Q41176.}
  MINUS {?item wdt:P31 wd:Q1980247.}
  MINUS {?item wdt:P31 wd:Q23927052.}
  MINUS {?item wdt:P31 wd:Q101352.}
  MINUS {?item wdt:P31 wd:Q16917.}
  MINUS {?item wdt:P31 wd:Q746654.}
  MINUS {?item wdt:P31 wd:Q3305213.}
  MINUS {?item wdt:P31 wd:Q1002697.}
  MINUS {?item wdt:P31 wd:Q13442814.}
  MINUS {?item wdt:P31 wd:Q5633421.}
  MINUS {?item wdt:P31 wd:Q1539532.}
  MINUS {?item wdt:P31 wd:Q12973014.}
  MINUS {?item wdt:P31 wd:Q23900202.}
  MINUS {?item wdt:P31 wd:Q40434727.}
  MINUS {?item wdt:P31 wd:Q1079023.}
  MINUS {?item wdt:P31 wd:Q216048.}
  MINUS {?item wdt:P31 wd:Q18340514.}
  MINUS {?item wdt:P31 wd:Q2813537.}
  MINUS {?item wdt:P31 wd:Q21140826.}
  MINUS {?item wdt:P31 wd:Q2659904.}
  MINUS {?item wdt:P31 wd:Q261434.}
  MINUS {?item wdt:P31 wd:Q63981919.}
  MINUS {?item wdt:P31 wd:Q93661.}
  MINUS {?item wdt:P31 wd:Q618779.}
  MINUS {?item wdt:P31 wd:Q35127.}
  MINUS {?item wdt:P31 wd:Q1130322.}
  MINUS {?item wdt:P31 wd:Q3947.}
  MINUS {?item wdt:P31 wd:Q1426710.}
  MINUS {?item wdt:P31 wd:Q2367225.}
  MINUS {?item wdt:P31 wd:Q17156793.}
  MINUS {?item wdt:P31 wd:Q13027888.}
  MINUS {?item wdt:P31 wd:Q15020890.}
  MINUS {?item wdt:P31 wd:Q15944511.}
  MINUS {?item wdt:P31 wd:Q82969709.}
  MINUS {?item wdt:P31 wd:Q54190181.}
  MINUS {?item wdt:P31 wd:Q1244442.}
  MINUS {?item wdt:P31 wd:Q19844914.}
    MINUS {?item wdt:P31 wd:Q1060829.}
    MINUS {?item wdt:P31 wd:Q39364723.}
    MINUS {?item wdt:P31 wd:Q64578911.}
    MINUS {?item wdt:P31 wd:Q1076486.}
    MINUS {?item wdt:P31 wd:Q1107656.}
    MINUS {?item wdt:P31 wd:Q11032.}
    MINUS {?item wdt:P31 wd:Q738377.}
    MINUS {?item wdt:P31 wd:Q2319498.}
    MINUS {?item wdt:P31 wd:Q1368848.}
    MINUS {?item wdt:P31 wd:Q24354.}
    MINUS {?item wdt:P31 wd:Q3469910.}
    MINUS {?item wdt:P31 wd:Q14350.}
    MINUS {?item wdt:P31 wd:Q641226.}
   MINUS {?item wdt:P31 wd:Q386208.}
   MINUS {?item wdt:P31 wd:Q17524420.}
 }
