SELECT DISTINCT ?item ?itemLabel WHERE {
  ?item wdt:P31 wd:Q5.
  ?item wdt:P2632 ?value .
  	# beroep = beeldend kunstenaar of onderliggend
  {?item (wdt:P106/wdt:P279*) wd:Q3391743.}
  UNION
  	# beroep = grafisch ontwerper of onderliggend
  {?item (wdt:P106/wdt:P279*) wd:Q627325.}
}
