#defaultView:Map
prefix tgn: <http://vocab.getty.edu/tgn/>
prefix wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>
prefix gvp: <http://vocab.getty.edu/ontology#>
prefix xl: <http://www.w3.org/2008/05/skos-xl#>

select * {
  service <http://vocab.getty.edu/sparql.json> {
    ?place skos:inScheme tgn: ; 
           dc:identifier ?tgn ;
           gvp:prefLabelGVP/xl:literalForm "Holthausen" ;
           foaf:focus [ wgs:lat ?lat ; wgs:long ?lon ] .
  }
  bind(strdt(concat("Point(", str(?lon), " ", str(?lat), ")"), geo:wktLiteral) as ?coords1) .

}
