select ?item ?wiki ?item2 ?pagename ?pagename2 where {
	?item p:P31 ?statement .
	?statement ps:P31 wd:Q17362920 .
	{ ?statement pq:P642 ?item2 . } union
	{ ?statement pq:P460 ?item2 . } union
	{ ?statement pq:P805 ?item2 . } union
	{ ?item wdt:P460 ?item2 . }

	?sitelink schema:about ?item ; schema:isPartOf ?wiki ; schema:name ?pagename .
	?sitelink2 schema:about ?item2 ; schema:isPartOf ?wiki2 ; schema:name ?pagename2 .
	filter (?wiki = ?wiki2) .
	filter (?wiki != <https://ceb.wikipedia.org/>) .
	filter (?wiki != <https://sv.wikipedia.org/>) .
	filter (?wiki != <https://zh.wikipedia.org/>) .
} order by ?wiki limit 5000
