SELECT ?item ?itemLabel (COUNT(distinct ?sitelink) as ?count)
WHERE
{
	?item wdt:P31 wd:Q5 .
	?item wdt:P27 wd:Q41 .
	?sitelink schema:about ?item .
	FILTER EXISTS { ?wen schema:about ?item . ?wen schema:inLanguage "en" }
	FILTER NOT EXISTS { ?wfr schema:about ?item . ?wfr schema:inLanguage "el" }
	SERVICE wikibase:label {
		bd:serviceParam wikibase:language "el,en" .
	}
}
GROUP BY ?item ?itemLabel 
ORDER BY DESC(?count)
