SELECT ?entity ?entityLabel ?entityDescription ?st ?sl ?ids
WHERE
{
  ?entity wdt:P1435 wd:Q811165; wdt:P131* wd:Q1715; FILTER NOT EXISTS{ ?entity wdt:P5816 wd:Q63065035; wdt:P31 wd:Q1516079; }. 
  # MINUS { ?entity wdt:   [] }
  OPTIONAL { ?entity wikibase:statements ?st ; wikibase:sitelinks ?sl ; wikibase:identifiers ?ids } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" } 
}
