SELECT ?item ?itemLabel  WHERE {
  ?item wdt:P106 ?geo. # occupation variable geo
  ?item wdt:P31 wd:Q5. # instance is human
  ?item wdt:P21 wd:Q6581072. # gender is female
    VALUES ?geo {
    wd:Q17276189 # atmospheric scientist
    wd:Q18176481 # biogeochemist
    wd:Q1113838  # climatologist
    wd:Q15142825 # crystallographer
    wd:Q16529590 # environmental scientist
    wd:Q16738642 # gemologist
    wd:Q23823874 # geobiologist
    wd:Q16335312 # geochemist
    wd:Q11699606 # geodesist
    wd:Q901402   # geographer
    wd:Q2887387  # geological engineer
    wd:Q520549   # geologist
    wd:Q53752068 # geomorphologist
    wd:Q16335117 # geophysicist
    wd:Q15623737 # glaciologist
    wd:Q35380338 # hydrogeologist
    wd:Q15864580 # hydrographer
    wd:Q3644587  # hydrologist
    wd:Q2310145  # meteorologist
    wd:Q13416354 # mineralogist
    wd:Q3546255  # oceanographer
    wd:Q16037036 # paleobiologist
    wd:Q30059961 # paleobotanist
    wd:Q51048024 # paleogeographer
    wd:Q53754694 # paleomagnetist
    wd:Q1662561  # paleontologist
    wd:Q7178961  # petroleum geologist
    wd:Q19356817 # petrologist
    wd:Q53753884 # planetary geologist
    wd:Q23778646 # sedimentologist
    wd:Q12051314 # seismologist
    wd:Q20888501 # soil scientist
    wd:Q16742175 # speleologist
    wd:Q53751363 # stratigrapher
    wd:Q7940086  # volcanologist    
}
  FILTER NOT EXISTS { ?wfr schema:about ?item . ?wfr schema:isPartOf <https://en.wikipedia.org/>.} 
} LIMIT 600
