SELECT ?item ?itemLabel ?logo_image ?itemDescription
WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?item wdt:P31 wd:Q56056731.
  OPTIONAL { ?item wdt:P154 ?logo_image. }
}
LIMIT 1000
