#List of Nankai Lines
SELECT ?line ?lineLabel ?operatorLabel ?ownerLabel ?gaugeLabel ?routeMap ?openDate ?terminus ?terminusLabel WHERE {
  ?line wdt:P31 wd:Q728937.
  ?line wdt:P137 wd:Q1188230.
  OPTIONAL {?line wdt:P137 ?operator}
  OPTIONAL {?line wdt:P127 ?owner}
  OPTIONAL {?line wdt:P1064 ?gauge}
  OPTIONAL {?line wdt:P15 ?routeMap}
  OPTIONAL {?line wdt:P1619 ?openDate}
  OPTIONAL {?line wdt:P559 ?terminus}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
ORDER BY ?gaugeLabel
