#Stations of Nankai Line not having "operator(P137) Nankai Electric Railway(Q1188230)"
SELECT ?line ?lineLabel ?station ?stationLabel WHERE {
  ?line wdt:P31 wd:Q728937.
  ?line wdt:P137 wd:Q1188230.
  ?station wdt:P81 ?line.
  ?station wdt:P31 wd:Q55488.
  MINUS { ?station wdt:P137 wd:Q1188230 . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
