SELECT ?item ?council WHERE { 
  VALUES ?cities {wd:Q1770 wd:Q4450503}
  VALUES ?cons { wd:Q192611 }
  ?council wdt:P1001 ?cities ;
           wdt:P31/wdt:P279* wd:Q11204 .
  MINUS { ?council wdt:P576 [] }
  ?statement ps:P279 wd:Q192611 ;
             pq:P642 ?council.
  ?constype p:P279 ?statement .
  ?item wdt:P31/wdt:P279* ?constype 
  MINUS { ?item wdt:P576 [] }
}
ORDER BY ?item
