SELECT DISTINCT ?item ?itemLabel ?municipalities ?position ?electoraldistrict ?edtype ?starttime ?parliametarygroup ?parliametaryterm ?fbid WHERE {
    VALUES ?municipalities { wd:Q12348369 wd:Q9022143 wd:Q2557122 wd:Q2143868 wd:Q3313478 wd:Q6905368  wd:Q7258412 wd:Q2360428 wd:Q15121208 }
    ?municipalities wdt:P1313 ?head ;
                    wdt:P194 ?legislature .
    ?member wdt:P361 ?legislature ;
    MINUS {?member wdt:P576 [] }
    MINUS { ?legislature wdt:P576 [] }
    ?node ps:P39 ?member .
    OPTIONAL { ?node pq:P4100 ?parliametarygroup }
    OPTIONAL { ?node pq:P580 ?starttime }
    OPTIONAL { ?node pq:P768 ?electoraldistrict .
      OPTIONAL { ?electoraldistrict wdt:P31 ?edtype }
    }
    OPTIONAL { ?node pq:P582 ?endtime }
    ?node ps:P39 ?position .
    ?position wdt:P31 ?positiontype .
    ?item p:P39 ?node .
    OPTIONAL { ?item wdt:P2013 ?fbid }
}
ORDER BY ?item
