#title: LGA codes should all be local government areas of Australia
# Complex constraint from [[Property talk:P10112]]
#
SELECT ?item ?itemLabel ?instance ?instanceLabel ?value
WHERE
{
	{
		SELECT DISTINCT ?item ?instance ?value {
			?item wdt:P10112 ?value .
			MINUS {
				VALUES ?classes { wd:Q1867183 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
            FILTER(STRSTARTS(?value, "LGA")).
		} LIMIT 1000
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
