#title: XXX5### codes should be [[Property:P131|located in the administrative territorial entity&#32;<small dir="ltr">(P131)</small>]]: [[d:Q3206|Western Australia <small>(Q3206)</small>]].
# Complex constraint from [[Property talk:P10112]]
#
SELECT ?item ?itemLabel ?admin ?adminLabel ?value
WHERE
{
	{
		SELECT DISTINCT ?item ?admin ?value {
			?item wdt:P10112 ?value .
			MINUS {
				?item wdt:P131|wdt:P131/wdt:P131 wd:Q3206 .
			} .
			?item wdt:P131 ?admin .
            FILTER(STRSTARTS(?value, "LGA5") || STRSTARTS(?value, "SED5") || STRSTARTS(?value, "CED5") || STRSTARTS(?value, "SAL5") ).
		} LIMIT 1000
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
