#title: XXX3### codes should be [[Property:P131|located in the administrative territorial entity&#32;<small dir="ltr">(P131)</small>]]: [[d:Q36074|Queensland <small>(Q36074)</small>]].
# Complex constraint from [[Property talk:P10112]]
#
SELECT ?item ?itemLabel ?admin ?adminLabel ?value
WHERE
{
	{
		SELECT DISTINCT ?item ?admin ?value {
			?item wdt:P10112 ?value .
			MINUS {
				?item wdt:P131|wdt:P131/wdt:P131 wd:Q36074 .
			} .
			?item wdt:P131 ?admin .
            FILTER(STRSTARTS(?value, "LGA3") || STRSTARTS(?value, "SED3") || STRSTARTS(?value, "CED3") || STRSTARTS(?value, "SAL3") ).
		} LIMIT 1000
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
