#title: value label (experimental)
# Complex constraint from [[Property talk:P10280]]
# compares label of value with label of subject per regex for language at [[Property:P10280#P1552]]: [[d:Q100883797|complex constraint value label template <small>(Q100883797)</small>]]
SELECT ?item ?lang ?l ?value ?v ?t ?check
WHERE 
{
  hint:Query hint:optimizer "None".
  wd:P10280 p:P1552 [ ps:P1552 wd:Q100883797 ; pq:P8770 ?t ]
  BIND( lang(?t) as ?lang) 
  ?item wdt:P10280 ?value .
  FILTER (?item != wd:Q65619919) .
  ?item rdfs:label ?l . FILTER(lang(?l) = ?lang) 
  ?value rdfs:label ?v . FILTER(lang(?v) = ?lang)
  BIND ( REPLACE(str(?l), "^(.+)$", str(?t)) as ?check) 
  FILTER ( !REGEX(str(?v), ?check)  )
}
LIMIT 350
