#title: values of property P10280 with most identifiers
SELECT ?item ?itemLabel ?itemDescription ?ids
WHERE
{
	?p wdt:P10280 ?item . 
    ?item wikibase:identifiers ?ids
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }      
}
ORDER BY DESC(?ids) ?item
LIMIT 100
