SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P10412 [] .
			MINUS {
				VALUES ?classes { wd:Q740464 wd:Q13442814 wd:Q1190392 wd:Q1331848 wd:Q2751586 wd:Q106899662 wd:Q2334719 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
