#title: Items with property P10445 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P10445 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
