#Target required claim report for P1040: report listing each item and value

SELECT ?item ?itemLabel ?value ?valueLabel ?target ?targetLabel ?snak
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?target ?snak
		WHERE
		{
			{
				?item p:P1040/ps:P1040 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P1040 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P1040 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			VALUES ?values { wd:Q7042855 wd:Q7927905 wd:Q23016178 wd:Q1414443 wd:Q2526255 } .
			MINUS {
				?value p:P106/ps:P106 ?values .
			} .
			OPTIONAL {
				?value p:P106/ps:P106 ?target .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
