SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P1050 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P1050 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P1050 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q12136 wd:Q796194 wd:Q2057971 wd:Q808 wd:Q1441305 wd:Q175854 wd:Q19656546 wd:Q18596079 wd:Q12131 wd:Q7189713 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
