#title:"residence" (P551) of people with property "My World@Mail.Ru ID" (P10558) statements
#defaultView:Map{"hide":["?coordinates"]}
SELECT DISTINCT ?person ?personLabel ?personDescription ?coordinates ?image ?value
WHERE 
{
  ?person wdt:P10558 ?value ; wdt:P551/wdt:P625 ?coordinates.
  hint:Query hint:optimizer "None".
  OPTIONAL { ?person wdt:P18 ?image }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
LIMIT 1000
