#title: Items with property P10571 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P10571 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
