#Target required claim report for P10664: report listing each item and value

SELECT ?item ?itemLabel ?value ?valueLabel ?snak
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?snak
		WHERE
		{
			{
				?item p:P10664/ps:P10664 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P10664 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P10664 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS { ?value p:P1476 [] } .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
