#Target required claim report for P10664: report listing each item and value

SELECT ?item ?itemLabel ?value ?valueLabel ?target ?targetLabel ?snak
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?target ?snak
		WHERE
		{
			{
				?item p:P10664/ps:P10664 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P10664 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P10664 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			VALUES ?values { wd:Q7302866 wd:Q55850593 wd:Q55850643 wd:Q6805588 } .
			MINUS {
				?value p:P31/ps:P31 ?values .
			} .
			OPTIONAL {
				?value p:P31/ps:P31 ?target .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
