#title: Items with MCCP location or collection missing identifier
# Complex constraint from [[Property talk:P10760]]
# Items that have an [[Property:P276|location&#32;<small dir="ltr">(P276)</small>]] or [[Property:P195|collection&#32;<small dir="ltr">(P195)</small>]] set to [[d:Q1053735|Munich Central Collecting Point <small>(Q1053735)</small>]], but [[Property:P10760|MCCP ID&#32;<small dir="ltr">(P10760)</small>]] is missing
SELECT DISTINCT ?item WHERE {
  { ?item p:P276/ps:P276 wd:Q1053735 } UNION
  { ?item p:P195/ps:P195 wd:Q1053735 } 
  MINUS { ?item wdt:P10760 [] } .
  }
