SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P10767 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P123, wd:P50, wd:P2093, wd:P577, wd:P1476, wd:P407, wd:P3831, wd:P921, wd:P585, wd:P3740, wd:P1001, wd:P518, wd:P5017, wd:P393, wd:P805, wd:P1706 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
