SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P1080 [] .
			MINUS {
				VALUES ?classes { wd:Q14897293 wd:Q24334685 wd:Q13002315 wd:Q21070598 wd:Q978 wd:Q14514600 wd:Q15831596 wd:Q207869 wd:Q116811429 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
