#title: Items with property P10984 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P10984 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
