SELECT ?item ?itemLabel ?value WHERE {
	?item p:P1092/psv:P1092/wikibase:quantityAmount ?value .
	FILTER( xsd:integer( ?value ) != ?value ) .
	FILTER( ?item NOT IN ( wd:Q4115189, wd:Q13406268, wd:Q15397819 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
