#title: Items with property P1108 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P1108 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
