#title: Items with property P11050 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P11050 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
