#title: Items with property P11338 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P11338 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
