SELECT ?item ?itemLabel ?value ?valueLabel ?snak ?rank ?statement
WHERE
{
  {
    SELECT ?item ?value ?result ?snak ?rank ?statement WHERE {
      {
        ?item p:P1135 ?statement .
        ?statement ps:P1135 ?value; wikibase:rank ?rank .
        BIND("mainsnak" AS ?snak) .
      } UNION {
        ?statement pq:P1135 ?value; wikibase:rank ?rank .
        ?item ?p1 ?statement .
        BIND("qualifier" AS ?snak) .
      } UNION {
        ?ref pr:P1135 ?value .
        ?statement prov:wasDerivedFrom ?ref; wikibase:rank ?rank .
        ?item ?p2 ?statement .
        BIND("reference" AS ?snak) .
      } .
      FILTER( ?value NOT IN ( wd:Q941227, wd:Q15708833, wd:Q17276482, wd:Q15149791, wd:Q15708837, wd:Q1093954, wd:Q901847, wd:Q15709300, wd:Q51165361, wd:Q51165454, wd:Q922448, wd:Q23038368, wd:Q30349290, wd:Q68455470, wd:Q70573632, wd:Q7882332, wd:Q844326, wd:Q29995613 ) ) .
    } LIMIT 100
  } .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
