SELECT ?item ?itemLabel ?should_link_via_P466_to ?should_link_via_P466_toLabel 
WHERE
{
	?should_link_via_P466_to wdt:P115 ?item .
	FILTER NOT EXISTS { ?item wdt:P466 ?should_link_via_P466_to } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
