#title: Check important persons # 3
# Complex constraint from [[Property talk:P119]]
#
SELECT DISTINCT ?item {
  ?item wdt:P119/wdt:P31/wdt:P279* wd:Q162875;
        wdt:P31 wd:Q5.
  MINUS { ?item p:P53 [] } # 527
  #MINUS { ?item p:P106 ?b } # 87 ; bien pratique :/
  MINUS { ?item wdt:P22/wdt:P39 ?functionFather } # 57
  MINUS { ?item p:P1442 ?b } # 52, bien pratique
  MINUS { ?item wdt:P22/wdt:P119/wdt:P31 wd:Q162875 } # 43, exclude Q541665   ** duplicate code: Q162875 **
  MINUS { ?item wdt:P26/wdt:P39 ?functionConjoint } # 29, exclude Q33673045
  MINUS { ?item wdt:P40/wdt:P39 ?functionChild } # exclude : "mother of Jiajing Emperor" (Q8254570)
  MINUS {
    VALUES ?columbarium { wd:Q3006253 wd:Q17364144 wd:Q10918978 wd:Q3893448 wd:Q994694 wd:Q7231495 wd:Q46700479 }. # Q10918978: tombe de lui meme
    ?item wdt:P119 ?columbarium.
  }
  MINUS { ?item wdt:P22/wdt:P97 wd:Q273613 }
  MINUS { ?item wdt:P39/wdt:P279* wd:Q116 } # monarque
  MINUS { ?item wdt:P39/wdt:P279* wd:Q15995642 }
  MINUS {
    VALUES ?occupations { wd:Q23833535 wd:Q372436 wd:Q131524 wd:Q2095549 wd:Q49757 }
    ?item wdt:P106 ?occupations
  } # occupation:
  MINUS { ?item wdt:P39 wd:Q3409212 }
  MINUS { ?item wdt:P97 [] }
  FILTER (?item NOT IN (wd:Q6111001, wd:Q991533, wd:Q29173739, wd:Q64091692, wd:Q1441740))
  #?item wdt:P106 []. # occupation
  MINUS { ?item wdt:P1411 ?nommePour } # exclude Q329254
  MINUS { ?item wdt:P39 wd:Q175240 }
  #MINUS { ?item wdt:P39 ?fonction } # -4
  MINUS { ?item wdt:P802 [] } # eleve
  MINUS { ?item wdt:P509 wd:Q81672 }
  MINUS { ?item wdt:P106 wd:Q3242115 }
  MINUS { ?item wdt:P19 wd:Q8356 }
  MINUS { ?item wdt:P20 wd:Q8356 }
  #MINUS { ?item wdt:P410 wd:Q83460 }
  MINUS { ?item wdt:P410 [] } # grade militaire
  MINUS { ?item wdt:P800 [] } # oeuvre notable
  MINUS { ?item wdt:P2002 [] } # TODO: count followers of Q494996
  MINUS { ?item wdt:P119 wd:Q5574219 }
  MINUS { ?item wdt:P106 wd:Q43845 }
  MINUS { ?item wdt:P119/wdt:P825 ?item }
  MINUS { ?item wdt:P119/wdt:P2025 [] }
  MINUS { ?item wdt:P509 [] } # quick
  MINUS { ?item wdt:P1196 [] } # quick
  MINUS { ?item wdt:P140 [] } # quick
  MINUS { ?item wdt:P39/wdt:P31 wd:Q294414 }
  MINUS { ?item wdt:P39 wd:Q7636765 }
  MINUS { ?item wdt:P27 wd:Q156418 }
  #MINUS { ?item p:P535 ?c } # 40, exclude Q64091692
  ?item wdt:P535 ?c. # find A grave id
  MINUS { ?item wdt:P166/wdt:P31 wd:Q1046088 }
  MINUS { ?item wdt:P734 wd:Q669368 }
  MINUS { ?item wdt:P166 wd:Q1313340 }
}
