#title: values of property P1204 with most sitelinks
SELECT ?item ?itemLabel ?itemDescription ?sls
WHERE
{
	?p wdt:P1204 ?item . 
    ?item wikibase:sitelinks ?sls 
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }      
}
ORDER BY DESC(?sls) ?item
LIMIT 100
