#title: Items with property P1316 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P1316 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
