#title: Check for country code
# Complex constraint from [[Property talk:P1329]]
# entries should start with "+" and the country code (+1 for US numbers)
SELECT ?item ?itemLabel ?value ?cc
{
	?item wdt:P1329 ?value .
  	?item wdt:P17/wdt:P474 ?cc
	FILTER(!strstarts(?value, ?cc))          
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en"  }    
}
LIMIT 1000
