#title: Items with property P1336 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P1336 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
