SELECT ?item ?itemLabel ?class ?classLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?class {
			?item wdt:P1330 [] .
			MINUS {
				VALUES ?classes { wd:Q34379 wd:Q1254773 wd:Q2088357 } .
				?item wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P279 ?class .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
