SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P137 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P137 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P137 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q43229 wd:Q14623646 wd:Q5 wd:Q16334295 wd:Q95074 wd:Q12737077 wd:Q170584 wd:Q215627 wd:Q56061 wd:Q15911314 wd:Q18325841 wd:Q390516 wd:Q39614 wd:Q16970 wd:Q6881511 wd:Q1248784 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
