SELECT ?item ?itemLabel ?value ?valueLabel ?snak ?rank ?statement
WHERE
{
  {
    SELECT ?item ?value ?result ?snak ?rank ?statement WHERE {
      {
        ?item p:P1387 ?statement .
        ?statement ps:P1387 ?value; wikibase:rank ?rank .
        BIND("mainsnak" AS ?snak) .
      } UNION {
        ?statement pq:P1387 ?value; wikibase:rank ?rank .
        ?item ?p1 ?statement .
        BIND("qualifier" AS ?snak) .
      } UNION {
        ?ref pr:P1387 ?value .
        ?statement prov:wasDerivedFrom ?ref; wikibase:rank ?rank .
        ?item ?p2 ?statement .
        BIND("reference" AS ?snak) .
      } .
      FILTER( ?value NOT IN ( wd:Q1129409, wd:Q164597, wd:Q737014, wd:Q6587194, wd:Q844072, wd:Q76074, wd:Q204481, wd:Q23018230, wd:Q3289782, wd:Q1030814, wd:Q15141601, wd:Q114876382 ) ) .
    } LIMIT 100
  } .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
