#title: Check start date qualifier
# Complex constraint from [[Property talk:P138]]
#
SELECT ?item {
  ?item p:P138 [ps:P138 ?named;
                pq:P580 ?starttime;
               ].
  ?named wdt:P569 ?born.
  FILTER (?starttime < ?born).
}
