SELECT ?item ?itemLabel ?should_link_via_P1423_to ?should_link_via_P1423_toLabel 
WHERE
{
	?should_link_via_P1423_to wdt:P1424 ?item .
	FILTER NOT EXISTS { ?item wdt:P1423 ?should_link_via_P1423_to } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
