SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P1427 [] .
			MINUS {
				VALUES ?classes { wd:Q1190554 wd:Q40218 wd:Q42889 wd:Q21211206 wd:Q3099911 wd:Q337912 wd:Q1322323 wd:Q14136353 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
