SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P144 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P144 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P144 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q386724 wd:Q34770 wd:Q8192 wd:Q65943 wd:Q16686448 wd:Q95107111 wd:Q3695082 wd:Q24334685 wd:Q384748 wd:Q11410 wd:Q483394 wd:Q17737 wd:Q10541491 wd:Q13002315 wd:Q21070568 wd:Q980357 wd:Q31629 wd:Q53996674 wd:Q2085518 wd:Q17537576 wd:Q17489659 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
