#title: Items with property P1541 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P1541 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
