SELECT ?item ?itemLabel ?value ?valueLabel ?class ?classLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?class ?snak {
			{
				?item wdt:P1576 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P1576 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P1576 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q1914636 wd:Q3769299 wd:Q5410500 wd:Q2515887 wd:Q117850 wd:Q264965 wd:Q188976 } .			
				?value wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P279 ?class .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
