SELECT ?item ?itemLabel ?should_link_via_P1672_to ?should_link_via_P1672_toLabel 
WHERE
{
	?should_link_via_P1672_to wdt:P1582 ?item .
	FILTER NOT EXISTS { ?item wdt:P1672 ?should_link_via_P1672_to } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
