SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P161 [] .
			VALUES ?value { wd:Q4167410 wd:Q4167836 wd:Q14204246 wd:Q11266439 wd:Q13406463 wd:Q202866 wd:Q581714 wd:Q56884562 wd:Q29168811 wd:Q17517379 wd:Q1371849 wd:Q5 wd:Q20650540 wd:Q29982285 wd:Q98807719 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
