SELECT ?item ?itemLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?value {
			?item p:P1639/ps:P1639 ?value .
			MINUS { 
				?value p:P1639/ps:P1639 ?item .
			} .
		}
		LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
