SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P166 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P166 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P166 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q618779 wd:Q2003221 wd:Q38033430 wd:Q131647 wd:Q193622 wd:Q60754876 wd:Q7810129 wd:Q4164871 wd:Q2658935 wd:Q1046088 wd:Q3001412 wd:Q3320743 wd:Q657438 wd:Q841654 wd:Q1788716 wd:Q11448906 wd:Q378427 wd:Q4504495 wd:Q7302601 wd:Q16249975 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
