SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P1685 [] .
			VALUES ?value { wd:Q6581072 wd:Q43445 } .
			?item wdt:P21 ?value .
			BIND( wd:P21 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
