SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P1733 [] .
			MINUS {
				VALUES ?classes { wd:Q7889 wd:Q166142 wd:Q209163 wd:Q16070115 wd:Q11424 wd:Q24862 wd:Q5398426 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
