SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P179 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P179 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P179 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q7725310 wd:Q15275719 wd:Q11578774 wd:Q16858238 wd:Q17518557 wd:Q811701 wd:Q63183159 wd:Q3511132 wd:Q133250 wd:Q20937557 wd:Q43229 wd:Q27968055 wd:Q57305 wd:Q10929058 wd:Q431289 wd:Q34442 wd:Q20655472 wd:Q1978454 wd:Q5398426 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
