SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P179 [] .
			MINUS {
				VALUES ?classes { wd:Q386724 wd:Q27968055 wd:Q811704 wd:Q15900616 wd:Q42889 wd:Q1238720 wd:Q853614 wd:Q2031291 wd:Q24992028 wd:Q1656682 wd:Q1850364 wd:Q116779426 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
