SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value ?valueLabel
WHERE
{
	?item p:P179 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P1545, wd:P155, wd:P156, wd:P478, wd:P2241, wd:P7452, wd:P1013, wd:P123, wd:P1932, wd:P8338, wd:P433 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
