SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P17 [] .
			VALUES ?value { wd:Q11086742 wd:Q63952888 wd:Q102364578 wd:Q100269041 wd:Q104775758 wd:Q202866 wd:Q581714 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
