#title: Episode lists should be linked with this property
# Complex constraint from [[Property talk:P1811]]
# Find [[Property:P360|is a list of&#32;<small dir="ltr">(P360)</small>]]=episode not used as value with this property
SELECT DISTINCT ?item ?itemLabel
{
    { ?item wdt:P360 wd:Q21191270 } UNION { ?item wdt:P360 wd:Q21191270 }
	?item wdt:P31 wd:Q13406463 .
    FILTER NOT EXISTS { [] wdt:P1811 ?item }
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
