SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P186 [] .
			VALUES ?value { wd:Q56676227 wd:Q55439 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
