#title: Items with property P1871 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P1871 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
