SELECT ?item ?itemLabel ?value ?valueLabel ?snak ?rank ?statement
WHERE
{
  {
    SELECT ?item ?value ?result ?snak ?rank ?statement WHERE {
      {
        ?item p:P1884 ?statement .
        ?statement ps:P1884 ?value; wikibase:rank ?rank .
        BIND("mainsnak" AS ?snak) .
      } UNION {
        ?statement pq:P1884 ?value; wikibase:rank ?rank .
        ?item ?p1 ?statement .
        BIND("qualifier" AS ?snak) .
      } UNION {
        ?ref pr:P1884 ?value .
        ?statement prov:wasDerivedFrom ?ref; wikibase:rank ?rank .
        ?item ?p2 ?statement .
        BIND("reference" AS ?snak) .
      } .
      FILTER( ?value  IN ( wd:Q17122705, wd:Q17122834, wd:Q17122854, wd:Q17244465, wd:Q17244894, wd:Q17122740, wd:Q17245659, wd:Q17126729, wd:Q27839441, wd:Q3375649, wd:Q27777837, wd:Q17291407, wd:Q61600018, wd:Q59318252, wd:Q60172366, wd:Q42845936, wd:Q79399164, wd:Q62391724, wd:Q87067369, wd:Q59318527, wd:Q66821598, wd:Q87067389, wd:Q79401007, wd:Q78374938, wd:Q112259529, wd:Q112135905 ) ) .
    } LIMIT 100
  } .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
