#Target required claim report for P1881: report listing each item and value

SELECT ?item ?itemLabel ?value ?valueLabel ?target ?targetLabel ?snak
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?target ?snak
		WHERE
		{
			{
				?item p:P1881/ps:P1881 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P1881 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P1881 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			VALUES ?values { wd:Q95074 wd:Q15632617 wd:Q15773317 wd:Q3658341 wd:Q3966183 } .
			MINUS {
				?value p:P360/ps:P360 ?values .
			} .
			OPTIONAL {
				?value p:P360/ps:P360 ?target .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
