SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P195 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P195 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P195 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q2668072 wd:Q43229 wd:Q811979 wd:Q3707858 wd:Q334453 wd:Q8513 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
