#title: Items with property P1971 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P1971 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
