#title: Items with property P1983 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P1983 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
