# Objekte mit FSK-Altersfreigaben ohne Prüfnummer
SELECT DISTINCT ?item ?itemLabel
WHERE {
  ?item p:P1981 ?value .
  MINUS { ?value pq:P2676 ?id . }
    SERVICE wikibase:label {
     bd:serviceParam wikibase:language "de" .
     }
  }
