#title: Check qualifier
# Complex constraint from [[Property talk:P1981]]
# P2676 qualifier must meet regex "<tt>$</tt>"
SELECT ?item ?ID {
  ?item p:P1981 [ pq:P2676 ?ID ] .
  FILTER( ! REGEX(  ?ID , "^(2[3-9]\\d{4}|([1-9]\\d{0,4}|1\\d{5}|2[01]\\d{4})((-[a-d])?/(KV?|V(DVD(UMD)?)?|DVD|LD)|\\(VV\\))|)$" ) )
}
