SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P2031 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P1480, wd:P2868, wd:P642, wd:P4241, wd:P1326, wd:P1319, wd:P3629, wd:P276, wd:P106, wd:P805, wd:P5102, wd:P518, wd:P136, wd:P2241 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
