#title: Items with property P2165 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P2165 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
