SELECT ?item ?itemLabel ?should_link_via_P1269_to ?should_link_via_P1269_toLabel 
WHERE
{
	?should_link_via_P1269_to wdt:P2184 ?item .
	FILTER NOT EXISTS { ?item wdt:P1269 ?should_link_via_P1269_to } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
