embed.html#PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
#Sample query to start a list of values for property P2186
#Remove some of the "#" below to see if it helps you

SELECT ?country (SAMPLE(?countryLabel) as ?countryLabel) (count(distinct ?value) as ?count) (SAMPLE(?item) as ?example_item) (SAMPLE(?value) as ?example_value)
WHERE
{
  ?item wdt:P2186 ?value .
  OPTIONAL { ?item wdt:P17 ?country . }
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?country rdfs:label ?countryLabel .
  }
}
GROUP BY ?country
