SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P21 [] .
			VALUES ?value { wd:Q4167410 wd:Q15623926 wd:Q202444 wd:Q16334295 wd:Q571 wd:Q21286738 wd:Q215380 wd:Q2088357 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
