SELECT 
?sl ?extids
?item ?itemLabel ?itemDescription ?sex_or_genderLabel ?viaf ?isni ?date
WHERE {
  ?item wdt:P31 wd:Q5 .
  ?item p:P227 ?v .
  ?v a wdno:P227 .
 OPTIONAL {?v prov:wasDerivedFrom [ pr:P813 ?date ] .}
 OPTIONAL {?item wdt:P21 ?sex_or_gender.}
 OPTIONAL {?item wdt:P214 ?viaf.}
 OPTIONAL {?item wdt:P213 ?isni.}
 #?item wdt:P244 ?lc.
 ?item wikibase:sitelinks ?sl . #FILTER (?sl >= 1) . # only include items having X or more sitelinks
 ?item wikibase:identifiers ?extids. #FILTER (?extids >= 1) . # only include items having X or more external ids
# ?sitelink schema:isPartOf <https://de.wikipedia.org/>;
#     schema:about ?item;
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE]". }
}
#GROUP BY ?item ?data ?irisid
ORDER BY DESC(?sl) DESC(?extids) DESC(?viaf) DESC(?isni)
