#Target required claim report for P22: report listing each item and value

SELECT ?item ?itemLabel ?value ?valueLabel ?target ?targetLabel ?snak
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?target ?snak
		WHERE
		{
			{
				?item p:P22/ps:P22 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P22 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P22 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			VALUES ?values { wd:Q6581097 wd:Q44148 wd:Q2449503 wd:Q15145778 wd:Q1052281 wd:Q104717073 wd:Q69990794 } .
			MINUS {
				?value p:P21/ps:P21 ?values .
			} .
			OPTIONAL {
				?value p:P21/ps:P21 ?target .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
