#title: Validate norwegian organization numbers
# Complex constraint from [[Property talk:P2333]]
# Report organizations with incorrect organization numbers, found by validating the checksum
SELECT ?item #?itemLabel ?orgnr ?checksum ?checksum2 ?checksum3 ?quot ?rem
WITH {
  SELECT DISTINCT *
  WHERE {
    ?item wdt:P2333 ?orgnr . FILTER(strlen(?orgnr) = 9)
    BIND(xsd:integer(substr(?orgnr, 1, 1))*3 +
         xsd:integer(substr(?orgnr, 2, 1))*2 +
         xsd:integer(substr(?orgnr, 3, 1))*7 +
         xsd:integer(substr(?orgnr, 4, 1))*6 +
         xsd:integer(substr(?orgnr, 5, 1))*5 +
         xsd:integer(substr(?orgnr, 6, 1))*4 +
         xsd:integer(substr(?orgnr, 7, 1))*3 +
         xsd:integer(substr(?orgnr, 8, 1))*2 AS ?checksum)
    #BIND(floor(?checksum/11) AS ?quot)
    #BIND(?checksum - 11*?quot AS ?rem)
    BIND(11 - ?checksum + 11*floor(?checksum/11) AS ?checksum2)
    BIND(IF(?checksum2 = 11, "0", IF(?checksum2 = 10, "-", STR(?checksum2))) AS ?checksum3)
    FILTER(?checksum2 = 10 || substr(?orgnr, 9, 1) != ?checksum3)
  }
  #LIMIT 1000
} AS %i
WHERE {
  INCLUDE %i
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
}
