#title: Items with property P234 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P234 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
