# Other properties generally found on  items with P2385. 
# Limited to statements with best rank (wdt:), exceptions not filtered
# query added by Jura1, 2017-08-03

SELECT ?item ?itemLabel ?itemDescription ?value ?valueLabel
WHERE
{
	?item wdt:P2385 ?value .
	FILTER NOT EXISTS { ?item   wdt:P27 wd:Q142 }
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 1000
