#title: Items with property P2383 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P2383 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
