#title: items should have an English label (5)
# Complex constraint from [[Property talk:P244]]
#
SELECT ?item 
WITH { SELECT ?item WHERE { ?item wdt:P244 ?LCCN } OFFSET 800000 LIMIT 200000 } as %i 
WHERE { INCLUDE %i OPTIONAL { ?item rdfs:label ?l . FILTER(LANG(?l) = "en")}  FILTER(!BOUND(?l)) } LIMIT 1000
