SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P245 [] .
			MINUS {
				VALUES ?classes { wd:Q215627 wd:Q43229 wd:Q16334295 wd:Q811979 wd:Q164950 wd:Q2221906 wd:Q106668099 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
