#title: Items with property P2505 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P2505 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
