SELECT ?item ?itemLabel ?should_link_via_P144_to ?should_link_via_P144_toLabel 
WHERE
{
	?should_link_via_P144_to wdt:P2512 ?item .
	FILTER NOT EXISTS { ?item wdt:P144 ?should_link_via_P144_to } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
