#Target required claim report for P2517: report listing each item and value

SELECT ?item ?itemLabel ?value ?valueLabel ?target ?targetLabel ?snak
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?target ?snak
		WHERE
		{
			{
				?item p:P2517/ps:P2517 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P2517 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P2517 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			VALUES ?values { wd:Q21096945 } .
			MINUS {
				?value p:P971/ps:P971 ?values .
			} .
			OPTIONAL {
				?value p:P971/ps:P971 ?target .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
