SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P2566 [] .
			MINUS {
				VALUES ?classes { wd:Q11173 wd:Q169336 wd:Q11344 wd:Q79529 wd:Q81163 wd:Q2393187 wd:Q56256086 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
