SELECT ?item ?unit ?exception
WHERE
{
	{
      SELECT ?item ?unit
      WHERE
      {
        ?item      p:P2630              ?stmnode.
        ?stmnode   psv:P2630            ?valuenode.
        ?valuenode wikibase:quantityUnit   ?unit.
      }
    }.
    OPTIONAL {
		wd:P2630 p:P2302 [ ps:P2302 wd:Q21514353; pq:P2303 ?exc ] .
		FILTER( ?exc = ?item ) .
	} .
	BIND( BOUND( ?exc ) AS ?exception ) .
}
