#title: Items with property P2685 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P2685 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
