#title: Invalid NACSIS-CAT ID
# Complex constraint from [[Property talk:P271]]
# NACSIS-CAT ID that have wrong checksum (see https://catdoc.nii.ac.jp/MAN2/CM/furoku2_1.html)
SELECT ?item ?value
  {       { ?item      wdt:P271          ?value
          }
    UNION { ?statement pq:P271             ?value
          . ?item      ?p                  ?statement
          . ?prop      wikibase:claim      ?p
          }
    UNION { ?ref       pr:P271             ?value
          . ?statement prov:wasDerivedFrom ?ref
          . ?item      ?p                  ?statement
          . ?prop      wikibase:claim      ?p
          }
  . FILTER( STRLEN(?value) = 10 )
  . BIND(xsd:string(STRLEN(STRBEFORE("0123456789@ABCDEFGHIJKLMNOPQRSTUVWXYZ", SUBSTR(?value, 1 , 1 )))) AS ?digit1)
  . BIND(xsd:string(STRLEN(STRBEFORE("0123456789@ABCDEFGHIJKLMNOPQRSTUVWXYZ", SUBSTR(?value, 2 , 1 )))) AS ?digit2)
  . BIND(
      xsd:integer(SUBSTR(?digit1, STRLEN(?digit1), 1)) * 9 +
      xsd:integer(SUBSTR(?digit2, STRLEN(?digit2), 1)) * 8 +
      xsd:integer(SUBSTR(?value,  3, 1)) * 7 +
      xsd:integer(SUBSTR(?value,  4, 1)) * 6 +
      xsd:integer(SUBSTR(?value,  5, 1)) * 5 +
      xsd:integer(SUBSTR(?value,  6, 1)) * 4 +
      xsd:integer(SUBSTR(?value,  7, 1)) * 3 +
      xsd:integer(SUBSTR(?value,  8, 1)) * 2 +
      xsd:integer(SUBSTR(?value,  9, 1)) -
      xsd:integer(REPLACE(SUBSTR(?value, 10, 1), "X", "10")) AS ?checksum )
  . FILTER( FLOOR(?checksum / 11) != (?checksum / 11) )
  }
  ORDER BY ?value
