#title: Items with property P2729 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P2729 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
