SELECT ?wiki (COUNT( DISTINCT ?item ) as ?count) (SAMPLE(?item) as ?sample)
{
	?item wdt:P2772 [ ] . 
    [] schema:about ?item ; schema:isPartOf ?wiki . 
}
GROUP BY ?wiki 
ORDER BY DESC(?count) ?wiki
