#title: Check postal codes in the Philippines
# Complex constraint from [[Property talk:P281]]
#
SELECT DISTINCT ?item ?zipCode
WHERE {
  ?item wdt:P17 wd:Q928; wdt:P281 ?zipCode .
  FILTER(REGEX(STR(?zipCode), "^\\d{4}(–\\d{4})?$") = false)
}
ORDER BY ?item
