#title: Check postal codes in New Zealand
# Complex constraint from [[Property talk:P281]]
#
SELECT DISTINCT ?item ?zipCode WHERE { ?item wdt:P17 wd:Q664; wdt:P281 ?zipCode. FILTER( REGEX( STR( ?zipCode ), "^((0[1-9]|1\\d|2[0-6]|[34]\\d|5[0123578]|6[01249]|7\\d|8[01245689]|9[02345678])\\d{2})$" ) = false ) . } ORDER BY ?item
