#title: Items with property P2927 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P2927 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
