#title: Items with property P3024 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P3024 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
