SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value ?valueLabel
WHERE
{
	?item p:P3025 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P3027, wd:P3028, wd:P8626, wd:P8627, wd:P3026, wd:P1264, wd:P5102, wd:P1001, wd:P518, wd:P2360, wd:P10818 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
