SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P3080 [] .
			MINUS {
				VALUES ?classes { wd:Q7889 wd:Q160738 wd:Q734698 wd:Q209163 wd:Q1066707 wd:Q416 wd:Q904997 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
