#title: Without participation (P1344)
# Complex constraint from [[Property talk:P3171]]
# Item with a [[Property:P3171|Olympic.org athlete ID (archived)&#32;<small dir="ltr">(P3171)</small>]] identifier should have a [[Property:P1344|participant in&#32;<small dir="ltr">(P1344)</small>]] claim for their Olympic participation
SELECT DISTINCT ?item WHERE { ?item wdt:P3171 ?id . MINUS { ?item wdt:P1344 [] } } ORDER BY ASC(xsd:integer(STRAFTER(STR(?item), 'Q')))
