#title: Human without occupation (P106)
# Complex constraint from [[Property talk:P3171]]
# Human items with an [[Property:P3171|Olympic.org athlete ID (archived)&#32;<small dir="ltr">(P3171)</small>]] identifier should have a [[Property:P106|occupation&#32;<small dir="ltr">(P106)</small>]] claim
SELECT DISTINCT ?item WHERE { ?item wdt:P3171 ?id; wdt:P31 wd:Q5 . MINUS { ?item wdt:P106 [] } } ORDER BY ASC(xsd:integer(STRAFTER(STR(?item), 'Q')))
