SELECT ?item ?itemLabel ?value ?valueLabel ?snak ?rank ?statement
WHERE
{
  {
    SELECT ?item ?value ?result ?snak ?rank ?statement WHERE {
      {
        ?item p:P31 ?statement .
        ?statement ps:P31 ?value; wikibase:rank ?rank .
        BIND("mainsnak" AS ?snak) .
      } UNION {
        ?statement pq:P31 ?value; wikibase:rank ?rank .
        ?item ?p1 ?statement .
        BIND("qualifier" AS ?snak) .
      } UNION {
        ?ref pr:P31 ?value .
        ?statement prov:wasDerivedFrom ?ref; wikibase:rank ?rank .
        ?item ?p2 ?statement .
        BIND("reference" AS ?snak) .
      } .
      FILTER( ?value  IN ( wd:Q624669 ) ) .
    } LIMIT 100
  } .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
