SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P3225 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P580, wd:P582, wd:P518, wd:P1810, wd:P159, wd:P6375, wd:P2241, wd:P7452, wd:P1814, wd:P6427, wd:P1534, wd:P1366, wd:P1365, wd:P4070 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
