#Target required claim report for P3275: report listing each item and value

SELECT ?item ?itemLabel ?value ?valueLabel ?target ?targetLabel ?snak
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?target ?snak
		WHERE
		{
			{
				?item p:P3275/ps:P3275 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P3275 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P3275 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			VALUES ?values { wd:Q5762300 wd:Q483501 wd:Q20002503 wd:Q644687 wd:Q1062952 wd:Q28107590 wd:Q266569 wd:Q28122926 } .
			MINUS {
				?value p:P106/ps:P106 ?values .
			} .
			OPTIONAL {
				?value p:P106/ps:P106 ?target .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
