#title:"place of death" (P20) of people with property "ChessTempo.com player ID" (P3315) statements
#defaultView:Map{"hide":["?coordinates"]}
SELECT DISTINCT ?person ?personLabel ?personDescription ?coordinates ?image ?value
WHERE 
{
  ?person wdt:P3315 ?value ; wdt:P20/wdt:P625 ?coordinates.
  hint:Query hint:optimizer "None".
  OPTIONAL { ?person wdt:P18 ?image }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
LIMIT 1000
