SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value ?valueLabel
WHERE
{
	?item p:P3342 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P3831, wd:P580, wd:P582, wd:P1264, wd:P1319, wd:P1326, wd:P585, wd:P2868, wd:P2241, wd:P7452, wd:P8554, wd:P8555, wd:P463, wd:P10663, wd:P1545, wd:P3629, wd:P1480, wd:P1343, wd:P805, wd:P3680, wd:P1310, wd:P7528, wd:P1534, wd:P828 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
