#title: Items with property P3352 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P3352 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
