#title: Items with property P3511 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P3511 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
