SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P3575 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P400, wd:P750, wd:P585, wd:P2701, wd:P2241, wd:P7452, wd:P291, wd:P348, wd:P5102, wd:P642, wd:P1480, wd:P437, wd:P518 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
