#title: 20th-century artists without nationality
# Complex constraint from [[Property talk:P3782]]
# People with [[Property:P3782|Artnet artist ID&#32;<small dir="ltr">(P3782)</small>]] born after 1900, but no [[Property:P27|country of citizenship&#32;<small dir="ltr">(P27)</small>]]
SELECT DISTINCT ?item WHERE {
  ?item wdt:P3782 [] .
  ?item p:P569 ?birthclaim .
  MINUS { ?item p:P27 [] }
  ?birthclaim ps:P569 ?birth .
  FILTER(?birth > "+1900-00-00T00:00:00Z"^^xsd:dateTime) .
}  ORDER BY ?birth LIMIT 1000
