SELECT ?item ?itemLabel ?should_link_via_P3781_to ?should_link_via_P3781_toLabel 
WHERE
{
	?should_link_via_P3781_to wdt:P3780 ?item .
	FILTER NOT EXISTS { ?item wdt:P3781 ?should_link_via_P3781_to } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
