SELECT ?item ?itemLabel ?should_link_via_P3780_to ?should_link_via_P3780_toLabel 
WHERE
{
	?should_link_via_P3780_to wdt:P3781 ?item .
	FILTER NOT EXISTS { ?item wdt:P3780 ?should_link_via_P3780_to } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
