#title: Items with property P3846 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P3846 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
