SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P3878 [] .
			VALUES ?value { wd:Q11059 wd:Q58635 } .
			?item wdt:P407 ?value .
			BIND( wd:P407 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
