SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P400 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P400 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P400 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q241317 wd:Q60644919 wd:Q6368 wd:Q1406 wd:Q14116 wd:Q13522376 wd:Q388 wd:Q170434 wd:Q600659 wd:Q26884850 wd:Q8076 wd:Q48493 wd:Q9135 wd:Q205020 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
