SELECT ?item ?itemLabel ?value ?valueLabel ?snak ?rank ?statement
WHERE
{
  {
    SELECT ?item ?value ?result ?snak ?rank ?statement WHERE {
      {
        ?item p:P400 ?statement .
        ?statement ps:P400 ?value; wikibase:rank ?rank .
        BIND("mainsnak" AS ?snak) .
      } UNION {
        ?statement pq:P400 ?value; wikibase:rank ?rank .
        ?item ?p1 ?statement .
        BIND("qualifier" AS ?snak) .
      } UNION {
        ?ref pr:P400 ?value .
        ?statement prov:wasDerivedFrom ?ref; wikibase:rank ?rank .
        ?item ?p2 ?statement .
        BIND("reference" AS ?snak) .
      } .
      FILTER( ?value  IN ( wd:Q60309635, wd:Q28133964, wd:Q15614041, wd:Q64487188, wd:Q99582374, wd:Q64658267, wd:Q15304599, wd:Q99447158, wd:Q62513347, wd:Q99740231, wd:Q29578331, wd:Q17492436, wd:Q96379060, wd:Q30943865, wd:Q1102629, wd:Q85632250 ) ) .
    } LIMIT 100
  } .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
