SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P40 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P40 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P40 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q5 wd:Q95074 wd:Q4271324 wd:Q729 wd:Q178885 wd:Q24334299 wd:Q21070598 wd:Q16979650 wd:Q21070568 wd:Q13002315 wd:Q207174 wd:Q2135501 wd:Q21191150 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
