#title: Items with property P4209 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P4209 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
