#title: Check item with `pe` prefix
# Complex constraint from [[Property talk:P4293]]
#
SELECT ?item ?value {
	?item wdt:P4293 ?value.
  BIND (SUBSTR(?value, 1, 2) AS ?prefix).
  FILTER (?prefix IN ("pe")).
  FILTER NOT EXISTS {
    ?item wdt:P31 wd:Q5.
  }
  FILTER NOT EXISTS {
    ?item wdt:P214 ?viaf.
  }
  FILTER NOT EXISTS {
    ?item wdt:P227 ?Normdatei.
  }
  FILTER NOT EXISTS {
    ?item wdt:P31/wdt:P279* wd:Q8436.
  }
}
