SELECT ?item ?itemLabel ?value ?result (STRLEN(STR(?value)) AS ?stringlength)  ?snak ?rank
WHERE
{
	{
		SELECT ?item ?value ?result ?snak ?rank
		WHERE
		{
			{
				?item p:P4297 [ ps:P4297 ?value; wikibase:rank ?rank ] .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement1 pq:P4297 ?value;
					wikibase:rank ?rank .
				?item ?p1 ?statement1 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P4297 ?value .
				?statement2 prov:wasDerivedFrom ?ref;
					wikibase:rank ?rank .
				?item ?p2 ?statement2 .
				BIND("reference" AS ?snak) .
			} .
			BIND( REGEX( STR( ?value ), "^(([1-3][0-9])([0-2][0-6])(0[1256]|1[015]|2[05]|3[056]|4[0567]|5[0-4]|60|99)([0-5]|9)([0-7]|9)(00|1[1-9]|2([1-6]|9)|3([1-7]|9)|[4-6][129]|99)([0-9]{10})([0-9]{10})?)$" ) AS ?regexresult ) .
			FILTER( ?regexresult = false ) .
			BIND( IF( ?regexresult = true, "pass", "fail" ) AS ?result ) .
			FILTER( ?item NOT IN ( wd:Q4115189, wd:Q13406268, wd:Q15397819 ) ) .
		} 
		LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
#ORDER BY ?rank ?snak ?value
#PLEASE NOTE: This is experimental and may only work for simple patterns.
#Tests may fail due to:
#(1) differences in regex format between SPARQL (https://www.w3.org/TR/xpath-functions/#regex-syntax) and PCRE (used by constraint reports). Don't change the regex to work with SPARQL!
#(2) some bug in the link that brought you here
#Known to fail: P227 (multiple curly braces), P274, P281
