#title: Items with property P4352 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P4352 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
