SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P437 [] .
			MINUS {
				VALUES ?classes { wd:Q386724 wd:Q42848 wd:Q11424 wd:Q82014556 wd:Q2031291 wd:Q7725310 wd:Q17489659 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
