SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P437 [] .
			VALUES ?value { wd:Q4830453 wd:Q6881511 wd:Q43229 wd:Q11371 wd:Q891723 wd:Q1266169 wd:Q1941618 wd:Q93429702 wd:Q22687 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
