SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P444 [] .
			MINUS {
				VALUES ?classes { wd:Q386724 wd:Q43229 wd:Q17350442 wd:Q783794 wd:Q618779 wd:Q2424752 wd:Q17334923 wd:Q116779426 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
