#title: Items with property P4463 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P4463 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
