#title: Strict value for International Congress of Distinguished Awards
# Complex constraint from [[Property talk:P447]]
# Value for [[d:Q58890465|International Congress of Distinguished Awards <small>(Q58890465)</small>]], source: http://www.icda.org/directoryofawards/icdaprestigerating.html
SELECT ?item ?value {
  ?item p:P444 [pq:P447 wd:Q58890465; ps:P444 ?value].
  FILTER (?value NOT IN ("0.0", "0.5", "1.0", "2.0", "3.0", "3.2", "3.4", "3.6", "4.0", "5.0"))
}
