SELECT ?item ?itemLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?value {
			?item p:P451/ps:P451 ?value .
			MINUS { 
				?value p:P451/ps:P451 ?item .
			} .
		}
		LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
