SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P4529 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P580, wd:P407, wd:P1810, wd:P4908, wd:P1545, wd:P582 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
