#title: In the Museum without a link
# Complex constraint from [[Property talk:P4610]]
# Items that have [[Property:P195|collection&#32;<small dir="ltr">(P195)</small>]] -> [[d:Q239303|Art Institute of Chicago <small>(Q239303)</small>]], but that don't have a [[Property:P4610|ARTIC artwork ID&#32;<small dir="ltr">(P4610)</small>]] link
SELECT DISTINCT ?item ?url WHERE {
  ?item wdt:P195 wd:Q239303 .
  OPTIONAL { ?item wdt:P973 ?url } . 
  MINUS { ?item wdt:P4610 [] } .
}  LIMIT 500
