#title: Items with property P4638 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P4638 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
