#title: Items with property P4666 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P4666 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
