SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P4769 [] .
			VALUES ?value { wd:Q8274 wd:Q5398426 wd:Q559618 wd:Q196600 wd:Q21198342 wd:Q63952888 wd:Q20650540 wd:Q100269041 wd:Q220898 wd:Q1047299 wd:Q11086742 wd:Q747381 wd:Q104213567 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
