#Values used by property P4794
SELECT ?value ?valueLabel ?ct ?sampleitem ?sampleitemLabel
WHERE
{
  {
    SELECT ?value (count(*) as ?ct) (SAMPLE(?item) as ?sampleitem)
    WHERE
    {
      ?item wdt:P4794 ?value
    }
    GROUP BY ?value
    ORDER BY DESC(?ct)
    LIMIT 1000
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
ORDER BY DESC(?ct) ASC(?value)
