SELECT ?item ?itemLabel  WHERE {
  ?item wdt:P481 [] ;
        wdt:P31 wd:Q3305213 ;
        wdt:P921 [] . 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],fr" . }
  } ORDER BY ?itemLabel
