SELECT ?item ?itemLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?value {
			?item p:P4915/ps:P4915 ?value .
			MINUS { 
				?value p:P4915/ps:P4915 ?item .
			} .
		}
		LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
