#title: Works with creator missing link
# Complex constraint from [[Property talk:P4936]]
# List of works that are in [[Property:P195|collection&#32;<small dir="ltr">(P195)</small>]] [[d:Q913672|San Francisco Museum of Modern Art <small>(Q913672)</small>]] and have [[Property:P170|creator&#32;<small dir="ltr">(P170)</small>]] set, but that creator doesn't have a [[Property:P4936|SFMOMA artist ID&#32;<small dir="ltr">(P4936)</small>]] link
SELECT ?item ?creator
{
	?item wdt:P195 wd:Q913672 .
    ?item wdt:P170 ?creator .
	MINUS { ?creator wdt:P4936 [] } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en,en" }
} ORDER BY ?creatorLabel
