#title: Items with property P500 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P500 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
