#title: Items with property P5013 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P5013 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
