SELECT ?item ?itemLabel ?value
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P5020 ?value .
          MINUS { ?item rdfs:label ?label .
                 FILTER( LANG(?label)="zh"||LANG(?label)="zh-tw" ) }			
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
