SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P5030 [] .
			MINUS {
				VALUES ?classes { wd:Q21191270 wd:Q57608327 wd:Q61855877 wd:Q3464665 wd:Q106942341 wd:Q114321689 wd:Q1555508 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
