SELECT ?sl ?item ?itemLabel ?itemDescription
WHERE
{
  ?item wdt:P5039 ?value ; wikibase:sitelinks ?sl .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
ORDER BY ASC(?sl)
LIMIT 50
