#title: Items with property P5083 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P5083 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
