SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value ?valueLabel
WHERE
{
	?item p:P512 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P812, wd:P69, wd:P585, wd:P5021, wd:P166, wd:P811, wd:P1026, wd:P1352, wd:P184, wd:P1027, wd:P3323, wd:P580, wd:P2241, wd:P7452, wd:P1319, wd:P1326, wd:P1480, wd:P101, wd:P582, wd:P1534, wd:P8555, wd:P8554, wd:P4101, wd:P1552, wd:P805, wd:P6208, wd:P1932, wd:P1066 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
