#title: same language senses that are equivalent to the same item should be synonym
# Complex constraint from [[Property talk:P5137]]
# if <span class="statement"><b class="subject">sense A</b><span class="predicate">[[d:Property:P5137|item for this sense <small>(P5137)</small>]]</span><span class="object">item</span></span>, <span class="statement"><b class="subject">sense B</b><span class="predicate">[[d:Property:P5137|item for this sense <small>(P5137)</small>]]</span><span class="object">item</span></span>, and "sense A" and "sense B" are different senses but their lexemes belong to the same language, then <span class="statement"><b class="subject">sense A</b><span class="predicate">[[d:Property:P5973|synonym <small>(P5973)</small>]]</span><span class="object">sense B</span></span>.
SELECT ?senseA ?senseB WHERE { ?senseA wdt:P5137 ?item . ?senseB wdt:P5137 ?item . ?lexemeA ontolex:sense ?senseA . ?lexemeB ontolex:sense ?senseB . ?lexemeA dct:language ?lang . ?lexemeB dct:language ?lang . FILTER NOT EXISTS { ?senseA wdt:P5973 ?senseB } FILTER (?senseA != ?senseB) }
