SELECT ?item ?itemLabel ?value
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P5207 ?value .
          MINUS { ?item schema:description ?description .
                 FILTER( LANG(?description)="en" ) }			
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
