#title: Check P106
# Complex constraint from [[Property talk:P5291]]
#
SELECT ?item {
  ?item wdt:P5291 ?id.
  ?item wdt:P31 wd:Q5.
  FILTER NOT EXISTS { ?item wdt:P106/wdt:P31 wd:Q66715801 }
  FILTER NOT EXISTS { ?item wdt:P27 wd:Q142 } # France
  FILTER NOT EXISTS { ?item wdt:P106/wdt:P279* wd:Q177220 } # singer
  FILTER (?item NOT IN (wd:Q81819)) # exception
}
