SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P5327 [] .
			MINUS {
				VALUES ?classes { wd:Q15416 wd:Q24856 wd:Q7725310 wd:Q5 wd:Q11424 wd:Q431102 wd:Q21191270 wd:Q215380 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
