SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P5383 [] .
			MINUS {
				VALUES ?classes { wd:Q811979 wd:Q18577275 wd:Q2065736 wd:Q839954 wd:Q22698 wd:Q1497375 wd:Q15243209 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
