SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P53 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P53 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P53 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q13417114 wd:Q19791817 wd:Q8436 wd:Q15331236 wd:Q2240474 wd:Q24074280 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
