# Other properties generally found on  items with P5499. 
# Limited to statements with best rank (wdt:), exceptions not filtered
# query added by Jura1, 2017-08-03

SELECT ?item ?itemLabel ?itemDescription ?value ?valueLabel
WHERE
{
	?item wdt:P5499 ?value .
	FILTER NOT EXISTS { ?item   p:P136 [] }
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 1000
