SELECT ?item ?item2 (REPLACE(CONCAT('[', ?formatter, ' $1]'), '\\$1', ?selibr) AS ?url) WITH {
  SELECT * {
    ?item wdt:P5587/^wdt:P5587 ?item2 .
    FILTER( STR( ?item ) < STR( ?item2 ) ) .
  { ?item wdt:P31 wd:Q5 . } UNION { ?item2 wdt:P31 wd:Q5 . }
  }
} AS %duplicates WITH {
  SELECT * { wd:P5587 wdt:P1630 ?formatter } LIMIT 1
} AS %formatter WHERE {
  INCLUDE %duplicates .
  INCLUDE %formatter .
  ?item wdt:P5587 ?selibr .
  ?item2 wdt:P5587 ?selibr .
} ORDER BY ?selibr
