#title: Check units
# Complex constraint from [[Property talk:P5682]]
# Unit must to be a [[d:Q2394680|temperature scale <small>(Q2394680)</small>]]
SELECT ?item ?unit
WHERE {	
  ?item p:P5682/psv:P5682/wikibase:quantityUnit ?unit.
  MINUS {
    ?unit wdt:P31 wd:Q2394680.
  }
}
