SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P577 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P291, wd:P400, wd:P437, wd:P1480, wd:P4241, wd:P1013, wd:P1476, wd:P407, wd:P580, wd:P582, wd:P642, wd:P2361, wd:P1319, wd:P1326, wd:P1011, wd:P264, wd:P1932, wd:P5102, wd:P1310, wd:P3680, wd:P3831, wd:P478, wd:P1680, wd:P1552, wd:P421, wd:P805, wd:P123, wd:P629, wd:P212, wd:P750, wd:P2241, wd:P7452, wd:P1433, wd:P957, wd:P8555, wd:P8554, wd:P518, wd:P1545, wd:P393, wd:P3301, wd:P528, wd:P361, wd:P793, wd:P195, wd:P9767 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
