#title: Items with property P5797 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P5797 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
