SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value ?valueLabel
WHERE
{
	?item p:P5800 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P10663, wd:P7528, wd:P4895, wd:P5102, wd:P2210, wd:P518 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
