SELECT ?item ?itemLabel ?value ?valueLabel ?snak ?rank ?statement
WHERE
{
  {
    SELECT ?item ?value ?result ?snak ?rank ?statement WHERE {
      {
        ?item p:P588 ?statement .
        ?statement ps:P588 ?value; wikibase:rank ?rank .
        BIND("mainsnak" AS ?snak) .
      } UNION {
        ?statement pq:P588 ?value; wikibase:rank ?rank .
        ?item ?p1 ?statement .
        BIND("qualifier" AS ?snak) .
      } UNION {
        ?ref pr:P588 ?value .
        ?statement prov:wasDerivedFrom ?ref; wikibase:rank ?rank .
        ?item ?p2 ?statement .
        BIND("reference" AS ?snak) .
      } .
      FILTER( ?value NOT IN ( wd:Q29053744, wd:Q1931010, wd:Q7391292, wd:Q11435, wd:Q42962, wd:Q708, wd:Q11432, wd:Q658, wd:Q560, wd:Q6557453, wd:Q6508334, wd:Q155890, wd:Q194207, wd:Q23392, wd:Q1997, wd:Q184395, wd:Q1139370, wd:Q620361 ) ) .
    } LIMIT 100
  } .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
