SELECT ?item ?itemLabel ?should_link_via_P4791_to ?should_link_via_P4791_toLabel 
WHERE
{
	?should_link_via_P4791_to wdt:P598 ?item .
	FILTER NOT EXISTS { ?item wdt:P4791 ?should_link_via_P4791_to } .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
