#title: values of property P6112 with fewest statements
SELECT ?item ?itemLabel ?itemDescription ?sts
WHERE
{
	?p wdt:P6112 ?item . 
    ?item wikibase:statements ?sts
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }      
}
ORDER BY ASC(?sts) ?item
LIMIT 100
