SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P61 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P61 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P61 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q5 wd:Q13226383 wd:Q1378139 wd:Q550089 wd:Q6502154 wd:Q43229 wd:Q16334295 wd:Q7397 wd:Q18327510 wd:Q95074 wd:Q14514600 wd:Q1047213 wd:Q14897293 wd:Q14208553 wd:Q10855061 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
