SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P6228 ?statement .
	VALUES ?pq { pq:P1810 } .
	OPTIONAL {
		?statement ?pq ?qualif .
	} .
	FILTER( !BOUND( ?qualif ) ) .
	?prop wikibase:qualifier ?pq .
	?statement wikibase:rank ?rank; ps:P6228 ?value .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
