SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P625 [] .
			VALUES ?value { wd:Q11879590 wd:Q202444 wd:Q12308941 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
