SELECT ?item ?value WHERE
{
  ?item p:P6276/ps:P6276 ?value .
  
  FILTER( REGEX(REPLACE(STR(?value), "%20", " "), "^((https://music\\.amazon\\.in/artists/)?(B[\\dA-Z]+)/[a-z]+(-[a-z]+)*(\\?.+)?)$") )
}
