SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P6375 [] .
			MINUS {
				VALUES ?classes { wd:Q618123 wd:Q2221906 wd:Q1190554 wd:Q43229 wd:Q327333 wd:Q41298 wd:Q17537576 wd:Q2668072 wd:Q177634 wd:Q3895768 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
