#title: Items in catalog without the identifier
# Complex constraint from [[Property talk:P6489]]
# Items in catalog without the identifier property
SELECT ?item WHERE {
  ?item p:P528/pq:P972/wdt:P361 wd:Q61732105 .
  MINUS { ?item wdt:P6489 [] }
}
