#title:Count of items with P6482 by number of statements
#defaultView:AreaChart
SELECT ?st ?ct {
  {
    BIND (0 AS ?ct)
    BIND (0 AS ?st)
  }
  UNION {
    SELECT ?st (COUNT(*) as ?ct) {
      ?item wdt:P6482 ?value ; wikibase:statements ?st
    }
    GROUP BY ?st ORDER BY ?st
  }
}
