#title: National Memorial, National Historic Site or National Military Park but not listed on the National Register of Historic Places
# Complex constraint from [[Property talk:P649]]
# Items who are [[d:Q1967454|National Memorial of the United States <small>(Q1967454)</small>]] [[d:Q1258086|National Historic Site <small>(Q1258086)</small>]] or [[d:Q203676|National Battlefield <small>(Q203676)</small>]], but are not listed as [[d:Q19558910|National Register of Historic Places listed place <small>(Q19558910)</small>]] or [[d:Q20856087|NRHP district <small>(Q20856087)</small>]]
SELECT ?item WHERE { { ?item wdt:P31 wd:Q1967454 . } UNION { ?item wdt:P31 wd:Q1258086 . } UNION { ?item wdt:P31 wd:Q203676 . } MINUS { ?item wdt:P1435 wd:Q19558910 } MINUS { ?item wdt:P1435 wd:Q20856087 } }
