SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P658 [] .
			VALUES ?value { wd:Q11424 wd:Q5398426 wd:Q15416 wd:Q21191270 wd:Q7889 wd:Q63952888 wd:Q102364578 wd:Q220898 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
