#title: Items with property P6583 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P6583 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
