#title:"place of burial" (P119) of people with property "CNV-SP ID" (P6690) statements
#defaultView:Map{"hide":["?coordinates"]}
SELECT DISTINCT ?person ?personLabel ?personDescription ?coordinates ?image ?value
WHERE 
{
  ?person wdt:P6690 ?value ; wdt:P119/wdt:P625 ?coordinates.
  hint:Query hint:optimizer "None".
  OPTIONAL { ?person wdt:P18 ?image }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
LIMIT 1000
