embed.html#SELECT ?item ?itemLabel ?val ?f ?formatter_since  ?total_links ?unique_targets ?2019_link_counts_source
{
  BIND( URI("https://meta.wikimedia.org/wiki/Interwiki_map/detailed_table") as ?2019_link_counts_source)
  VALUES (?val ?total_links ?unique_targets)  
  { 
 ("commons" 19532715 6551177 )
 ("wikidata" 8997642 1668516 )
 ("toollabs" 7642048 101750 )
 ("irc" 7322031 1062 )
 ("translatewiki" 4996476 23015 )
 ("wikipedia" 4712099 385576 )
 ("c" 3871032 1424154 )
 ("wikispecies" 3462087 1887968 )
 ("tools" 1379134 734790 )
 ("freedomdefined" 1205884 59 )
 ("wmf" 1049675 4884 )
 ("luxo" 1022600 584761 )
 ("mw" 1006534 22910 )
 ("wikisource" 577425 89762 )
 ("phab" 486372 120331 )
 ("species" 481687 316807 )
 ("outreach" 361221 3771 )
 ("ticket" 332285 29086 )
 ("foundation" 322782 2204 )
 ("sulutil" 306546 182936 )
 ("wiktionary" 229066 122921 )
 ("phabricator" 191668 32807 )
 ("gerrit" 188425 5331 )
 ("bugzilla" 186991 18456 )
 ("toolforge" 110611 107191 )
 ("imdbname" 93129 62230 )
 ("wikibooks" 85554 29033 )
 ("imdbtitle" 84238 57582 )
 ("doi" 77892 56541 )
 ("wikimedia" 76146 2519 )
 ("wikivoyage" 73827 47035 )
 ("wikiquote" 70670 40675 )
 ("iarchive" 69676 55171 )
 ("bcnbio" 64810 1468 )
 ("wmpl" 61287 660 )
 ("incubator" 57016 9302 )
 ("wikinews" 48931 18815 )
 ("flickruser" 48688 9771 )
 ("wmse" 46432 797 )
 ("mail" 44826 857 )
 ("wmua" 42017 874 )
 ("wmru" 41214 1002 )
 ("rev" 39197 3074 )
 ("wikiversity" 36983 11478 )
 ("iso639-3" 36309 8361 )
 ("scores" 34415 13975 )
 ("mailarchive" 24436 2550 )
 ("wikitech" 24235 960 )
 ("testwiki" 23331 1395 )
 ("google" 22204 16346 )
 ("betawikiversity" 20746 1860 )
 ("pmid" 20190 16436 )
 ("wikilivres" 19945 9118 )
 ("mediawikiwiki" 18748 1059 )
 ("oeis" 16862 4702 )
 ("wikia" 16411 6229 )
 ("oldwikisource" 13119 3485 )
 ("wmid" 12382 278 )
 ("metawiki" 11844 1555 )
 ("betawiki" 10889 1428 )
 ("creativecommons" 9521 173 )
 ("otrs" 9517 2354 )
 ("arxiv" 8274 4712 )
 ("strategy" 7320 935 )
 ("wmania" 6938 190 )
 ("wmnl" 6399 625 )
 ("test2wiki" 6111 453 )
 ("wmuk" 6037 815 )
 ("outreachwiki" 6020 219 )
 ("wmfblog" 6008 971 )
 ("gutenberg" 5948 4068 )
 ("freenode" 5833 68 )
 ("foundationsite" 5230 76 )
 ("wm2012" 5053 496 )
 ("wikiapiary" 4993 1979 )
 ("wmbe" 4989 518 )
 ("wm2016" 4880 367 )
 ("testwikidata" 4505 321 )
 ("wm2018" 4429 200 )
 ("wmit" 4391 420 )
 ("mineralienatlas" 4380 3039 )
 ("wm2014" 4376 626 )
 ("drae" 4346 2921 )
 ("wmin" 4339 91 )
 ("ethnologue" 4323 1928 )
 ("wmee" 4259 12 )
 ("mediazilla" 4136 1390 )
 ("wm2010" 3885 403 )
 ("rfc" 3791 1570 )
 ("wm2017" 3524 296 )
 ("wikiasite" 3490 1618 )
 ("meatball" 3460 318 )
 ("wm2013" 3434 431 )
 ("choralwiki" 3336 1682 )
 ("schoolswp" 2695 2522 )
 ("wm2015" 2384 478 )
 ("metawikipedia" 2362 336 )
 ("wmbd" 2338 280 )
 ("creativecommonswiki" 2268 40 )
 ("wikilivresru" 2240 1540 )
 ("wm2009" 2191 250 )
 ("revo" 2140 1906 )
 ("viaf" 2067 1832 )
 ("tenwiki" 1901 376 )
 ("tswiki" 1878 168 )
 ("issn" 1868 538 )
 ("stats" 1767 267 )
 ("quarry" 1680 1119 )
 ("uncyclopedia" 1654 831 )
 ("wmca" 1620 215 )
 ("etherpad" 1599 697 )
 ("wmno" 1551 299 )
 ("download" 1515 147 )
 ("hdl" 1468 899 )
 ("wm2011" 1452 388 )
 ("petscan" 1391 860 )
 ("wmdeblog" 1338 110 )
 ("bibcode" 1321 1168 )
 ("vikidia" 1237 868 )
 ("wm2008" 1201 226 )
 ("usability" 1186 284 )
 ("wmdc" 1153 23 )
 ("wm2007" 1152 240 )
 ("memoryalpha" 1148 763 )
 ("wikicities" 1076 377 )
 ("wikifur" 1064 487 )
 ("pyrev" 1059 162 )
 ("sharemap" 956 267 )
 ("karlsruhe" 933 620 )
 ("wookieepedia" 910 612 )
 ("imdbcharacter" 901 735 )
 ("git" 893 886 )
 ("wm2006" 875 152 )
 ("wmat" 862 148 )
 ("wm2005" 802 116 )
 ("openstreetmap" 756 371 )
 ("otrswiki" 743 213 )
 ("wmbr" 727 392 )
 ("wikinvest" 677 343 )
 ("strategywiki" 648 336 )
 ("wmde" 638 97 )
 ("livepedia" 589 277 )
 ("wmfi" 588 217 )
 ("nara" 578 582 )
 ("citizendium" 572 395 )
 ("wikiconference" 561 89 )
 ("wmau" 548 102 )
 ("sourceforge" 523 354 )
 ("c2" 519 182 )
 ("planetmath" 474 320 )
 ("dmoz" 474 403 )
 ("donate" 462 147 )
 ("wmmx" 453 255 )
 ("centralwikia" 447 115 )
 ("semantic-mw" 446 91 )
 ("labsconsole" 442 146 )
 ("openlibrary" 437 313 )
 ("orthodoxwiki" 408 260 )
 ("svn" 396 141 )
 ("hrwiki" 389 202 )
 ("wmdk" 368 228 )
 ("nost" 345 118 )
 ("infosphere" 342 170 )
 ("botwiki" 339 61 )
 ("appropedia" 333 156 )
 ("localwiki" 329 312 )
 ("bibliowiki" 323 282 )
 ("wmrs" 300 129 )
 ("imdbcompany" 282 232 )
 ("wmnyc" 276 217 )
 ("marveldatabase" 275 156 )
 ("wmam" 268 14 )
 ("wmco" 264 216 )
 ("zum" 263 144 )
 ("wikiindex" 263 99 )
 ("quality" 259 143 )
 ("wikihow" 258 147 )
 ("comixpedia" 257 94 )
 ("wmar" 257 202 )
 ("wikipediawikipedia" 254 65 )
 ("wikiwikiweb" 248 101 )
 ("wmmk" 229 197 )
 ("dcdatabase" 227 137 )
 ("wmtr" 227 212 )
 ("wmve" 224 15 )
 ("genwiki" 219 213 )
 ("wmpt" 219 19 )
 ("wmil" 216 13 )
 ("wmhk" 214 4 )
 ("wmpa-us" 214 155 )
 ("battlestarwiki" 210 135 )
 ("wmet" 205 192 )
 ("rowiki" 194 92 )
 ("kamelo" 194 113 )
 ("rcirc" 186 19 )
 ("wmfr" 183 7 )
 ("scholar" 172 154 )
 ("unihan" 168 109 )
 ("wmch" 166 5 )
 ("brickwiki" 164 33 )
 ("wmhu" 164 25 )
 ("tmbw" 163 131 )
 ("wmza" 158 9 )
 ("securewikidc" 154 7 )
 ("dbdump" 153 12 )
 ("wikispot" 152 86 )
 ("metawikimedia" 147 103 )
 ("wowwiki" 145 97 )
 ("wmph" 137 36 )
 ("wikinfo" 135 31 )
 ("advisory" 134 130 )
 ("flickrphoto" 133 98 )
 ("policy" 133 13 )
 ("wmsk" 131 23 )
 ("wmcz" 127 21 )
 ("tfwiki" 117 87 )
 ("organicdesign" 116 73 )
 ("comune" 107 70 )
 ("finalfantasy" 104 69 )
 ("jira" 102 74 )
 ("mwod" 98 87 )
 ("aquariumwiki" 93 41 )
 ("wg" 84 39 )
 ("mozillawiki" 83 43 )
 ("slwiki" 83 45 )
 ("vlos" 82 66 )
 ("osmwiki" 82 54 )
 ("jstor" 81 54 )
 ("olpc" 80 55 )
 ("nostalgia" 74 21 )
 ("heraldik" 70 63 )
 ("wmes" 66 6 )
 ("rheinneckar" 64 36 )
 ("dict" 58 46 )
 ("enkol" 57 44 )
 ("mariowiki" 56 47 )
 ("encyc" 55 45 )
 ("ethnologuefamily" 55 48 )
 ("tvtropes" 54 24 )
 ("owasp" 54 36 )
 ("urbandict" 52 47 )
 ("devmo" 51 21 )
 ("bulba" 50 43 )
 ("jaglyphwiki" 50 49 )
 ("evowiki" 47 8 )
 ("elibre" 46 32 )
 ("foldoc" 45 21 )
 ("wmcl" 45 4 )
 ("wipipedia" 39 30 )
 ("silcode" 36 32 )
 ("usemod" 34 19 )
 ("liswiki" 33 10 )
 ("dictionary" 32 9 )
 ("ckwiss" 32 25 )
 ("dpd" 32 22 )
 ("acronym" 30 25 )
 ("tyvawiki" 30 14 )
 ("fedora" 30 27 )
 ("cache" 29 25 )
 ("wmtw" 27 1 )
 ("baden" 27 19 )
 ("atmwiki" 25 14 )
 ("wikiskripta" 25 24 )
 ("pokéwiki" 25 25 )
 ("aew" 24 19 )
 ("wmteam" 24 10 )
 ("musicbrainz" 23 14 )
 ("tviv" 23 18 )
 ("swtrain" 23 10 )
 ("freesoft" 23 15 )
 ("pythoninfo" 22 17 )
 ("senseislibrary" 22 19 )
 ("openwetware" 22 16 )
 ("twiki" 21 18 )
 ("spcom" 21 3 )
 ("rt" 21 7 )
 ("gentoo" 21 19 )
 ("googlegroups" 19 13 )
 ("ircrc" 19 6 )
 ("heroeswiki" 19 12 )
 ("jerseydatabase" 19 9 )
 ("hrfwiki" 18 11 )
 ("scoutwiki" 18 8 )
 ("guc" 18 13 )
 ("s23wiki" 17 17 )
 ("lostpedia" 17 16 )
 ("lqwiki" 15 11 )
 ("mozillazinekb" 15 10 )
 ("mosapedia" 15 13 )
 ("dcc" 15 13 )
 ("disinfopedia" 14 11 )
 ("ecoreality" 14 4 )
 ("wikicity" 14 9 )
 ("unreal" 13 7 )
 ("wikif1" 13 11 )
 ("proofwiki" 13 12 )
 ("utrs" 13 11 )
 ("iuridictum" 12 11 )
 ("gutenbergwiki" 12 9 )
 ("slashdot" 11 10 )
 ("scramble" 11 4 )
 ("wikiti" 10 6 )
 ("bluwiki" 10 6 )
 ("linguistlist" 10 10 )
 ("wikipapers" 10 4 )
 ("theopedia" 9 7 )
 ("exotica" 9 9 )
 ("esolang" 9 6 )
 ("advogato" 8 6 )
 ("moinmoin" 8 5 )
 ("emacswiki" 8 6 )
 ("dwjwiki" 8 4 )
 ("thelemapedia" 8 6 )
 ("finnix" 8 8 )
 ("wikilemon" 8 6 )
 ("werelate" 8 6 )
 ("wmcn" 8 1 )
 ("squeak" 7 5 )
 ("pmeg" 7 5 )
 ("personaltelco" 7 5 )
 ("googledefine" 7 5 )
 ("gardenology" 7 5 )
 ("stewardry" 7 6 )
 ("freebsdman" 6 4 )
 ("mozcom" 6 2 )
 ("boxrec" 6 6 )
 ("freebio" 6 5 )
 ("nosmoke" 6 6 )
 ("doom_wiki" 6 5 )
 ("rodovid" 6 5 )
 ("linuxwiki" 5 3 )
 ("phpwiki" 5 3 )
 ("pywiki" 5 2 )
 ("seattlewiki" 5 4 )
 ("wikisophia" 5 4 )
 ("guildwiki" 5 2 )
 ("communitywiki" 5 5 )
 ("wikiotics" 5 2 )
 ("englyphwiki" 5 3 )
 ("c2find" 4 3 )
 ("foxwiki" 4 2 )
 ("hammondwiki" 4 2 )
 ("jspwiki" 4 2 )
 ("pythonwiki" 4 2 )
 ("zwiki" 4 2 )
 ("jefo" 4 3 )
 ("drumcorpswiki" 4 3 )
 ("tclerswiki" 4 4 )
 ("phwiki" 4 4 )
 ("ecxei" 3 2 )
 ("tmnet" 3 2 )
 ("tmwiki" 3 2 )
 ("usej" 3 2 )
 ("seapig" 3 2 )
 ("energiewiki" 3 2 )
 ("kontuwiki" 3 3 )
 ("kinowiki" 3 3 )
 ("delicious" 3 3 )
 ("thinkwiki" 3 3 )
 ("dcma" 3 3 )
 ("freeculturewiki" 3 3 )
 ("wikimac-de" 3 2 )
 ("cellwiki" 3 2 )
 ("literateprograms" 3 3 )
 ("libreplanet" 3 2 )
 ("eĉei" 2 2 )
 ("wlug" 2 2 )
 ("infosecpedia" 2 2 )
 ("ĉej" 2 2 )
 ("linuxwikide" 2 2 )
 ("vkol" 2 2 )
 ("wikichristian" 2 2 )
 ("ganfyd" 2 2 )
 ("hupwiki" 2 2 )
 ("dreamhost" 2 2 )
 ("monstropedia" 2 2 )
 ("arborwiki" 2 2 )
 ("wmke" 2 2 )
 ("komicawiki" 2 2 )
 ("wmhi" 2 2 )
 ("eokulturcentro" 1 1 )
 ("lojban" 1 1 )
 ("opera7wiki" 1 1 )
 ("patwiki" 1 1 )
 ("gausswiki" 1 1 )
 ("chej" 1 1 )
 ("cxej" 1 1 )
 ("fanimutationwiki" 1 1 )
 ("wqy" 1 1 )
 ("rtfm" 1 1 )
 ("ourmedia" 1 1 )
 ("robowiki" 1 1 )
 ("h2wiki" 1 1 )
 ("javanet" 1 1 )
 ("javapedia" 1 1 )
 ("onelook" 1 1 )
 ("freekiwiki" 1 1 )
 ("zrhwiki" 1 1 )
 ("communityscheme" 1 1 )
 ("tabwiki" 1 1 )
 ("swinbrain" 1 1 )
 ("technorati" 1 1 )
 ("mwot" 1 1 )
 ("wurmpedia" 1 1 )
 ("freefeel" 1 1 )
 ("psycle" 1 1 )
 ("panawiki" 1 1 )
 ("floralwiki" 1 1 )
 ("nkcells" 1 1 )
 ("voipinfo" 1 1 )
 ("reuterswiki" 1 1 )
 ("dmozs" 1 1 )
 ("guildwarswiki" 1 1 )
 ("blw" 1 1 )
 ("hackerspaces" 1 1 )
 ("pokewiki" 1 1 )
 ("wmromd" 1 1 )
 ("wikimania" 0 0 )
 ("distributedproofreaders" 0 0 )
 ("distributedproofreadersca" 0 0 )
 ("beacha" 0 0 )
 ("metawikisearch" 0 0 )
 ("votewiki" 0 0 )
 ("wmec" 0 0 )
 ("horizonlabs" 0 0 )
 ("wmpunjabi" 0 0 )
 ("gucprefix" 0 0 )
 ("debian" 0 0 )
 ("ircs" 0 0 )
 ("omegawiki" 0 0 )
 ("umap" 0 0 )
 ("wmfdashboard" 0 0 )

  }
  ?item p:P6720 ?st . 
  ?st ps:P6720 ?val .
  OPTIONAL { ?st pq:P1630 ?f }
  OPTIONAL { ?st pq:P580 ?formatter_since }
  OPTIONAL { ?st pq:P582 ?end }  
  ?st a wikibase:BestRank .
  OPTIONAL { ?item wdt:P137 wd:Q180 . BIND("y" as ?wmf) }
  OPTIONAL { ?item wdt:P31 wd:Q15924535 . BIND("chapter" as ?wmf) }
  OPTIONAL { ?item wdt:P31 wd:Q483279 . BIND("mania" as ?wmf) }
  FILTER NOT EXISTS { ?item wdt:P1800 ?wmf_db }  
  FILTER ( !BOUND(?wmf) )
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}  
