embed.html#SELECT ?item ?itemLabel ?val ?f ?formatter_since  ?total_links ?unique_targets ?2019_link_counts_source
{
  BIND(URI("https://meta.wikimedia.org/wiki/Interwiki_map/detailed_table") as ?2019_link_counts_source)
VALUES (?val ?total_links ?unique_targets){ 
("appropedia" 333 156)
("arxiv" 8274 4712)
("battlestarwiki" 210 135)
("bcnbio" 64810 1468)
("bibcode" 1321 1168)
("bibliowiki" 323 282)
("botwiki" 339 61)
("c2" 519 182)
("centralwikia" 447 115)
("choralwiki" 3336 1682)
("citizendium" 572 395)
("comixpedia" 257 94)
("creativecommons" 9521 173)
("creativecommonswiki" 2268 40)
("dcdatabase" 227 137)
("dmoz" 474 403)
("doi" 77892 56541)
("donate" 462 147)
("download" 1515 147)
("drae" 4346 2921)
("ethnologue" 4323 1928)
("flickruser" 48688 9771)
("foundationsite" 5230 76)
("freedomdefined" 1205884 59)
("freenode" 5833 68)
("genwiki" 219 213)
("gutenberg" 5948 4068)
("hdl" 1468 899)
("hrwiki" 389 202)
("iarchive" 69676 55171)
("imdbcharacter" 901 735)
("imdbcompany" 282 232)
("imdbname" 93129 62230)
("imdbtitle" 84238 57582)
("infosphere" 342 170)
("irc" 7322031 1062)
("iso639-3" 36309 8361)
("issn" 1868 538)
("karlsruhe" 933 620)
("labsconsole" 442 146)
("livepedia" 589 277)
("localwiki" 329 312)
("marveldatabase" 275 156)
("meatball" 3460 318)
("memoryalpha" 1148 763)
("mineralienatlas" 4380 3039)
("nara" 578 582)
("nost" 345 118)
("oeis" 16862 4702)
("openlibrary" 437 313)
("openstreetmap" 756 371)
("orthodoxwiki" 408 260)
("otrswiki" 743 213)
("planetmath" 474 320)
("pmid" 20190 16436)
("pyrev" 1059 162)
("quality" 259 143)
("revo" 2140 1906)
("rfc" 3791 1570)
("semantic-mw" 446 91)
("sharemap" 956 267)
("sourceforge" 523 354)
("stats" 1767 267)
("strategywiki" 648 336)
("svn" 396 141)
("tswiki" 1878 168)
("uncyclopedia" 1654 831)
("viaf" 2067 1832)
("vikidia" 1237 868)
("wikia" 16411 6229)
("wikiapiary" 4993 1979)
("wikiasite" 3490 1618)
("wikiconference" 561 89)
("wikifur" 1064 487)
("wikihow" 258 147)
("wikiindex" 263 99)
("wikilivres" 19945 9118)
("wikilivresru" 2240 1540)
("wikinvest" 677 343)
("wikiwikiweb" 248 101)
("wookieepedia" 910 612)
("zum" 263 144)
}
  ?item p:P6720 ?st . 
  ?st ps:P6720 ?val .
  OPTIONAL { ?st pq:P1630 ?f }
  OPTIONAL { ?st pq:P580 ?formatter_since }
  ?st a wikibase:BestRank .

  # Main selection:
  FILTER NOT EXISTS { ?item wdt:P1687 [ ] }                 #no Wikidata property
  FILTER ( ?total_links > 500 && ?unique_targets > 300  )
  # exclude some
  FILTER( ?item not in ( wd:Q461 , wd:Q17460 , wd:Q1540899 , wd:Q300885 , wd:Q33133762 ) )

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en"}
}  
