#title: official website uses https, but formatter http
# Complex constraint from [[Property talk:P6720]]
# https is generally preferred. If the website can be accessed with https, you may want to request an update at [[m:Talk:Interwiki_map#Requests_for_updates]]. Once the interwiki table updated, add an "s" to the formatter
SELECT ?item ?iw (CONCAT("[[",?iw,":]]") as ?iwlinked) ?f ?ws
{
  ?item p:P6720 ?st . 
  ?st ps:P6720 ?iw . 
  ?st pq:P1630 ?f . 
  ?st a wikibase:BestRank .
  ?item wdt:P856 ?ws . 
  FILTER( contains ( str(?ws), "https:") )
  FILTER( CONTAINS( ?f, "http:") )
}
