#title: Items with property P673 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P673 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
