SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P6819 [] .
			MINUS {
				VALUES ?classes { wd:Q12681 wd:Q87167 wd:Q386724 wd:Q3331189 wd:Q53731850 wd:Q8201 wd:Q82772 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
