#title: Items with property P6828 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P6828 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
