#title: Items with property P6927 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P6927 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
