#Target required claim report for P6942: report listing each item and value

SELECT ?item ?itemLabel ?value ?valueLabel ?target ?targetLabel ?snak
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?target ?snak
		WHERE
		{
			{
				?item p:P6942/ps:P6942 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P6942 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P6942 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			VALUES ?values { wd:Q266569 wd:Q28122926 wd:Q28122965 } .
			MINUS {
				?value p:P106/ps:P106 ?values .
			} .
			OPTIONAL {
				?value p:P106/ps:P106 ?target .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
