#title: Items with property P6985 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P6985 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
