SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P69 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P69 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P69 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q2385804 wd:Q15690029 wd:Q23005223 wd:Q44613 wd:Q1128397 wd:Q1896682 wd:Q2023606 wd:Q180958 wd:Q16519632 wd:Q16917 wd:Q5341295 wd:Q233324 wd:Q504703 wd:Q391347 wd:Q14911880 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
