SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P6 [] .
			MINUS {
				VALUES ?classes { wd:Q1048835 wd:Q7188 wd:Q640506 wd:Q524572 wd:Q1145276 wd:Q64034456 wd:Q56061 wd:Q327333 wd:Q6866562 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
