SELECT ?item ?itemLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?value {
			?item p:P7047/ps:P7047 ?value .
			MINUS { 
				?value p:P7047/ps:P7047 ?item .
			} .
		}
		LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
