SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P710 [] .
			MINUS {
				VALUES ?classes { wd:Q1190554 wd:Q14136353 wd:Q24336466 wd:Q170584 wd:Q54933017 wd:Q124964 wd:Q321839 wd:Q4539 wd:Q3249551 wd:Q500834 wd:Q13406554 wd:Q178651 wd:Q5 wd:Q16334295 wd:Q58778 wd:Q70990126 wd:Q24634210 wd:Q93204 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
