#title: Items with property P7184 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P7184 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
