#title: Items with property P7180 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P7180 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
