SELECT ?item ?itemLabel ?property ?propertyLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?property ?value {
			?item wdt:P7212 [] .
			VALUES ?value { wd:Q2031291 wd:Q134556 wd:Q482994 wd:Q169930 wd:Q394970 wd:Q1892995 wd:Q10590726 wd:Q7366 wd:Q193977 wd:Q105543609 wd:Q2188189 wd:Q207628 wd:Q55850643 } .
			?item wdt:P31 ?value .
			BIND( wd:P31 AS ?property ) .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
