#title: Items with property P7370 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P7370 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
