SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P739 [] .
			MINUS {
				VALUES ?classes { wd:Q12796 wd:Q181947 wd:Q46311 wd:Q15720870 wd:Q728 wd:Q42889 wd:Q184613 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
