#title: Items with property P7403 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P7403 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
