#title: Items with property P7413 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P7413 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
