#title: Items with property P7607 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P7607 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
