#title: Items with property P7646 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P7646 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
