#title: Deutsche Biographie ID should be equal to GND ID
# Complex constraint from [[Property talk:P7902]]
# GND ID exists and is different from Deutsche Biographie ID. NOTE:  also lists items having more than one GND and one is equal
SELECT ?item ?dtbioid {?item wdt:P7902 ?dtbioid; wdt:P227 ?gndid.  FILTER ( ?gndid != ?dtbioid )}
