#title: Deutsche Biographie ID - type human should have given name
# Complex constraint from [[Property talk:P7902]]
# Deutsche Biographie ID exists, type is human, given name missing
SELECT ?item ?dtbioid {?item wdt:P7902 ?dtbioid; wdt:P31 wd:Q5; MINUS {?item wdt:P735 []} } LIMIT 100
