#title: Deutsche Biographie ID - item requires statement if described by NDB
# Complex constraint from [[Property talk:P7902]]
# Deutsche Biographie ID missing and described by NDB
SELECT ?item {?item wdt:P1343 wd:Q222784. MINUS {?item wdt:P7902 []} }
