SELECT ?item ?itemLabel ?value ?valueLabel ?snak ?rank ?statement
WHERE
{
  {
    SELECT ?item ?value ?result ?snak ?rank ?statement WHERE {
      {
        ?item p:P8031 ?statement .
        ?statement ps:P8031 ?value; wikibase:rank ?rank .
        BIND("mainsnak" AS ?snak) .
      } UNION {
        ?statement pq:P8031 ?value; wikibase:rank ?rank .
        ?item ?p1 ?statement .
        BIND("qualifier" AS ?snak) .
      } UNION {
        ?ref pr:P8031 ?value .
        ?statement prov:wasDerivedFrom ?ref; wikibase:rank ?rank .
        ?item ?p2 ?statement .
        BIND("reference" AS ?snak) .
      } .
      FILTER( ?value  IN ( wd:Q35535, wd:Q2159907, wd:Q18028810, wd:Q14886050, wd:Q17127659, wd:Q8473, wd:Q37726 ) ) .
    } LIMIT 100
  } .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
