SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P8069 [] .
			MINUS {
				VALUES ?classes { wd:Q5 wd:Q4271324 wd:Q3117863 wd:Q207869 wd:Q21070568 wd:Q17537576 wd:Q132241 wd:Q6313217 wd:Q6999 wd:Q7239 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
