#title: Items with property P8168 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P8168 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
