#title: Check P106
# Complex constraint from [[Property talk:P8170]]
# [[d:Q39631|physician <small>(Q39631)</small>]]
SELECT ?item {
	?item p:P8170 [].
	FILTER NOT EXISTS { ?item wdt:P106/wdt:P279* wd:Q39631 }
}
