SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P8289 [] .
			MINUS {
				VALUES ?classes { wd:Q102496 wd:Q1989839 wd:Q17143723 wd:Q12798556 wd:Q7137411 wd:Q11859145 wd:Q2638480 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
