#title: Items with property P8332 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P8332 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
