#title:"work location" (P937) of people with property "lobbywatch.ch ID of a member of the Swiss parliament" (P8474) statements
#defaultView:Map{"hide":["?coordinates"]}
SELECT DISTINCT ?person ?personLabel ?personDescription ?coordinates ?image ?value
WHERE 
{
  ?person wdt:P8474 ?value ; wdt:P937/wdt:P625 ?coordinates.
  hint:Query hint:optimizer "None".
  OPTIONAL { ?person wdt:P18 ?image }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
LIMIT 1000
