SELECT ?item ?value WHERE
{
  ?item p:P854/ps:P854 ?value .
  
  FILTER( REGEX(REPLACE(STR(?value), "%20", " "), "^(https?://(www\\.)?plus\\.google\\.com/(\\d{21}|\\+[-\\w_À-ÿА-я]+|communities/\\d{21})(/(about(\\?hl=en)?)?)?)$") )
}
