SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value ?valueLabel
WHERE
{
	?item p:P8570 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P304, wd:P7668, wd:P805, wd:P1104, wd:P1114, wd:P1476, wd:P1922, wd:P3132, wd:P7081, wd:P953, wd:P50, wd:P921 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
