SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P8604 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P1810, wd:P1352, wd:P3744, wd:P3740, wd:P5436, wd:P585, wd:P1552, wd:P580, wd:P1065, wd:P5897, wd:P2047, wd:P582, wd:P1534, wd:P10649, wd:P407, wd:P3831 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
