#title: FIX ALLCAPS
# Complex constraint from [[Property talk:P8631]]
# see [[Help:Label]]
SELECT ?item ?l WHERE { ?item wdt:P8631 []; rdfs:label ?l. FILTER( lang(?l) ="en" && REGEX(?l,"[A-Z]{3,}") )  }  LIMIT 50
