#title: Value shouldn't be the same as for "see also" (P1659)
# Complex constraint from [[Property talk:P8882]]
# TODO: correct one of the two statements
SELECT ?item ?value { ?item wdt:P8882 ?value ; wdt:P1659 ?value }
