SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value ?valueLabel
WHERE
{
	?item p:P8938 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P580, wd:P582, wd:P1706 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
