SELECT ?item ?itemLabel ?sample ?sampleLabel
WHERE	
{
	{
		SELECT ?item (COUNT(?value) AS ?count) (SAMPLE(?value) AS ?sample) {
			?item wdt:P9161 ?value .
		}
		GROUP BY ?item
		HAVING ( ?count = 1 )
	}
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
