SELECT ?item ?itemLabel ?value ?valueLabel ?instance ?instanceLabel ?snak 
WHERE
{
	{
		SELECT DISTINCT ?item ?value ?instance ?snak {
			{
				?item wdt:P92 ?value .
				BIND("mainsnak" AS ?snak) .
			} UNION {
				?statement0 pq:P92 ?value .
				?item ?p0 ?statement0 .
				BIND("qualifier" AS ?snak) .
			} UNION {
				?ref pr:P92 ?value .
				?statement1 prov:wasDerivedFrom ?ref .
				?item ?p1 ?statement1 .
				BIND("reference" AS ?snak) .
			} .
			MINUS {
				VALUES ?classes { wd:Q820655 wd:Q45736416 wd:Q4122445 wd:Q2571972 wd:Q1864008 wd:Q428148 wd:Q98491862 wd:Q694045 wd:Q3150005 wd:Q846882 } .			
				?value wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?value wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
