SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value ?valueLabel
WHERE
{
	?item p:P930 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P2283, wd:P559, wd:P518, wd:P580, wd:P582 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
