SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P9345 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P580, wd:P1552, wd:P2241, wd:P2124, wd:P407, wd:P7452, wd:P805, wd:P585, wd:P9078, wd:P582, wd:P1001, wd:P1810 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
