#title: Items with property P9426 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P9426 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
