#title: Items with property P9539 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P9539 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
