#title: values of property P9549 with most statements
SELECT ?item ?itemLabel ?itemDescription ?sts
WHERE
{
	?p wdt:P9549 ?item . 
    ?item wikibase:statements ?sts
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }      
}
ORDER BY DESC(?sts) ?item
LIMIT 100
