#title: Items with property P9550 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P9550 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
