#title: Items with property P9574 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P9574 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
