SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P968 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P3831, wd:P582, wd:P518, wd:P407, wd:P3721, wd:P642, wd:P366, wd:P813, wd:P1448, wd:P2360, wd:P1476, wd:P854, wd:P580 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
