SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P968 [] .
			MINUS {
				VALUES ?classes { wd:Q43229 wd:Q2221906 wd:Q7397 wd:Q13226383 wd:Q132241 wd:Q5 wd:Q106668099 wd:Q95074 wd:Q464980 wd:Q288514 wd:Q102345381 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
