SELECT ?item ?itemLabel ?value ?valueLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?value {
			{
				?item wdt:P972 ?value .
              	?value wdt:P31/wdt:P279* ?classes
			}  .
			VALUES ?classes { wd:Q2352616 } .
		} 
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
