SELECT ?item ?itemLabel ?instance ?instanceLabel
WHERE
{
	{
		SELECT DISTINCT ?item ?instance {
			?item wdt:P9721 [] .
			MINUS {
				VALUES ?classes { wd:Q811979 wd:Q42889 wd:Q34442 wd:Q79007 wd:Q15617994 wd:Q863404 wd:Q22698 } .
				?item wdt:P31/wdt:P279* ?classes .
			} .
			OPTIONAL {
				?item wdt:P31 ?instance .
			} .
		} LIMIT 100
	} .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
