SELECT ?item ?value WHERE
{
  ?item p:P973/ps:P973 ?value .
  
  FILTER( REGEX(REPLACE(STR(?value), "%20", " "), "^(https?://structurae\\.(info|net|de)/(structures|ouvrage|bauwerke)/([12]0\\d{6}))$") )
}
