SELECT ?item ?value WHERE
{
  ?item p:P973/ps:P973 ?value .
  
  FILTER( REGEX(REPLACE(STR(?value), "%20", " "), "^(https?://(www\\.)?hkmdb\\.com/db/movies/view\\.mhtml\\?id=(\\d{1,5})(&display_set.*)?)$") )
}
