SELECT ?item ?value WHERE
{
  ?item p:P973/ps:P973 ?value .
  
  FILTER( REGEX(REPLACE(STR(?value), "%20", " "), "^(https?://www\\.boxofficemojo\\.com/movies/\\?id=([a-z0-9][-.a-z0-9]*)\\.htm)$") )
}
