SELECT ?item ?value WHERE
{
  ?item p:P973/ps:P973 ?value .
  
  FILTER( REGEX(REPLACE(STR(?value), "%20", " "), "^(https?://www\\.errproject\\.org/jeudepaume/card_view\\.php\\?CardId\\=([1-9]\\d{2,4}))$") )
}
