#title: No localitzat a un municipi valencià
# Complex constraint from [[Property talk:P9746]]
# element amb codi CEICE però no localitzat a un municipi del País Valencià (o una subdivisió seva, o una subdivisió d'una subdivisió seva)
select ?item where {
  ?item wdt:P9746 [] .
  minus { ?item wdt:P131?/wdt:P131?/wdt:P131/wdt:P131/wdt:P131/wdt:P131 wd:Q5720 }
}
