#title: Items with property P9770 and no other statements
SELECT ?item ?itemLabel ?value {
  ?item wdt:P9770 ?value ; wikibase:statements 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
