#title: Items with statements where property P984 uses the novalue special value
SELECT ?item ?itemLabel (GROUP_CONCAT(?instanceLabel; separator=", ") as ?instanceLabels)
{
  ?item p:P984 [a wdno:P984; a wikibase:BestRank] .

  OPTIONAL {?item wdt:P31 ?instance}
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,en,ru,ja,zh" .
    ?item rdfs:label ?itemLabel .
    ?instance rdfs:label ?instanceLabel
  }
}
GROUP BY ?item ?itemLabel
LIMIT 100
