#title: Items with property P9859 and no other identifiers
SELECT ?item ?itemLabel ?value {
  ?item wdt:P9859 ?value ; wikibase:identifiers 1
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
} LIMIT 1000
