SELECT ?item ?itemLabel ?prop ?propLabel ?rank ?value 
WHERE
{
	?item p:P9976 [ ?pq ?value; wikibase:rank ?rank ] .
	?prop wikibase:qualifier ?pq .
	FILTER( ?prop NOT IN ( wd:P518, wd:P585, wd:P3831, wd:P1810 ) ) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" } .
}
LIMIT 100
