SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P27 wd:Q214; wdt:P31 wd:Q5 . 
  MINUS { ?entity wdt:P1412 []; wdt:P27 wd:Q214; wdt:P31 wd:Q5  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
