#defaultView:Map
SELECT ?item ?itemLabel ?location ?image
WHERE {
  ?item wdt:P17 wd:Q27 . 
  ?item wdt:P2186 ?wlmid .
  FILTER(STRSTARTS(?wlmid, 'IE-')) .
  ?item wdt:P625 ?location . 
  OPTIONAL { ?item wdt:P18 ?image }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
