SELECT ?item1 ?item2 ?a
{
  ?item1 wdt:P17 wd:Q414 .
  ?item2 wdt:P17 wd:Q414 .
  ?item1 wdt:P528 ?a .
  ?item2 wdt:P528 ?a .
  BIND( xsd:integer( STRAFTER( STR( ?item1 ), STR( wd:Q ) ) ) AS ?num1 ) .
  BIND( xsd:integer( STRAFTER( STR( ?item2 ), STR( wd:Q ) ) ) AS ?num2 ) .
  FILTER( ?num1 > ?num2 ) 
}
