SELECT ?item ?itemLabel
{
  ?item wdt:P971 wd:Q56465024 .
  ?item wdt:P971 _:CFC .
  _:CFC wdt:P31 wd:Q476028 .
  _:CFC wdt:P17 wd:Q229 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],el,en" }
}
