SELECT DISTINCT ?item ?itemLabel ?itemDescription ?sitelinks WHERE {  #?instanceOfLabel
  
    ?item wdt:P31 wd:Q5292 .
  # ?item wdt:P31 ?instanceOf .
  # FILTER NOT EXISTS {?item wdt:P136 wd:Q5292}
  ?item wikibase:sitelinks ?sitelinks
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } 
}
ORDER BY DESC(?sitelinks) ?itemLabel
