SELECT DISTINCT ?item ?id WHERE {
  { ?item wdt:P276/wdt:P361* wd:Q2981 ;
          wdt:P481 ?id .
  } UNION
  { ?item wdt:P361 ?group .
    ?group wdt:P276/wdt:P361* wd:Q2981 ;
           wdt:P481 ?id .
  }
}
