SELECT DISTINCT ?item ?itemLabel  WHERE 
{  
  ?item wdt:P31 wd:Q29555881 .
  ?item wdt:P179 wd:Q83279 .
  ?item wdt:P361 ?parent .
  ?parent wdt:P345 [] 
  MINUS { ?item wdt:P345 [] }
  MINUS { ?item rdf:type wdno:P345 }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
} 
