SELECT ?item ?label #?awardStat ?award ?_image 
WHERE {
  ?item wdt:P31 wd:Q577 ;
        p:P31 ?awardStat .
  ?awardStat pq:P361 wd:Q44722.
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,he" . 
    ?item rdfs:label ?label
  }
  
OPTIONAL { ?item wdt:P18 ?_image. }
}
