SELECT ?Property_ ?Property_Label ?Property_Description ?property_ ?property_Label ?minimum ?min_unit_Label ?maximum ?max_unit_Label ?constraint_status_ ?constraint_status_Label
WHERE {
  
	?Property_ p:P2302 ?statement .
	?statement ps:P2302 wd:Q21510854 .
	OPTIONAL {?statement pq:P2306 ?property_ .}
	OPTIONAL {?statement pq:P2313 ?minimum .}
	OPTIONAL {?statement pqv:P2313/wikibase:quantityUnit ?min_unit_ .}
	OPTIONAL {?statement pq:P2312 ?maximum .}
	OPTIONAL {?statement pqv:P2312/wikibase:quantityUnit ?max_unit_ .}
	OPTIONAL {?statement pq:P2316 ?constraint_status_ .}

	SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

} 
