SELECT ?item ?named ?url (CONCAT("[[:w:de:",?lemma,"]]") AS ?wikipedia) WHERE {
  ?item wdt:P1343 wd:Q106508758.
  ?item p:P1343 ?statement.
  OPTIONAL {?statement pq:P1810 ?named ; ps:P1343 wd:Q106508758.}
  OPTIONAL {?statement pq:P2699 ?url ; ps:P1343 wd:Q106508758.}  
  OPTIONAL {?sitelink schema:about ?item;
    schema:isPartOf <https://de.wikipedia.org/>;
    schema:name ?lemma.  }
  }
