embed.html#PREFIX wdname: <http://www.wikidata.org/entity/Q1418855> 
SELECT ?item ?itemLabel ?itemDescription ?sl ?st ?ids ?nst ?enwiki
{
    { SELECT ?item ?st ?ids ( ?st-?ids as ?nst) { ?item wdt:P735 wdname: ; wdt:P31 wd:Q5 ; wikibase:statements ?st ; wikibase:identifiers ?ids . MINUS { ?item wdt:P1087 [] } } ORDER BY DESC(?nst) LIMIT 25 }
    hint:Prior hint:runFirst true.  
    ?item wikibase:sitelinks ?sl .
    OPTIONAL { ?enwiki schema:about ?item ; schema:isPartOf <https://en.wikipedia.org/> }          
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}  
ORDER BY DESC(?nst)
