SELECT ?prop ?propLabel ?instances WHERE { 
  {SELECT ?prop_ (COUNT(?item) AS ?instances) WHERE { 
    ?item wdt:P31/wdt:P279* wd:Q43229 . # /wdt:P279*
    ?item ?prop_ wd:Q1860 . 
    
    }
   GROUP BY ?prop_
   #ORDER BY DESC(?instances)
   #LIMIT 500
  }
  ?prop wikibase:directClaim ?prop_ .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE]". } 
  }
ORDER BY DESC(?instances)
