#title: RSFSR is used as death place qualifier value for people dead after 1991-12-12
# Complex constraint from [[Property talk:Q2184]]
# Items with [[Property:P17|country&#32;<small dir="ltr">(P17)</small>]] qualifier of [[Property:P20|place of death&#32;<small dir="ltr">(P20)</small>]] equal to [[d:Q2184|Russian Soviet Federative Socialist Republic <small>(Q2184)</small>]] and [[Property:P570|date of death&#32;<small dir="ltr">(P570)</small>]] after 1991-12-12
SELECT DISTINCT ?item WHERE {
    ?item p:P570/psv:P570 ?node .
    ?node wikibase:timeValue ?dead .
    ?node wikibase:timePrecision ?precision .
    ?item wdt:P19 ?deathPlace .
    ?deathPlace pq:P17 wd:QQ2184 .
    FILTER (?dead > "1991-12-12T00:00:00Z"^^xsd:dateTime)
    FILTER (?precision >= "9"^^xsd:integer)
  }
