# click "Execute" to run the query, then (on the right side) below "Display" select the link "Map" or "Image Grid"
SELECT 
	?item 
	?itemLabel 
	(GROUP_CONCAT(?instanceLabel; separator=", ") as ?instance_of)
	(SAMPLE(?coord) as ?coordinates)
	(SAMPLE(?img) as ?image)
WHERE
{
	VALUES ?item { wd:Q27925924 wd:Q2536715 wd:Q19957249 wd:Q514375 wd:Q647438 wd:Q719472 wd:Q978679 wd:Q2085459 wd:Q3093818 wd:Q3915221 wd:Q4751411 wd:Q4798073 wd:Q6290803 wd:Q7454311 wd:Q9667711 wd:Q10264854 wd:Q10265821 wd:Q14628912 wd:Q14755400 wd:Q16940238 wd:Q17490040 wd:Q19968757 wd:Q27927413 wd:Q27927836 wd:Q27928529 wd:Q27928565 wd:Q27941709 wd:Q10304761 wd:Q892981 wd:Q16336243  }
	OPTIONAL {?item wdt:P625 ?coord } .  
	OPTIONAL {?item wdt:P31 ?instance } .   
  	OPTIONAL {?item wdt:P18 ?img } .   
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en,en" 
                           . ?item rdfs:label ?itemLabel
                           . ?instance rdfs:label ?instanceLabel }
}
GROUP BY ?item ?itemLabel 
