#title: Cims actuals sense URL
# Complex constraint from [[Property talk:Q31074657]]
#
select ?item where {
  ?item p:P361 ?stat .
  ?stat ps:P361 wd:Q31074657 .
  minus { ?stat pq:P2699 [] }
  minus { ?stat pq:P582 [] }
}
