#title: Cims que no són muntanyes
# Complex constraint from [[Property talk:Q31074657]]
# Han de tenir també una referència als 100 cims
select ?item where {
  ?item p:P361 ?stat .
  ?stat ps:P361 wd:Q31074657 .
  ?stat pq:P2699 [] .
  minus {
    ?item p:P31 ?s .
    ?s ps:P31 wd:Q8502 .
    ?s prov:wasDerivedFrom ?ref .
    ?ref pr:P248 wd:Q31074657 .
    ?ref pr:P854 [] .
    ?ref pr:P813 [] .
  }
}
