#title: Municipis sense comarca
# Complex constraint from [[Property talk:Q33146843]]
#
select ?item where {
   ?item wdt:P31 wd:Q33146843.
   minus { ?item wdt:P131/wdt:P31 wd:Q937876 }
   minus { ?item wdt:P131 wd:Q12602 }
 }
