querybuilder/?query={"conditions":[{"propertyId":"P1435","propertyDataType":"wikibase-item","propertyValueRelation":"matching","referenceRelation":"regardless","value":"Q10729054","subclasses":false,"conditionRelation":null,"negate":false},{"propertyId":"P131","propertyDataType":"wikibase-item","propertyValueRelation":"regardless-of-value","referenceRelation":"regardless","value":"","subclasses":true,"conditionRelation":"and","negate":false}],"limit":100,"useLimit":true,"omitLabels":false}
