SELECT ?item ?itemLabel
WHERE
{
  ?item p:P166 ?statement .
  ?statement ps:P166 wd:Q28918638 .
  FILTER NOT EXISTS { ?statement prov:wasDerivedFrom / pr:P4256 ?POE . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],es,en" . }
}
