bigdata/namespace/wdq/sparql?explain&query=SELECT ?e ?label
WITH {
  SELECT ?e {
    VALUES ?e {wd:L7 wd:Q146}.
  }
} AS %0
{
  INCLUDE %0.
  OPTIONAL{?e wikibase:lemma ?lemma}
  OPTIONAL{
    ?e rdfs:label ?labelDe.
    FILTER(LANG(?labelDe) = "de")
  }
  OPTIONAL{
    ?e rdfs:label ?labelDeDe.
    FILTER(LANG(?labelDeDe) = "de-de")
  }
  OPTIONAL{
    ?e rdfs:label ?labelEn.
    FILTER(LANG(?labelEn) = "en")
  }
  BIND(COALESCE(IF(BOUND(?lemma), ?lemma, 1/0),
                IF(BOUND(?labelDe), ?labelDe, 1/0),
                IF(BOUND(?labelDeDe), ?labelDeDe, 1/0),
                IF(BOUND(?labelEn), ?labelEn, 1/0))
       AS ?label).
}
