SELECT ?елементи_ВД   ?назви_статей_на_сайтах_Вікімедіа   ?посилання_на_сайти_Вікімедіа {
  VALUES ?елементи_ВД { wd:Q4115189 } # wd:Q2664631 
  ?посилання_на_сайти_Вікімедіа schema:about ?елементи_ВД .
  OPTIONAL {
    ?посилання_на_сайти_Вікімедіа schema:name ?назви_статей_на_сайтах_Вікімедіа .
  }
}
