SELECT DISTINCT ?person ?personLabel ?personDescription ?band ?bild ?wpsv ?wpfi ?wpen WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "sv". }
  ?person wdt:P31 wd:Q5;
    wdt:P1343 wd:Q110721719;
    p:P1343 ?statement2.
  ?statement2 pq:P478 ?band.
  OPTIONAL { ?person wdt:P18 ?bild. }
  OPTIONAL {
    ?wpsv schema:about ?person;
      schema:isPartOf <https://sv.wikipedia.org/>.
  }
  OPTIONAL {
    ?wpfi schema:about ?person;
      schema:isPartOf <https://fi.wikipedia.org/>.
  }
  OPTIONAL {
    ?wpen schema:about ?person;
      schema:isPartOf <https://en.wikipedia.org/>.
  }

  OPTIONAL { ?person wdt:P27 ?medborgare. }
}
ORDER BY ?band ?personLabel 
LIMIT 200
