sparql?query=SELECT  ?ratio  ?item2 ?item2Label ?dist ?mileage_diff ?section ?lin ?lin2 ?sectionLabel 

WITH {
  SELECT ?item ?section ?elr ?lin ?itemLoc WHERE {
    ?item p:P795 ?stmt .
    ?stmt ps:P795 ?section . 
    ?section wdt:P10271 ?elr .
    ?stmt pq:P6710 ?lin .
    ?item wdt:P625 ?itemLoc .
  }
} AS %items

WHERE { 
  VALUES ?item {wd:Q2525068} .
  INCLUDE %items .
  ?item2 wdt:P795 ?section .
  FILTER (?item != ?item2) .
  {
    SELECT (?item AS ?item2) ?section (?lin AS ?lin2) (?itemLoc AS ?item2Loc) WHERE {
      INCLUDE %items .
    }
  }
  BIND ((geof:distance(?itemLoc, ?item2Loc) / 1.609) AS ?dist) .
  BIND (abs(?lin - ?lin2) AS ?mileage_diff) . 
  BIND (?dist / ?mileage_diff AS ?ratio) . 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } .
} 
ORDER BY ?lin2&explain=details
