SELECT ?predicate ?property ?propertyLabel ?value
WHERE 
{
  wd:Q48895080 ?predicate ?value. 
  ?property wikibase:directClaim ?predicate.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } 
}
