SELECT DISTINCT ?numberLabel (count(?numberLabel) as ?count) WHERE {
  ?number wdt:P31/wdt:P279 wd:Q12503 . #find integers
  ?number rdfs:label ?numberLabel . FILTER(lang(?numberLabel) = "ko")  #get the integer's ko label
  ?item ?property ?numberLabel .  #find items for which the integer's label value is an item property value
  ?item rdfs:label ?itemLabel . FILTER(lang(?itemLabel) = "ko") #show only ko itemLabels 
}
group by ?numberLabel
#having (?count > 10)
order by DESC(?count)
