SELECT DISTINCT ?city ?cityLabel ?bridgeLabel ?womanLabel (BOUND(?enArticle) AS ?hasEn) (BOUND(?frArticle) AS ?hasFr) WHERE {
  ?bridge wdt:P31/wdt:P279* wd:Q12280;
          wdt:P138 ?woman;
          wdt:P131+ ?city.
  ?woman wdt:P31 wd:Q5;
         wdt:P21 wd:Q6581072.
  ?city wdt:P31/wdt:P279* wd:Q486972.
  OPTIONAL {
    ?enArticle a schema:Article;
               schema:about ?woman;
               schema:isPartOf <https://en.wikipedia.org/>.
  }
  OPTIONAL {
    ?frArticle a schema:Article;
               schema:about ?woman;
               schema:isPartOf <https://fr.wikipedia.org/>.
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY ?city
