sparql?format=json&query=SELECT ?super (?aLength + ?bLength as ?length) WHERE { SERVICE gas:service { gas:program gas:gasClass "com.bigdata.rdf.graph.analytics.SSSP" ; gas:in wd:Q5 ; gas:traversalDirection "Forward" ; gas:out ?super ; gas:out1 ?aLength ; gas:maxIterations 10 ; gas:linkType wdt:P279 . } SERVICE gas:service { gas:program gas:gasClass "com.bigdata.rdf.graph.analytics.SSSP" ; gas:in wd:Q349 ; gas:traversalDirection "Forward" ; gas:out ?super ; gas:out1 ?bLength ; gas:maxIterations 10 ; gas:linkType wdt:P279 . } } ORDER BY ?length LIMIT 1
