SELECT DISTINCT ?item ?itemLabel 
WHERE {
  ?sitelink wikibase:badge wd:Q17437796 ; schema:isPartOf <https://es.wikipedia.org/>.
  ?sitelink schema:about ?item .
  FILTER NOT EXISTS { ?wen schema:about ?item; schema:isPartOf <https://en.wikipedia.org/> . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "es" }
} 
