SELECT DISTINCT ?item ?itemLabel 
WHERE
{
	?item wdt:P31 wd:Q476028 .
  	?item wdt:P17 wd:Q229 .
	FILTER NOT EXISTS { ?item wdt:P576 [] . }
	FILTER NOT EXISTS { ?item p:P856 ?claim . ?claim pq:P407 ?lang } 
  	SERVICE wikibase:label { bd:serviceParam wikibase:language "el" }
}
