SELECT ?item ?identifiers ?sitelinks ?statements (COUNT(?any) AS ?cnt) WHERE {
  ?item wdt:P31/wdt:P279* wd:Q21073937; wdt:P17 wd:Q668; wikibase:identifiers ?identifiers; wikibase:sitelinks ?sitelinks; wikibase:statements ?statements .
  MINUS { ?item wdt:P4635 [] }
  OPTIONAL { [] ?any ?item }
} GROUP BY ?item ?identifiers ?sitelinks ?statements
