embed.html##defaultView:Map{"markercluster": {}}
SELECT * WHERE {
  ?item (wdt:P31*/wdt:P279*) wd:Q1362233.
  ?item wdt:P625 ?geo.
  OPTIONAL { ?item wdt:P6375 ?Adresse. }
  OPTIONAL { ?item wdt:P18 ?Bild. }
}
