SELECT ?item ?itemLabel ?itemDescription ?id
{
	BIND( "article"@en  as ?d)
    ?item wdt:P31 wd:Q13442814 ; schema:description ?d ; wikibase:statements 2 ; wikibase:identifiers 1 . 
    ?item wdt:P932 ?id . 
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
