# topics sorted by number of main subject (P921) statements
#defaultView:Table
SELECT DISTINCT ?topic ?topicLabel ?count 
WITH {
  SELECT (count(?work) as ?count) ?topic WHERE {
    ?work wdt:P921 ?topic .
  }
  GROUP BY ?topic
} AS %result
WHERE {
  INCLUDE %result
  FILTER (?count > 1000 ).
  ?topic rdfs:label ?topicLabel .
  FILTER (lang(?topicLabel) = "en")
}
ORDER BY DESC(?count)
