SELECT ?item ?ole ?from WHERE {
  ?item wdt:P10149 ?ole.
  ?item p:P106 ?occupation.
  ?occupation ps:P106 wd:Q860918.
  OPTIONAL { 
    ?occupation pqv:P580 [
        wikibase:timePrecision ?from_precision;
        wikibase:timeValue ?from_time;
      ];
  }
  BIND(YEAR(?from_time) AS ?from)
}
