SELECT ?item ?itemLabel ?instanceOfLabel ?instanceOptionsLabel ?locationLabel WHERE {
  ?item wdt:P31 wd:Q1368262 .
  OPTIONAL{?item wdt:P17 ?location .} 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "nl". }
}
LIMIT 1000
