SELECT ?item ?itemLabel ?image ?coor WHERE {
  ?item wdt:P131 wd:Q12193 .
  ?item wdt:P31 wd:Q2983893  .
  OPTIONAL { ?item wdt:P18 ?image }
           { ?item wdt:P625 ?coor }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,nl,fr,es" .}
  }
