sparql?query=PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?autorname ?order ?autor
WHERE
{
	wd:Q56810046 p:P2093 ?autornamestatement .
    ?autornamestatement ps:P2093 ?autorname .
  	?autornamestatement pq:P1545 ?order .
#  	wd:Q56810046 wdt:P50 ?autor
#	OPTIONAL {?item wdt:P570 ?dod } . 
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en"  }    
}

ORDER BY ?order
#LIMIT 100
