SELECT DISTINCT ?item ?itemLabel
  WHERE {?item wdt:P672 ?string.
         FILTER(strstarts(?string, 'D26'))
         
         SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
         }
