SELECT DISTINCT ?item ?itemLabel
  WHERE {?item wdt:P672 ?string.
         FILTER(strstarts(?string, 'G07.100.100.160'))
         
         SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
         }
