SELECT DISTINCT ?item ?itemLabel
  WHERE {?item wdt:P672 ?string.
         FILTER(strstarts(?string, 'E01.370.600.115.100.160'))
         
         SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
         }
