embed.html##defaultView:Map
SELECT ?s ?sLabel ?coor ?operator ?operatorLabel ?image ?layer WHERE {  
  
       ?s wdt:P31/wdt:P279* wd:Q28564 ;
          wdt:P17 wd:Q145 ;
          wdt:P625 ?coor ;
          wdt:P137 ?operator ;
          OPTIONAL {?s wdt:P18 ?image .}
BIND( 
       IF(?operator = wd:Q16998823, "Newcastle", 
       IF(?operator = wd:Q6386521, "Northumberland", 
       IF(?operator = wd:Q17017005, "North Tyneside", 
       IF(?operator = wd:Q16948698, "Darlington",
       IF(?operator = wd:Q6841843, "Middlesbrough",   
       IF(?operator = wd:Q16953331, "Bradford", 
       IF(?operator = wd:Q6515870, "Leeds",   
       IF(?operator = wd:Q16995709, "Kirklees", 
       IF(?operator = wd:Q7961061, "Wakefield",   
       IF(?operator = wd:Q16985873, "Calderdale",
       IF(?operator = wd:Q17017103, "North Yorkshire",
       IF(?operator = wd:Q17059453, "York", 
       IF(?operator = wd:Q16989282, "East Yorkshire",   
       IF(?operator = wd:Q7492609, "Sheffield",
       IF(?operator = wd:Q7063612, "Nottingham",
       IF(?operator = wd:Q16934215, "Nottinghamshire", 
       IF(?operator = wd:Q6519163, "Leicester",
       IF(?operator = wd:Q5261430, "Derby",   
       IF(?operator = wd:Q5261561, "Derbyshire", 
       IF(?operator = wd:Q6386295, "Staffordshire",
       IF(?operator = wd:Q16996347, "Lincolnshire", 
       IF(?operator = wd:Q3305205, "Suffolk",   
       IF(?operator = wd:Q14942414, "Northamptonshire",
       IF(?operator = wd:Q6658351, "Liverpool", 
       IF(?operator = wd:Q17038877, "Wirral",
       IF(?operator = wd:Q7446119, "Sefton",   
       IF(?operator = wd:Q16829355, "Cheshire East",   
       IF(?operator = wd:Q6386149, "Lancashire", 
       IF(?operator = wd:Q2302252, "Manchester",   
       IF(?operator = wd:Q16984489, "Blackpool",
       IF(?operator = wd:Q7999507, "Wigan",    
       IF(?operator = wd:Q17019804, "Rochdale",  
       IF(?operator = wd:Q16829360, "Cheshire West & Chester",   
       IF(?operator = wd:Q5194027, "Cumbria",  
       IF(?operator = wd:Q5646045, "Hampshire",
       IF(?operator = wd:Q1144019, "Bournemouth",   
       IF(?operator = wd:Q7205775, "Plymouth",
       IF(?operator = wd:Q6385990, "Devon", 
       IF(?operator = wd:Q3774189, "Cornwall",   
       IF(?operator = wd:Q17034697, "Torbay",   
       IF(?operator = wd:Q17040033, "Swindon",
       IF(?operator = wd:Q1990879, "Wiltshire",   
       IF(?operator = wd:Q16953796, "Bristol",   
       IF(?operator = wd:Q6386270, "Somerset",  
       IF(?operator = wd:Q17016922, "North Somerset", 
       IF(?operator = wd:Q93612, "Shropshire",   
       IF(?operator = wd:Q16842680, "Herefordshire", 
       IF(?operator = wd:Q8034245, "Worcestershire",   
       IF(?operator = wd:Q16839354, "Gloucestershire",   
       IF(?operator = wd:Q6386353, "West Sussex", 
       IF(?operator = wd:Q16953725, "Brighton & Hove",   
       IF(?operator = wd:Q5399679, "Essex",   
       IF(?operator = wd:Q6386127, "Kent",   
       IF(?operator = wd:Q4973687, "Bromley",
       IF(?operator = wd:Q7331065, "Richmond",   
       IF(?operator = wd:Q6084379, "Islington",  
       IF(?operator = wd:Q5604860, "Greenwich", 
       IF(?operator = wd:Q4861611, "Barnet",    
       IF(?operator = wd:Q5637369, "Hackney",
       IF(?operator = wd:Q7305508, "Redbridge",   
       IF(?operator = wd:Q4916650, "Birmingham",   
       IF(?operator = wd:Q7417057, "Sandwell",
       IF(?operator = wd:Q7963789, "Walsall",
       IF(?operator = wd:Q8030462, "Wolverhampton",
       IF(?operator = wd:Q17021590, "Solihull",   
            ""))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))) AS ?layer).  
  
SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
ORDER BY ?sLabel
