SELECT ?item ?itemLabel ?theme ?themeLabel WHERE {
  ?item wdt:P31 wd:Q3305213 .
  ?item wdt:P144 ?theme .
  ?theme wdt:P31 wd:Q1406161 .
  ?theme wdt:P4969 ?item .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  }
