SELECT ?item ?itemLabel ?itemDescription ?name ?sitelink WHERE {
  ?sitelink schema:about ?item; schema:isPartOf <https://uk.wikipedia.org/>; schema:name ?name; wikibase:badge wd:Q70893996 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language 'uk' }
} LIMIT 250
