SELECT ?after ?count WHERE {
  { SELECT ?after (COUNT(*) AS ?count) WHERE {
    ?item wdt:P31 wd:Q9842; wdt:P17 wd:Q55; rdfs:label ?label .
    MINUS { ?item wdt:P138 [] } .
    FILTER(LANG(?label) = "nl" && STRENDS(STR(?label), "school") && CONTAINS(STR(?label), " ")) .
    BIND(STRBEFORE(STR(?label), "school") AS ?after) .
  } GROUP BY ?after } .
}
ORDER BY DESC(?count)
LIMIT 100
