SELECT ?item ?itemLabel WHERE {
  ?item wdt:P31/wdt:P279* wd:Q464980.
  {
    ?item wdt:P131 wd:Q1852569.
  } UNION {
    ?item wdt:P276 wd:Q1852569.
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "cs,en". }
}
