#Big cities, grouped into map layers by population
#defaultView:Map
SELECT DISTINCT ?city ?cityLabel (SAMPLE(?loc) AS ?location) (MAX(?pop) AS ?population) (SAMPLE(?layer) AS ?layer)
WHERE
{
  ?city wdt:P31/wdt:P279* wd:Q515;
        wdt:P625 ?loc;
        wdt:P1082 ?pop.
  FILTER(?pop >= 500000).
  BIND(
    IF(?pop < 1000000, "<1M",
    IF(?pop < 2000000, "1M-2M",
    IF(?pop < 5000000, "2M-5M",
    IF(?pop < 10000000, "5M-10M",
    IF(?pop < 20000000, "10M-20M",
    ">20M")))))
    AS ?layer).
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
GROUP BY ?city ?cityLabel
