SELECT DISTINCT ?item ?itemLabel ?count 
WHERE
{
	{ 	SELECT ?item (count(*) as ?count) 
      	WHERE
		{
      		?pid wdt:P1196 ?item .
    	}
    	GROUP BY ?item
		ORDER BY DESC(?count)
		LIMIT 200                 
	}
  	SERVICE wikibase:label { bd:serviceParam wikibase:language "ar" . }
}
ORDER BY DESC(?count)
