PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX v: <http://www.wikidata.org/prop/statement/>
PREFIX q: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?airport ?icao ?airportLabel WHERE {
    ?airportType wdt:P279* wd:Q62447 .
    ?airport wdt:P31 ?airportType .
    ?airport wdt:P17 wd:Q183 .
    OPTIONAL { ?airport wdt:P239 ?icao }
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "de" .
    }
 } ORDER BY ?airportLabel
