#defaultView:Map
SELECT DISTINCT ?item ?label ?coord WHERE {
  ?item wdt:P17 wd:Q145.
  ?item wdt:P625 ?coord.
  ?item rdfs:label ?labelWithLanguage.
  BIND(STR(?labelWithLanguage) AS ?label)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  FILTER(STRSTARTS(?labelWithLanguage, "Llan"))
  FILTER((LANG(?labelWithLanguage)) = "en")
}
