#defaultView:BubbleChart
SELECT (COUNT(?mp) AS ?mps) ?job ?jobLabel
WHERE { 
?mp wdt:P39 wd:Q16707842;
    wdt:P106 ?job.
FILTER (?job not in (wd:Q82955, wd:Q486839) )
SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
} GROUP BY ?job ?jobLabel
ORDER BY DESC(?mps)
