SELECT ?item ?taxonName ?commonName ?itemLabel WHERE {
  ?item wdt:P225 ?taxonName .
  ?item wdt:P1843 ?commonName .
  FILTER(LANG(?commonName) = 'en' )
  SERVICE wikibase:label {
  bd:serviceParam wikibase:language "en" .
  ?item rdfs:label ?itemLabel .
  }
  FILTER(!REGEX(SUBSTR(?itemLabel,1, 2), "\\p{Lu}"))
} 
ORDER BY ASC(?taxonName)
