select ?i ?iLabel ?nfLabel where{
  ?i wdt:P31 wd:Q11344;
     wdt:P1086 ?no;
     wdt:P138 ?nf.
  # OPTIONAL { ?i skos:altLabel ?ais . FILTER (lang(?ais) = "ja")}
  ?nf wdt:P31 wd:Q5.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "ja" }
  
}order by ?no
