SELECT ?director ?directorLabel ?actor ?actorLabel ?FilmCount WHERE {
  {
    SELECT ?director ?actor (COUNT(?film) AS ?FilmCount) WHERE {
      ?film wdt:P57 ?director.
      ?film wdt:P161 ?actor.
    }
    GROUP BY ?director ?actor
    HAVING (?FilmCount > 20)
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY DESC(?FilmCount) ?directorLabel ?actorLabel
