SELECT ?item ?dob
WHERE 
{
  ?item wdt:P27 wd:Q20.
  ?item wdt:P569 ?dob .
  filter not exists {?item wdt:P734 []. } 
  hint:Prior hint:rangeSafe true .
  FILTER("1820-00-00"^^xsd:dateTime <= ?dob && ?dob <= "1920-00-00"^^xsd:dateTime)
 }
