SELECT distinct ?item ?itemLabel ?fort ?fortLabel WITH { SELECT ?item ?itemLabel
WHERE 
{
  ?item wdt:P131/wdt:P131 wd:Q22 .
  ?item wdt:P31/wdt:P279* wd:Q55659167. 
  ?item rdfs:label ?itemLabel . filter(lang(?itemLabel)="en")
  
} } as %i
WHERE
{
  INCLUDE %i
  ?fort skos:altLabel ?itemLabel .
  filter not exists {?fort wdt:P206 [] . }
  filter not exists {?fort wdt:P1889 ?item . }
  ?fort wdt:P131/wdt:P131 wd:Q22 .
  
   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
