# places in Scotland according to P131, having a single P131

select ?item ?itemLabel ?itemDescription ?elseLabel ?P31Label 
with { select ?item ?else ?coords where {
   ?item wdt:P131 ?else  .
  ?else wdt:P31 wd:Q15060255  . hint:Prior hint:runFirst true.
  ?item wdt:P625 ?coords .
  } } as %i
where
{
  include %i
 
  filter not exists { ?item wdt:P131 ?else2 .   {?else2 wdt:P31 wd:Q15060255 .} UNION {?else2 wdt:P131* wd:Q21. hint:Prior hint:gearing "forward".} filter(str(?else2) != str(?else)) } 
#  ?item wdt:P31 ?P31 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".
                         ?else rdfs:label ?elseLabel.
                         ?item rdfs:label ?itemLabel .
                         ?item schema:description ?itemDescription .
                         #?P31 rdfs:label ?P31Label .
                          
                         } 
}
