SELECT ?item ?itemLabel ?article WHERE {
?item wikibase:statements "0"^^xsd:integer.
?article schema:about ?item.
?article schema:isPartOf <https://en.wikipedia.org/>.
SERVICE wikibase:label {bd:serviceParam wikibase:language "en"}
}
limit 500
