SELECT ?item ?itemLabel (min(year(?date)) as ?year) (group_concat(distinct ?typelabel;separator=", ") as ?P31) (group_concat(distinct ?dirLabel;separator=", ") as ?P57) with {
  select ?item where 
{
  ?item wdt:P31/wdt:P279* wd:Q11424.
  optional {?item schema:description ?Den. filter(lang(?Den)="en")}
  filter(!bound(?Den))
} } as %i
where
{ include %i
  optional {?item wdt:P577 ?date .}
  optional {?item wdt:P57 ?dir . optional {?dir rdfs:label ?dirLabel. filter(lang(?dirLabel)="en")} }
 optional {?item rdfs:label ?itemLabel. filter(lang(?itemLabel)="en")}
optional { ?item wdt:P31 ?type.   ?type rdfs:label ?typelabel. filter(lang(?typelabel)="en")}
 } group by ?item ?itemLabel
