SELECT ?river ?riverLabel ?claims WITH {
  SELECT distinct ?river WHERE {
  #  VALUES ?river {wd:Q19721}
   ?river wdt:P131/wdt:P131 wd:Q22 . 
    } } as %i
WITH {
  SELECT distinct ?river WHERE {
    INCLUDE %i
    ?river wdt:P31/wdt:P279* wd:Q55659167. hint:Prior hint:gearing "forward".
    } } as %j
WITH {
  SELECT ?river (count(?item) as ?items) (count(distinct ?item) as ?claims) WHERE {
    INCLUDE %j
    OPTIONAL { ?item ?predicate ?river .
    ?property wikibase:directClaim ?predicate . } 
    } group by ?river } as %k
WHERE
{
  INCLUDE %k
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } 
} order by DESC(?claims)
