SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P195 ?collection. ?collection wdt:P17 ?countries FILTER (?countries IN (wd:Q40, wd:Q183, wd:Q39)) . 
  MINUS { ?entity wdt:P195 []; wdt:P195 ?collection. ?collection wdt:P17 ?countries FILTER (?countries IN (wd:Q40, wd:Q183, wd:Q39))  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
