SELECT ?entity ?entityLabel ?entityDescription ?st ?sl ?ids
WHERE
{
  ?entity wdt:P31 wd:Q7725634.
  {
    ?entity wdt:P50 ?author.
    ?author wdt:P19 ?place.
    ?place wdt:P17 ?country.
  }
  UNION
  {
    ?entity wdt:P50 ?author.
    ?author wdt:P27 ?country.
  }
  UNION
  {
    ?entity wdt:P4647 ?firstperformance.
    ?firstperformance wdt:P17 ?country.
  }
FILTER (?country IN (wd:Q40, wd:Q183, wd:Q39)). 
  # MINUS { ?entity wdt:   [] }
  OPTIONAL { ?entity wikibase:statements ?st ; wikibase:sitelinks ?sl ; wikibase:identifiers ?ids } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" } 
}
