SELECT ?item ?file {{{ ?item wdt:P225 "l.lagopus scoticus" } UNION { ?item wdt:P225 "L.lagopus scoticus" } UNION { ?item rdfs:label "Grugiar goch"@cy } } .
                      ?item wdt:P18 ?file .
                      filter ( bound ( ?file ) )
                      }
