#defaultView:Table
SELECT ?item ?itemLabel ?publicationDate (group_concat(?genreLabel; separator=", ") as ?genres) ?steamurl WHERE {
  ?item wdt:P31 wd:Q7889.
  ?item wdt:P577 ?publicationDate.
  ?item wdt:P136 ?genre.
  ?item wdt:P400 wd:Q1406.
  wd:P1733 wdt:P1630 ?formatterurl.
  OPTIONAL { ?item wdt:P1733 ?steamId. }.
  SERVICE wikibase:label { 
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". 
    ?genre rdfs:label ?genreLabel.
    ?item rdfs:label ?itemLabel.
  }.
  BIND(YEAR(?publicationDate) AS ?year).
  BIND(IRI(REPLACE(?steamId, '^(.+)$', ?formatterurl)) AS ?steamurl).
  FILTER(?year = (YEAR(NOW()))).
}
GROUP BY ?item ?itemLabel ?publicationDate ?steamurl
ORDER BY ?publicationDate ?itemLabel
LIMIT 500
