SELECT ?item ?itemLabel ?SHARECatID ?SHAREVDEID ?EDIT16ID
WHERE
{
  ?item wdt:P3987 ?SHARECatID;
        wdt:P6329 ?SHAREVDEID; 
        wdt:P5492 ?EDIT16ID.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  }
