embed.html##defaultView:Map
SELECT * WHERE {
SERVICE wikibase:box {
    ?place wdt:P625 ?location .
    bd:serviceParam wikibase:cornerWest "Point(-80 49)"^^geo:wktLiteral .
    bd:serviceParam wikibase:cornerEast "Point(-60 80)"^^geo:wktLiteral .
  }
?place wdt:P131 wd:Q764294 ; .
}
