#NARA P1225 example of series
SELECT ?item ?ID ?link ?itemLabel ?date_debut ?date_fin
WHERE 
{
  ?item wdt:P1225 ?ID_NARA;
        wdt:P31 wd:Q2668072;
        wdt:P6224 wd:Q59294700;
        wdt:P1225 ?ID;
        wdt:P580 ?date_debut;
        wdt:P582 ?date_fin. 
        wd:P1225 wdt:P1630 ?ffu .
        BIND(iri(CONCAT(REPLACE(?ffu,'\\$1',?ID),?ID)) AS ?link)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
ORDER BY?ID
LIMIT 5
