SELECT distinct ?item ?itemLabel ?carica ?caricaLabel ?ruoloLabel ?governo ?governoLabel ?designatoLabel ?inizio ?fine
WHERE 
{
  ?item p:P39 ?statement .
  ?statement ps:P39 ?carica. 
  {?carica wdt:P279* wd:Q3858501 .} #ministro
  UNION
  {?carica wdt:P279* wd:Q796897} #presidente del consigli
  UNION
  {?carica wdt:P279* wd:Q4011164} #vicepresidente
  
  OPTIONAL{?statement pq:P5054 ?governo .}
  OPTIONAL{?statement pq:P580 ?inizio .}
  OPTIONAL{?statement pq:P582 ?fine .}
  OPTIONAL{?statement pq:P2868 ?ruolo .}
  OPTIONAL{?statement pq:P748 ?designato .}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "it". }
  FILTER(?governo = wd:Q3112431)
}
ORDER BY desc(?designatoLabel) ?caricaLabel ?inizio ?fine
