SELECT ?item ?itemLabel WHERE {
  ?item wdt:P31 wd:Q571.
  ?item wdt:P136 wd:Q213051 .
  ?item wdt:P364 wd:Q1860 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  OPTIONAL { ?item wdt:P921 ?dummy0. }
  FILTER(!BOUND(?dummy0))
}
