SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity dct:language wd:Q12107 ; wikibase:lexicalCategory ?cat ; wikibase:statements ?st 
GROUP BY ?l ?cat ?st. ?entity wdt:wikibase:lexicalCategory ?grouping .} GROUP BY ?grouping HAVING (?count >= 0) ORDER BY DESC(?count) LIMIT 1000
