SELECT DISTINCT ?item ?itemLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE]". }
  {
    SELECT DISTINCT ?item WHERE {
      ?item p:P279 ?statement0.
      ?statement0 (ps:P279/(wdt:P279*)) wd:Q278368.
      MINUS {
        ?item p:P279 ?statement1.
        ?statement1 (ps:P279/(wdt:P279*)) wd:Q16532929.
      }
    }
  }
}
