SELECT ?qual ?qualLabel ?count 
WHERE {
  {
    SELECT ?qual (COUNT(DISTINCT ?person) AS ?count) WHERE {
      ?person p:P39 [ ps:P39 [ wdt:P279* wd:Q21328618 ]; ?pq_qual ?pq_obj ] .
      ?qual wikibase:qualifier ?pq_qual .
    }
    GROUP BY ?qual ?qualLabel
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
ORDER BY DESC (?count)
