SELECT
  (SAMPLE(?i) as ?item)
  ?p ?pLabel 
  (CONCAT("[[Property:",strafter(str(?p),"y/"),"|",str(?pLabel),"]]") as ?t)
  (COUNT(?i) as ?ct)
  (CONCAT('align=left data-sort-value="',strafter(str(?p),"y/P"),'"
