SELECT ?item  ?fisher ?Kurth ?bartsch ?CD ?sitelink_label WHERE { 
  optional{ ?item p:P528 [ pq:P972 wd:Q100320351; ps:P528 ?fisher] . }
  ?item p:P528 [ pq:P972 wd:Q101542418; ps:P528 ?Kurth] . 
  optional{ ?item p:P528 [ pq:P972 wd:Q18327311; ps:P528 ?bartsch] . }
  optional{ ?item p:P528 [ pq:P972 wd:Q101181018; ps:P528 ?CD] . }
  optional{   ?commonsSitelink schema:about ?item; schema:isPartOf <https://commons.wikimedia.org/>; schema:name ?sitelink_label . }
} order by ?Kurth
