SELECT ?item ?itemLabel ?publication_date ?DOI WHERE {
  ?item wdt:P921 wd:Q14914098.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  OPTIONAL { ?item wdt:P577 ?publication_date. }
  OPTIONAL { ?item wdt:P356 ?DOID. }
  BIND(URI(CONCAT(STR("https://dx.doi.org/"), ?DOID)) AS ?DOI)
}
ORDER BY DESC(?publication_date) 
