SELECT ?item ?itemLabel (GROUP_CONCAT(DISTINCT ?value; separator=" ") as ?trailer) (SAMPLE(?t) as ?wt)
{
	{ ?item p:P1651 ?statement . ?statement ps:P1651 ?v . ?statement pq:P3831 wd:Q622550 . BIND(CONCAT("[https://www.youtube.com/watch?v=", ?v, " y]")  as ?value) }
  	UNION
	{ ?item p:P10   ?statement . ?statement ps:P10   ?v . ?statement pq:P3831 wd:Q622550 . BIND(CONCAT("[", str(?v), " C]")  as ?value) }
	?item wdt:P31/wdt:P279* wd:Q11424 .
        OPTIONAL { ?item p:P10 [pq:P3831 wd:Q622550 ; ps:P10 ?t ] }
  	SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
GROUP BY ?item ?itemLabel
ORDER BY DESC(xsd:integer(strafter(str(?item), "Q")))
LIMIT 2000
