SELECT DISTINCT ?item ?itemLabel 
WHERE 
{
  ?item wdt:P527 ?part.
  ?item ?property [pq:P642 ?part]
  FILTER (?property != p:P31)
  FILTER (?property != p:P279)
  FILTER (?property != p:P2868)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } # Helps get the label in your language, if not, then en language
}
