SELECT ?item (CONCAT("[[Wikidata:WikiProject sum of all paintings/Collection/",?name, "|list]]") AS ?listlink) (COUNT(DISTINCT ?painting) AS ?count) WHERE {
  ?painting wdt:P31 wd:Q3305213 .
  ?painting wdt:P195 wd:Q333515 .
  ?painting wdt:P276 ?item. 

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?item rdfs:label ?name .
   }
  } GROUP BY ?item ?name ?listlink
ORDER BY DESC(?count)
LIMIT 120
