#Dibner Portrait Project Entities
SELECT ?item ?itemLabel ?itemDescription ?image WHERE {
  ?item wdt:P5008 wd:Q103505599.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  OPTIONAL { ?item wdt:P18 ?image. }
}
