SELECT ?item (CONCAT("[[Wikidata:WikiProject sum of all paintings/Creator/",?name, "|list]]") AS ?listlink) ?paintingcount WHERE {
  ?item wdt:P106 wd:Q1028181 .
  ?item wdt:P31 wd:Q5 .
  ?item wdt:P19 ?loc.
  ?loc wdt:P131* wd:Q752.  { 
    SELECT ?item (COUNT(?item) as ?paintingcount) WHERE {
    ?painting wdt:P31 wd:Q3305213 .  
    ?painting wdt:P170 ?item . 
     } GROUP BY ?item 
  }
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?item rdfs:label ?name .
  }
}
GROUP BY ?item ?name ?listlink ?paintingcount
ORDER BY DESC(?paintingcount)
LIMIT 500
