SELECT 
   (wd:Q847 as ?item) 
   (SAMPLE(?a) as ?sample) 
   (COUNT(DISTINCT ?a) as ?ct)
   (wd:Q27020041 as ?type)
  ("0 b" as ?level)
  ("tennis season" as ?descr)
WHERE
   { ?a wdt:P31 wd:Q27020041 ; wdt:P641 wd:Q847 }
