SELECT DISTINCT ?entity ?entityLabel ?value ?valueLabel WHERE {  ?entity wdt:P31 wd:Q55488 .  ?entity wdt:P17 wd:Q159 .  ?entity p:P81 ?prop . OPTIONAL { ?prop ps:P81 ?value }  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }}
