SELECT ?item (COUNT(?item) as ?count) WHERE {
  ?painting wdt:P31 wd:Q3305213 .  
  ?painting wdt:P921 ?item . 
  ?painting wdt:P136 wd:Q2864737 .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?item rdfs:label ?name .
   }
} GROUP BY ?item ?name 
HAVING (?count > 5)
ORDER BY DESC(?count) 
LIMIT 300
