SELECT ?entity ?entityLabel ?entityDescription ?st ?sl ?ids
WHERE
{
  ?entity wdt:P31 ?grouping.
VALUES ?grouping { wd:Q113025511 wd:Q113015553 }. 
  # MINUS { ?entity wdt:   [] }
  OPTIONAL { ?entity wikibase:statements ?st ; wikibase:sitelinks ?sl ; wikibase:identifiers ?ids } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" } 
}
