SELECT ?item ?party ?district ?start ?end
WHERE 
{
  ?item p:P39 ?statement .
  ?statement ps:P39 wd:Q18171345  ; pq:P2937 wd:Q2785872 .
  OPTIONAL { ?statement pq:P580 ?start }
  OPTIONAL { ?statement pq:P582 ?end }
  OPTIONAL { ?statement pq:P768 ?district }
  OPTIONAL { ?statement pq:P4100 ?party }
}
