SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P4101 wd:Q174570; wdt:P31/wdt:P279* wd:Q1266946 . 
  MINUS { ?entity wdt:P4101 []; wdt:P4101 wd:Q174570; wdt:P31/wdt:P279* wd:Q1266946  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
