embed.html##title: films with Sean Connery missing "publication date" (P577)
SELECT DISTINCT ?film ?filmLabel ?filmDescription 
{
  	hint:Query hint:optimizer "None" .
  	?film ?wdt wd:Q4573 .
  	?property wikibase:directClaim ?wdt ; wikibase:claim ?p ; wikibase:statementProperty ?ps
  	{ ?film wdt:P31/wdt:P279* wd:Q11424 } UNION { ?film wdt:P31 wd:Q5398426 }
    FILTER NOT EXISTS { ?film wdt:P577 [] }   
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
