#Full texts (URLs) of works by Theun de Vries
SELECT distinct ?work ?workLabel ?workDescription
?authorLabel 
?fulltext

WHERE
{
  BIND(wd:Q2143934 as ?author) . #Theun de Vries
  BIND(wd:Q2143934 as ?translator) . #Theun de Vries
  {?work wdt:P50 ?author} UNION {?work wdt:P655 ?translator}.
  OPTIONAL {?work wdt:P953 ?fulltext.}

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "nl". 
  }
} ORDER BY DESC (?fulltext)
