SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P31 wd:Q3305213; wdt:P170 wd:Q296 . 
  MINUS { ?entity wdt:P195 []; wdt:P31 wd:Q3305213; wdt:P170 wd:Q296  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
