SELECT DISTINCT ?item ?itemLabel WHERE {
  { ?NorseClass wdt:P361+ wd:Q24175569 . }
  UNION
  { ?NorseClass wdt:P2596 wd:Q24175569 . }
  ?item wdt:P31/wdt:P279* ?NorseClass .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
