SELECT DISTINCT ?item ?description WHERE { 
  ?item p:P195/ps:P195 wd:Q163804 . 
  ?item wdt:P31 wd:Q3305213 . 
  MINUS { ?item wdt:P170 [] } .
  MINUS { ?item schema:description ?description . FILTER(LANG(?description)='en') } 
  ?item schema:description ?description . FILTER(LANG(?description)='de')
} LIMIT 2000
