SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P6104 wd:Q115191197 . 
  MINUS { ?entity wdt:P1343 []; wdt:P6104 wd:Q115191197  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
