SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P9092 ?id . 
  MINUS { ?entity wdt:P31 []; wdt:P9092 ?id  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
