SELECT ?item (COUNT(?sitelink) AS $slcnt) WHERE {
  ?item wdt:P5008 wd:Q66098665 .
  FILTER NOT EXISTS { ?item wdt:P31 wd:Q18608583 }
  FILTER NOT EXISTS { ?item wdt:P155 ?dummy0 }
  FILTER NOT EXISTS { ?item wdt:P156 ?dummy0 }
  FILTER NOT EXISTS { ?item wdt:P373 ?dummy0 }
  FILTER NOT EXISTS { ?item wdt:P31 wd:Q22936940 }
  FILTER NOT EXISTS { ?item wdt:P31 wd:Q57733325 }
  FILTER NOT EXISTS { ?item wdt:P31 wd:Q66208461 }
  FILTER NOT EXISTS { ?item wdt:P31 wd:Q13406463 }
  FILTER NOT EXISTS { ?item wdt:P31 wd:Q50382640 }
  FILTER NOT EXISTS { ?item wdt:P279 wd:Q16510064 }
  FILTER NOT EXISTS { ?item wdt:P279 wd:Q526719 }
  FILTER NOT EXISTS { ?item wdt:P279 wd:Q13406554 }
  FILTER NOT EXISTS { ?item wdt:P1269 ?dummy0 }
  FILTER NOT EXISTS { ?item wdt:P279 wd:Q2122052 }
  FILTER NOT EXISTS { ?item wdt:P393 "1" }
  OPTIONAL { ?sitelink schema:about ?item . }
} 
GROUP BY(?item) ORDER BY DESC(?slcnt) LIMIT 8000
