=#defaultView:ImageGrid
SELECT * WHERE {
  ?item wdt:P31 wd:Q5 ; wdt:P18 ?img .
  ?item wdt:P569 ?dob .
  ?item wdt:P21 wd:Q6581072 .
  filter ( year( ?dob ) < 1800 )
  minus { [] wdt:P180 ?item }
} limit 100
