SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P31 wd:Q4830453 . 
  MINUS { ?entity wdt:P17 []; wdt:P31 wd:Q4830453  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
