SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P31/wdt:P279* wd:Q7379880 . 
  MINUS { ?entity wdt:P131 []; wdt:P31/wdt:P279* wd:Q7379880  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
