SELECT ?item ?volume ?issue ?startpage WHERE {  
  ?item wdt:P1433 wd:Q220370 .
  OPTIONAL {?item wdt:P478 ?volume} .
  OPTIONAL {?item wdt:P433 ?issue} .
  OPTIONAL {?item wdt:P304 ?pages0} . 
  BIND(replace(?pages0, "-", "–") AS ?pages)
  BIND(if(contains(?pages,  "–"), strbefore(?pages, "–"), ?pages) as ?startpage)
  BIND(if(contains(?pages,  "–"), strafter(?pages, "–"), ?pages) as ?endpage)
  FILTER(contains(?pages0,  "zootaxa"))
}
ORDER BY ASC(xsd:integer(?volume)) ASC(xsd:integer(?issue)) ASC(xsd:integer(?startpage))
