SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity wdt:P31 wd:Q7889. ?entity wdt:P136 ?grouping .} GROUP BY ?grouping HAVING (?count >= 5) ORDER BY DESC(?count) LIMIT 1000
