PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX q: <http://www.wikidata.org/prop/qualifier/>
PREFIX v: <http://www.wikidata.org/prop/statement/>
#step 3: find missing ordinal on "series" property
#by Jura1 Dec 31, 2015

SELECT ?season ?seasonLabel ?series ?seriesLabel ?sitelink ?WP
WHERE 
{
       #hint:Query hint:optimizer "None" . 
	?season wdt:P31 wd:Q3464665 . 
    ?sitelink <http://schema.org/about> ?season . 
    ?season wdt:P31 ?instance
    FILTER(SUBSTR(str(?sitelink), 11, 20) = ".wikipedia.org/wiki/")
    #       FILTER(CONTAINS(str(?sitelink), "wikipedia.org")) .
    BIND(REPLACE(str(?sitelink), "%20", " ") As ?WP)
            
    #?season wdt:P179 ?series

    ?statement v:P179 ?series . ?season p:P179 ?statement .  OPTIONAL{?statement ?pq_qual ?ordinal . wd:P1545 wikibase:qualifier ?pq_qual } . FILTER(!BOUND(?ordinal))
    
  	SERVICE wikibase:label {
    	bd:serviceParam wikibase:language "en" .
    	#?season rdfs:label ?seasonLabel .
  	}
}
ORDER BY ?seasonLabel
LIMIT 1000
