SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity wdt:P17 wd:Q38 ; wdt:P2186 ?wlm. ?entity wdt:P131 ?grouping .} GROUP BY ?grouping HAVING (?count >= 8) ORDER BY DESC(?count) LIMIT 1000
