SELECT ?item ?inv (year(?collectiondate) as ?collectionyear) ?rkdurl WHERE {
  wd:P350 wdt:P1630 ?formatterurl .
  ?item p:P195 ?collectionstatement .
  ?collectionstatement ps:P195 wd:Q190804 .
  ?item wdt:P217 ?inv .
  FILTER regex(?inv, "^SK-C-\\d+(-\\w)?$") 
  OPTIONAL { ?collectionstatement pq:P580 ?collectiondate }  .
  OPTIONAL { ?item wdt:P350 ?rkdid }.
  BIND(REPLACE(?rkdid, '^(\\d+)$', CONCAT("[", ?formatterurl, " $1]")) AS ?rkdurl)  .  
  } ORDER BY xsd:integer(REPLACE(?inv, "^SK-C-(\\d+)(-\\w)?$", "$1")) ?inv
LIMIT 2000
