SELECT ?item ?group ?district ?start WHERE {
  ?item wdt:P31 wd:Q5;
    p:P39 ?ps.
  ?ps ps:P39 wd:Q20065966;
    pq:P580 ?start.
  OPTIONAL { ?ps pq:P580 ?start. }
  OPTIONAL { ?ps pq:P582 ?end. }
  OPTIONAL { ?ps pq:P4100 ?group. }
  OPTIONAL { ?ps pq:P768 ?district. }
  FILTER((!(BOUND(?end)))
