SELECT DISTINCT ?item ?country_label ?language_label (MIN(YEAR(?date)) AS ?year) WHERE {
  ?item wdt:P1343 wd:Q105406968;wdt:P31/wdt:P279* wd:Q11424.
  OPTIONAL{?item wdt:P495 ?country. ?country rdfs:label ?country_label. FILTER(LANG(?country_label)="en")}
  OPTIONAL{?item wdt:P364 ?language. ?language rdfs:label ?language_label. FILTER(LANG(?language_label)="en")}
  OPTIONAL{?item wdt:P577 ?date}
}
GROUP BY ?item ?country_label ?language_label
