SELECT 
   (wd:Q47403752 as ?item) 
   (SAMPLE(?a) as ?sample) 
   (COUNT(DISTINCT ?a) as ?ct)
   (wd:Q47403752 as ?type)
("2 B" as ?level)
("tournament by gender edition" as ?descr)
WHERE
   { ?a wdt:P641 wd:Q847 ; wdt:P31 wd:Q47403752 }
