SELECT ?item ?itemLabel ?collection ?pages ?creator ?ars3d_uri (GROUP_CONCAT(DISTINCT ?img; SEPARATOR = ",") AS ?images) ?lastUpdate ?versionNo WHERE { ?item wdt:P31 wd:Q109532996; wdt:P361 wd:Q105268778; wdt:P195 ?collection; wdt:P304 ?pages; wdt:P170 ?creator. OPTIONAL { ?item wdt:P6500 ?img. } ?item wdt:P2888 ?ars3d_uri; schema:dateModified ?lastUpdate; schema:version ?versionNo. SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } } GROUP BY ?item ?itemLabel ?collection ?pages ?creator ?ars3d_uri ?lastUpdate ?versionNo ORDER BY DESC (?itemLabel)
