#defaultView:Map
SELECT DISTINCT ?item ?itemlabel ?coor ?image ?country
{
	?item wdt:P31 wd:Q39715 . 
	?item wdt:P17 wd:Q145 .
	OPTIONAL { ?item wdt:P625 ?coor }
	OPTIONAL { ?item wdt:P18 ?image }  
	OPTIONAL { ?item rdfs:label ?itemlabel . FILTER(lang(?itemlabel)="cy")  }  
	OPTIONAL { ?item wdt:P131* ?country . ?country wdt:P31 wd:Q3336843 }    
}
