SELECT ?item ?position ?start ?replaces ?end ?cause  ?replaced_by WHERE {
  ?item p:P39 ?statement.
  ?statement ps:P39 ?position;
  pq:P5054 wd:Q1719882.
  OPTIONAL { ?statement pq:P580 ?start. }
  OPTIONAL { ?statement pq:P1365 ?replaces. }  
  OPTIONAL { ?statement pq:P582 ?end. }
  OPTIONAL { ?statement pq:P1534 ?cause. }
  OPTIONAL { ?statement pq:P1366 ?replaced_by. }  
}
