embed.html##defaultView:Map
SELECT ?item ?itemLabel ?c ?layer { ?item wdt:P6641 ?code . ?item wdt:P625 ?c .  OPTIONAL { ?item rdfs:label ?il. FILTER(LANG(?il)="sat") } BIND(IF(BOUND(?il),"with","without") as ?layer) SERVICE wikibase:label { bd:serviceParam wikibase:language "sat,en". } } #
