SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P31 wd:Q14350; wdt:P17 wd:Q408 . 
  MINUS { ?entity wdt:P131 []; wdt:P31 wd:Q14350; wdt:P17 wd:Q408  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
