SELECT 
   (wd:Q847 as ?item) 
   (SAMPLE(?a) as ?sample) 
   (COUNT(DISTINCT ?a) as ?ct)
   (wd:Q847 as ?type)
("*" as ?level)
("items with P641 only ([[Wikidata:WikiProject Tennis/reports/P641 only|list]])" as ?descr)
WHERE
   { ?a wdt:P641 wd:Q847 ; wikibase:statements 1  }
