SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P106 wd:Q82955 . 
  MINUS { ?entity wdt:P27 []; wdt:P106 wd:Q82955  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
