#Contributors to the Album amicorum of Petronella Moens (1762-1843), literary expert (Q72752530)
SELECT DISTINCT ?item ?itemLabel ?gender ?genderLabel ?image ?dateofbirth ?dateofdeath 
(GROUP_CONCAT(DISTINCT ?occupationLabel ; separator = " -- ") as ?Occupations)
?CommonsCategory
WHERE 
{
  ?item p:P31/ps:P31 wd:Q5.
  wd:Q72752530 p:P767/ps:P767 ?item.
  OPTIONAL {?item p:P18/ps:P18 ?image.}
  OPTIONAL {?item p:P21/ps:P21 ?gender.}
  OPTIONAL {?item p:P569/ps:P569 ?dateofbirth.}
  OPTIONAL {?item p:P570/ps:P570 ?dateofdeath.}                          
  OPTIONAL {?item p:P106/ps:P106 ?occupation.}
  OPTIONAL{ ?item p:P373/ps:P373 ?commonscat.
  BIND(URI(CONCAT("https://commons.wikimedia.org/wiki/Category:", REPLACE(?commonscat, " ", "_", "i"))) as ?CommonsCategory).}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en".
                          ?occupation rdfs:label ?occupationLabel.
                          ?item rdfs:label ?itemLabel.
                          ?gender rdfs:label ?genderLabel.
                          } 
} GROUP BY ?item ?itemLabel ?gender ?genderLabel ?image ?dateofbirth ?dateofdeath ?CommonsCategory
  ORDER BY ASC(?CommonsCategory)
