SELECT ?item (GROUP_CONCAT(DISTINCT ?seealsoLabel;separator=", ") as ?names) (COUNT(DISTINCT(?seealsoLabel)) as ?ct) WHERE { SELECT ?seealso ?seealsoLabel (MIN(?givenname) as ?item) WHERE { { SELECT ?givenname ?seealso ?seealsoLabel WHERE { VALUES ?givennametypes { wd:Q202444 wd:Q12308941 wd:Q11879590 } . ?givenname wdt:P31 ?givennametypes . ?givenname wdt:P460 ?seealso . ?seealso wdt:P31 ?givennametypes . SERVICE wikibase:label {  bd:serviceParam wikibase:language "en" . ?seealso rdfs:label ?seealsoLabel .} } } } GROUP BY ?seealso ?seealsoLabel ORDER BY ?seealsoLabel } GROUP BY ?item HAVING (?ct >1) ORDER BY DESC(?ct)
