SELECT (COUNT(?item) as ?count) ?auth ?authLabel WHERE {
  ?item wdt:P17 wd:Q38 . 
  ?item p:P2186 [ pq:P790 ?auth ] .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "it,[AUTO_LANGUAGE]". }
}
GROUP BY ?auth ?authLabel
ORDER BY DESC(?count)
