SELECT ?item WHERE {
    ?item p:P4765/ps:P4765 ?downloadurl ;
          wdt:P31 wd:Q3305213 ;
          schema:dateModified ?modified ;
  MINUS { ?item wdt:P571 [] } .
  MINUS { ?item wdt:P170 [] } .
  } ORDER BY ?modified
LIMIT 2000
