SELECT ?entity ?entityLabel ?entityDescription ?st ?sl ?ids
WHERE
{
  ?entity p:P106/ps:P106/wdt:P279* wd:Q26270618. 
  # MINUS { ?entity wdt:   [] }
  OPTIONAL { ?entity wikibase:statements ?st ; wikibase:sitelinks ?sl ; wikibase:identifiers ?ids } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" } 
}
