SELECT ?item (COUNT(?item) as ?count) WHERE {
  ?painting wdt:P31 wd:Q3305213 .  
  ?painting wdt:P180 ?item.
 { ?item wdt:P625 ?coord. } UNION { ?item wdt:P131 ?loc. }
  FILTER EXISTS { ?painting wdt:P195 ?coll . 
        ?coll wdt:P17 wd:Q668. } 
} GROUP BY ?item  
ORDER BY DESC(?count)
