#defaultView:Map
SELECT DISTINCT ?item ?itemlabel ?coor ?image ?county
{
	?item wdt:P31 wd:Q39715 . 
	?item wdt:P17 wd:Q27 .
	OPTIONAL { ?item wdt:P625 ?coor }
	OPTIONAL { ?item wdt:P18 ?image }  
	OPTIONAL { ?item wdt:P131* ?county . ?county wdt:P31 wd:Q179872 }    
}
