SELECT 
	?item
	?qid 
	(GROUP_CONCAT(DISTINCT(?enlabel)) as ?enlabels)
	(GROUP_CONCAT(CONCAT("[",str(?sitelink)," ", ?lang,"]"); separator=", ") as ?wp) 
	(COUNT(distinct ?sitelink) as ?count) 
WHERE
{
  	{ ?item wdt:P31 wd:Q506240 . } UNION { ?item wdt:P31 wd:Q20667187 . } UNION { ?item wdt:P31 wd:Q226730 . } UNION { ?item wdt:P31 wd:Q11424 . } UNION { ?item wdt:P31 wd:Q24869 . } . 
    ?item wdt:P364 wd:Q1321 . BIND(xsd:integer(STRAFTER(str(?item), "Q")) AS ?qid) .
	OPTIONAL { ?sitelink schema:about ?item . ?sitelink schema:inLanguage ?lang .  } . 
	FILTER NOT EXISTS { ?wfr schema:about ?item . ?wfr schema:inLanguage "es" } 
	OPTIONAL { ?item rdfs:label ?enlabel . FILTER(lang(?enlabel)="en")  } 
} 
GROUP BY ?item ?qid
ORDER BY DESC(?qid) 
LIMIT 5000
