SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P106 wd:Q10873124 . 
  MINUS { ?entity wdt:P1532 []; wdt:P106 wd:Q10873124  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
