#Hiskia van Harinxma
SELECT ?item ?itemLabel 
WHERE 
{
  ?item wdt:P31 wd:Q81564326 .
  ?item wdt:P361 wd:Q98277114 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
