#Cats
SELECT ?item ?wlmid ?itemLabel 
WHERE 
{
  ?item wdt:P17 wd:Q38.
  ?item wdt:P2186 ?wlmid.
  MINUS { ?item wdt:P31 ?class. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
