SELECT DISTINCT ?item ?itemLabel ?ofLabel
WHERE
{
  ?item p:P1552 ?inst_stm .
  ?inst_stm pq:P642 ?of .
  FILTER EXISTS {
    ?item wdt:P1552 wd:Q89410507.}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } # Helps get the label in your language, if not, then en language
}
