# Notable numbers
SELECT * WHERE {
  SELECT
    (SAMPLE(?item) as ?item)
    (SAMPLE(?en_label) as ?name)
    #(SAMPLE(?notation_label) as ?notation)
    (SAMPLE(?value) as ?approximate_value)
    (SAMPLE(?named_after) as ?named_after)
    (SAMPLE(?image) as ?image)
    (GROUP_CONCAT(DISTINCT ?en_class_label; SEPARATOR = ", ") AS ?classes)
  WHERE {
    ?item p:P31/ps:P31/wdt:P279* wd:Q11563.
    ?item wdt:P1181 ?value.
    ?item p:P31/ps:P31 ?class.
    #OPTIONAL {?item wdt:P913 ?notation}
    OPTIONAL {?item wdt:P138 ?named_after}
    OPTIONAL {?item wdt:P18 ?image}
    OPTIONAL {?item rdfs:label ?en_label. FILTER(LANG(?en_label) = "en")}
    OPTIONAL {?class rdfs:label ?en_class_label. FILTER(LANG(?en_class_label) = "en")}
    #OPTIONAL {?notation rdfs:label ?notation_label. FILTER(LANG(?notation_label) = "en")}
  }
  GROUP BY ?item
}
ORDER BY DESC(?name)
