SELECT ?entity ?entityLabel ?entityDescription ?st ?sl ?ids
WHERE
{
  ?entity wdt:P31 wd:Q1230708.
  MINUS { ?entity wdt:P576 [] }. 
  # MINUS { ?entity wdt:   [] }
  OPTIONAL { ?entity wikibase:statements ?st ; wikibase:sitelinks ?sl ; wikibase:identifiers ?ids } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" } 
}
