SELECT ?lyricist ?lyricistLabel ?song ?songLabel ?year{?lyricist p:P166 ?prizestmt.?lyricist wdt:P31 wd:Q5.?prizestmt ps:P166 wd:Q5449090. OPTIONAL{?prizestmt pq:P585 ?date. BIND(YEAR(?date) as ?year)}. OPTIONAL{?prizestmt pq:P1686 ?song}SERVICE wikibase:label{bd:serviceParam wikibase:language "ta,en".}}ORDER BY ?date
