#Unique value constraint report for P1614: report listing each item
SELECT DISTINCT ?item1 ?item1Label ?item2 ?item2Label ?value
{
	?item1 wdt:P1614 ?value .
	?item2 wdt:P1614 ?value .
	FILTER(?item1 != ?item2  && str(?item1)<str(?item2)) .
	SERVICE wikibase:label { bd:serviceParam wikibase:language "en,en" } .
} LIMIT 500
