SELECT ?item
WHERE {
  BIND(wd:Q33 AS ?country)

  VALUES ?type {
    wd:Q193512 # Region (19)
    wd:Q10495402 # Ministries (12)
  }
  ?item wdt:P31 ?type .

  ?item wdt:P17 ?country .

  MINUS { ?item wdt:P576 [] }
  MINUS { ?item wdt:P1366 [] }
}
