SELECT 
  (wd:Q5 as ?item)
  ("P25" as ?in)
  ("P40" as ?out)
  (COUNT(DISTINCT ?relative) as ?all)
  (COUNT(DISTINCT ?has) as ?with)
{
    ?item wdt:P25 ?relative .
    OPTIONAL { ?relative wdt:P40 ?item . BIND(?relative as ?has)  }
    ?item wdt:P31 wd:Q5 .
    ?relative wdt:P31 wd:Q5 .
}
