SELECT DISTINCT ?item 
{
    { ?item wdt:P31 wd:Q202444 } UNION { ?item wdt:P31 wd:Q11879590 } UNION { ?item wdt:P31 wd:Q12308941 } UNION { ?item wdt:P31 wd:Q3409032 }.
    ?item wdt:P407 wd:Q5287 .
  {
    {
    ?item rdfs:label ?itemLblEN
    FILTER (lang(?itemLblEN) = "en"  )  
    FILTER (regex(?itemLblEN, "^[^A-M]") )
    }
    UNION
    {
    FILTER NOT EXISTS {?item rdfs:label ?itemLbl FILTER(lang(?itemLbl)="en") } BIND(?item as ?bind1)
    }
  }  
}
LIMIT 5000
