SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P921 wd:Q202864 . 
  MINUS { ?entity wdt:P1433 []; wdt:P921 wd:Q202864  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
