#Name variants (pseudonymes etc.) of Pierre Kemp Q2677204 (from the NTA)
SELECT DISTINCT ?author ?s ?nta ?nta_uri ?namedAs #?award ?awardLabel ?year ?forwork ?forworkLabel
WHERE
{
  VALUES (?author) {(wd:Q2677204)}
  ?author p:P1006 ?s .
  ?s ps:P1006 ?nta
  BIND(URI(CONCAT("https://data.bibliotheken.nl/doc/thes/p",?nta)) AS ?nta_uri)   
  OPTIONAL {?s pq:P1810 ?namedAs.}
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "nl" .
  }
} 
