SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P31 wd:Q22044663 .
  MINUS { ?entity wdt:P576 [] } . 
  MINUS { ?entity wdt:P31 []; wdt:P31 wd:Q22044663 .
  MINUS { ?entity wdt:P576 [] }  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
