SELECT ?item WHERE {
  ?item wdt:P195 wd:Q574961 .
  ?item wdt:P31 wd:Q3305213 .  
  OPTIONAL {
    ?item p:P217 ?invstatement .
  ?invstatement ps:P217 ?inv .
  ?invstatement pq:P195 wd:Q574961 .
    }
  } ORDER BY ?inv
LIMIT 2000
