#defaultView:Map
SELECT ?chiesa ?chiesaLabel ?coord
WHERE {
  ?chiesa wdt:P31 wd:Q16970 .
  ?chiesa wdt:P708 wd:Q597646 .
  OPTIONAL { ?chiesa wdt:P625 ?coord }
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],it,en". }
}
