SELECT ?item ?itemLabel ?lieu WHERE {
  ?item wdt:P17 wd:Q142;
    (wdt:P31/(wdt:P279*)) wd:Q16970;
    wdt:P131 ?lieu.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "fr". }
}
ORDER BY DESC (xsd:integer(SUBSTR(STR(?item), 33 )))
LIMIT 100
