#Museums in the Netherlands
SELECT ?item ?itemLabel ?cityLabel
WHERE 
{
  ?item wdt:P31 wd:Q33506 .
  ?item wdt:P17 wd:Q55 .
  OPTIONAL {?item wdt:P131 ?city .}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "nl,en". }
}
