SELECT ?item ?itemDescription ?url WHERE {
  wd:P4525 wdt:P1630 ?formatterurl .
  ?item p:P195 ?collectionstatement .
  ?collectionstatement ps:P195 wd:Q56433510 .
  OPTIONAL { ?item wdt:P4525 ?id }.
  BIND(REPLACE(?id, '^(\\d+)$', CONCAT("[", ?formatterurl, " $1]")) AS ?url)  .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "et"}
  } 
LIMIT 5000
