SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity wdt:P31 wd:Q1149652.
  MINUS { ?entity wdt:P576 [] }. ?entity wdt:P31 ?grouping .} GROUP BY ?grouping HAVING (?count < 2) ORDER BY DESC(?count) LIMIT 1000
