SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity wdt:P31 ?type .
  VALUES ?type { wd:Q12443800  wd:Q467745 }
  MINUS{ ?entity wdt:P576 [] }. ?entity wdt:P31 ?grouping .} GROUP BY ?grouping HAVING (?count < 3) ORDER BY DESC(?count) LIMIT 1000
