SELECT ?datagouvid ?item ?itemLabel ?nature_of
WHERE {
  ?item wdt:P3206 ?datagouvid .
  MINUS{ ?item wdt:P31 ?nature_of. }  # without images
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],fr" }
  }
ORDER BY ?itemLabel
