SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P106/wdt:P279* wd:Q3578589 . 
  MINUS { ?entity wdt:P27 []; wdt:P106/wdt:P279* wd:Q3578589  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
