SELECT ?entity ?entityLabel ?entityDescription 
WHERE
{
  ?entity wdt:P39/wdt:P279 wd:Q100382287 . 
  MINUS { ?entity wdt:P102 []; wdt:P39/wdt:P279 wd:Q100382287  } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
LIMIT 1000
