embed.html##Noord-Nederland, provincies Groningen, Friesland, Drenthe
#defaultView:Map
SELECT ?Qvestiging ?QvestigingLabel ?coor ?partof ?partofLabel ?image ?layer WHERE {
#SELECT ?s ?sLabel ?coor ?image ?layer WHERE { 
  
       ?Qvestiging (p:P31/ps:P31) wd:Q28564;wdt:P17 wd:Q55;
          wdt:P625 ?coor ;
          wdt:P361 ?partof ;
          OPTIONAL {?Qvestiging wdt:P18 ?image .}
  
VALUES ?partof {
#Groningen  
wd:Q13928657 #Gron. Forum bieb
wd:Q59940713 #St. Biblionet Groningen
#Friesland
wd:Q61754972 #St. OB Smallingerlnd
wd:Q61912788 #St.Bieb Midden Fryslân
#Drenthe
wd:Q61754962 #St. OB Assen
wd:Q61755016 #St. Bieb Hoogeveen
wd:Q61912790 #St.OB Midden-Drenthe
wd:Q61912791 #St.OB Noordenveld
wd:Q61912792 #St.OB Westerveld
wd:Q61912789 #St.OB De Wolden
                 }
BIND(
#Groningen   
IF(?partof = wd:Q13928657, "Groningen Stad",
IF(?partof = wd:Q59940713, "Groningen Provincie",
#Friesland   
IF(?partof = wd:Q61754972, "Drachten",
IF(?partof = wd:Q61912788, "Leeuwarden en Tietjerksteradeel",
#Drenthe   
IF(?partof = wd:Q61754962, "Assen",
IF(?partof = wd:Q61912791, "Noordenveld", 
IF(?partof = wd:Q61912792, "Westerveld", 
IF(?partof = wd:Q61912790, "Midden-Drenthe", 
IF(?partof = wd:Q61912789, "De Wolden",
IF(?partof = wd:Q61755016, "Hoogeveen",   
"")))))))))) AS ?layer).  
 
SERVICE wikibase:label { bd:serviceParam wikibase:language "nl" }
}
ORDER BY ?layer ?partofLabel ?QvestigingLabel
