SELECT ?grouping (COUNT(DISTINCT ?entity) as ?count) (SAMPLE(?entity) as ?sample) WHERE { ?entity wdt:P641 ?sport ;
        wdt:P31 ?competition.
  FILTER (?sport IN (wd:Q1682809, wd:Q926191, wd:Q4179462, wd:Q4305887, wd:Q1482312, wd:Q38108))
  FILTER (?competition IN (wd:Q57305027, wd:Q2990963)). ?entity wdt:P3450 ?grouping .} GROUP BY ?grouping HAVING (?count < 2) ORDER BY DESC(?count) LIMIT 1000
