SELECT ?entity ?entityLabel ?entityDescription ?st ?sl ?ids
WHERE
{
  ?entity wdt:P31 wd:Q64063317; wdt:P131* wd:Q1186. 
  # MINUS { ?entity wdt:   [] }
  OPTIONAL { ?entity wikibase:statements ?st ; wikibase:sitelinks ?sl ; wikibase:identifiers ?ids } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" } 
}
