#defaultView:Map
SELECT DISTINCT ?item ?itemlabel ?coor ?image
{
	?item wdt:P31 wd:Q39715 . 
	?item wdt:P17 wd:Q948 .
	OPTIONAL { ?item wdt:P625 ?coor }
	OPTIONAL { ?item wdt:P18 ?image }  
	SERVICE wikibase:label { bd:serviceParam wikibase:language "ar,fr" . ?item rdfs:label ?itemlabel }  
}
