SELECT DISTINCT ?item ?cabinet { 
  ?item p:P463 ?ms .
  ?ms ps:P463 wd:Q1065 .
  FILTER NOT EXISTS { ?ms pq:P582 [] }

  OPTIONAL { 
    ?cabinet wdt:P1001 ?item ; wdt:P279* wd:Q640506 .
    hint:Prior hint:gearing "forward".
  }
}
