SELECT ?item ?stardate ?pub
WHERE
{
  ?item wdt:P179 wd:Q1077 . 
  ?item wdt:P31 wd:Q61220733 .
  OPTIONAL { ?item p:P840 [ pq:P4895 ?stardate ] }
  ?item wdt:P577 ?pub .
  FILTER NOT EXISTS { ?item wdt:P577 ?pub2 . FILTER( ?pub2 < ?pub ) }
}
ORDER BY ?pub
