SELECT DISTINCT ?item ?sitelink (CONCAT("https://el.wikipedia.org/wiki/",REPLACE(?name," ","_")) as ?sitelink2)
WHERE
{
  hint:Query hint:optimizer "None".
  ?item wdt:P971 wd:Q202444 , wd:Q9129 .
  ?sitelink schema:about ?item ; schema:isPartOf <https://el.wikipedia.org/> ; schema:name ?name 
}
ORDER BY ?sitelink
