SELECT ?person ?personLabel ?jaiolekuLabel ?koordenatuak ?jaiodata ?irudia WHERE {
  ?person wdt:P21 wd:Q6581072.
  ?person wdt:P19 wd:Q10313.
  ?person wdt:P19 ?jaioleku.
  ?jaioleku wdt:P625 ?koordenatuak.
  ?person wdt:P569 ?jaiodata.
  ?person wdt:P18 ?irudia.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "eu". }

}
