#defaultView:ImageGrid
SELECT ?software ?softwareLabel ?developerLabel ?image

WHERE {
  
  ?software wdt:P31 wd:Q341 .
  ?software p:P2537 [ pq:P366 wd:Q336 ].
  ?software wdt:P178 ?developer .
  ?developer wdt:P18 ?image.
  
            
  SERVICE wikibase:label {
		bd:serviceParam wikibase:language "en" .
    
}
}
