SELECT ?article ?articleLabel ?reviewerLabel
WHERE
{
	?article wdt:P31 wd:Q13442814 .
    ?article wdt:P4032 ?reviewer 
  
	SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }
}
