#Libros publicados por Trilce
#defaultView:Graph
SELECT ?editorial ?editorialLabel ?editorialPicture ?autor ?autorLabel ?autorPicture
WHERE 
{
  ?item wdt:P31 wd:Q3331189.
  ?item wdt:P123 wd:Q60224323.
  ?item wdt:P123 ?editorial.
  ?editorial wdt:P154 ?editorialPicture.
  ?item wdt:P50 ?autor.
   OPTIONAL {?item wdt:P18 ?itemPicture}
   OPTIONAL {?autor wdt:P18 ?autorPicture} .
  ?item wdt:P973 ?descritoURL.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],es". }

}
  ORDER BY ASC(?descritoURL)
