#title: Most popular subjects of scientific articles
#  NOTE - This scholarly query is written for use in WDQS-Main UI only  (query.wikidata.org).

SELECT (COUNT(?work) AS ?count) ?subject ?subjectLabel WHERE {
  hint:Query hint:optimizer "None".
  SERVICE wdsubgraph:scholarly_articles {
    SELECT ?work ?subject WHERE {
      ?work wdt:P31 wd:Q13442814;
        wdt:P921 ?subject.
    }
    LIMIT 10000
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
GROUP BY ?subject ?subjectLabel
ORDER BY DESC (?count)
