# Items that have a creator of "some value" which could be a q number
SELECT ?item ?username ?qnumb  WITH {
  SELECT ?qnumb ?username WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    SELECT DISTINCT ?qnumb ?username WHERE {
      ?qnumb wdt:P31 wd:Q5 ; 
             wdt:P4174 ?username .
    }
   }
 }
} AS %users
WHERE {
  INCLUDE %users
  ?item p:P170/pq:P4174 ?username.
  ?item wdt:P170 ?creatorVal
  FILTER( wikibase:isSomeValue( ?creatorVal ) )
} LIMIT 10000
